#!/usr/bin/env bash
# CI end-to-end run of the INSTALLED deployer against a real copy of this application (TASK-0032). Only systemctl,
# chown, setpriv (unprivileged it cannot switch users; it logs and runs the command) and the PHP-FPM reload are
# stubbed; maintenance mode, composer, migrations, seeders, caches, onhost:openapi, the platform backup and its
# verification, the doctor, the gate, the egress probe and the HTTP checks are real (SQLite, local backup disk,
# `php -S` serving public/). Runs A → B → A, where B adds a migration and edits the committed OpenAPI file (the
# one tracked file a build rewrites). Nothing outside the work directory is touched.
#
#   PHP_BIN=php COMPOSER_BIN=/usr/local/bin/composer bash infra/aapanel/ci/deploy-e2e.sh [work dir]
# Local Windows runs may set E2E_ALLOW_DOCTOR_FAIL=1 (the CA-bundle row fails there; the override is SHA-bound).
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "$0")/../../.." && pwd)}"
PHP_BIN="${PHP_BIN:-$(command -v php)}"
COMPOSER_BIN="${COMPOSER_BIN:-$(command -v composer)}"
PORT="${E2E_PORT:-8123}"
box="${1:-$(mktemp -d)}"
mkdir -p "$box"/{seed,bin,sbin,lib,state,etc}
box="$(cd "$box" && pwd)"
gitc() { git -c user.name=deploy-e2e -c user.email=deploy-e2e@example.invalid -c core.autocrlf=false -c init.defaultBranch=development -c commit.gpgsign=false "$@"; }
winpath() { (cd "$1" && (pwd -W 2>/dev/null || pwd)); }   # PHP on Windows needs C:/… paths inside .env
fail() { echo "E2E FAIL: $*" >&2; exit 1; }
server_pid=""
cleanup() { [ -n "$server_pid" ] && kill "$server_pid" 2>/dev/null || true; }
trap cleanup EXIT

echo "── repository: A = this working tree, B = A + a migration + an edited OpenAPI file"
(cd "$REPO_ROOT" && git ls-files -z -co --exclude-standard | tar --null -T - -cf -) | tar -xf - -C "$box/seed"
gitc init -q "$box/seed"
gitc -C "$box/seed" add -A && gitc -C "$box/seed" commit -q -m "A"
sha_a="$(git -C "$box/seed" rev-parse HEAD)"
cat > "$box/seed/database/migrations/2099_12_31_000000_deploy_e2e_noop.php" <<'EOF'
<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('deploy_e2e_marker', function (Blueprint $table) {
            $table->id();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('deploy_e2e_marker');
    }
};
EOF
printf '# deploy e2e: edited in B, regenerated by the build\n' >> "$box/seed/contracts/openapi/onhost-v1.yaml"
gitc -C "$box/seed" add -A && gitc -C "$box/seed" commit -q -m "B"
sha_b="$(git -C "$box/seed" rev-parse HEAD)"
git clone -q --bare "$box/seed" "$box/origin.git"
app="$box/app"
git clone -q -c core.autocrlf=false "$box/origin.git" "$app"
git -C "$app" checkout -q --detach "$sha_a"

echo "── the site as install.sh leaves it: .env, vendor, migrated database"
: > "$app/database/e2e.sqlite"
cat > "$box/etc/app.env" <<EOF
APP_NAME=ONhost
APP_ENV=staging   # staging | production
APP_KEY=base64:$("$PHP_BIN" -r 'echo base64_encode(random_bytes(32));')
APP_DEBUG=false
APP_URL=https://staging.test
DB_CONNECTION=sqlite
DB_DATABASE=$(winpath "$app/database")/e2e.sqlite
QUEUE_CONNECTION=database
CACHE_STORE=file
SESSION_DRIVER=file
MAIL_MAILER=log
LOG_CHANNEL=single
ONHOST_SECRETS_DRIVER=db
ONHOST_PLATFORM_BACKUP_DISK=local
EOF
# the site's .env IS the root-owned environment file (install.sh: a symlink; a hard link where symlinks need privileges)
if ! { ln -sfn "$box/etc/app.env" "$app/.env" 2>/dev/null && [ -L "$app/.env" ]; }; then rm -f "$app/.env"; ln -f "$box/etc/app.env" "$app/.env"; fi
(cd "$app" && COMPOSER_ALLOW_SUPERUSER=1 "$PHP_BIN" "$COMPOSER_BIN" install --no-dev --no-interaction --prefer-dist --no-progress --quiet)
(cd "$app" && "$PHP_BIN" artisan migrate --force --no-interaction >/dev/null)

echo "── stubs (systemctl, chown, fpm reload, setpriv; flock only where the OS has none)"
for tool in systemctl chown fpm-reload; do printf '#!/usr/bin/env bash\necho "%s $*" >> "%s/stub.log"\n[ "${1:-}" = is-active ] && exit 3\nexit 0\n' "$tool" "$box" > "$box/bin/$tool"; done
# setpriv: the deployer hands every artisan/composer call to it (as_run); unprivileged it can only run the command
printf '#!/usr/bin/env bash\necho "setpriv $*" >> "%s/stub.log"\nwhile [ $# -gt 0 ] && [ "$1" != -- ]; do shift; done\nshift\nexec "$@"\n' "$box" > "$box/bin/setpriv"
command -v flock >/dev/null 2>&1 || printf '#!/usr/bin/env bash\nexit 0\n' > "$box/bin/flock"
chmod +x "$box/bin/"*

echo "── serve public/ on 127.0.0.1:$PORT"
(cd "$app" && exec "$PHP_BIN" -S "127.0.0.1:$PORT" -t public vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php) > "$box/server.log" 2>&1 &
server_pid=$!
for _ in $(seq 1 50); do curl -s -o /dev/null "http://127.0.0.1:$PORT/up" && break; sleep 0.2; done

echo "── install the deployer from A"
SHA="$sha_a" FIRST=1 APP_DIR="$app" ENV_FILE="$box/etc/app.env" DEPLOY_STATE_DIR="$box/state" DEPLOYER_BIN="$box/sbin/onhost-deploy" DEPLOYER_LIB_DIR="$box/lib" \
  DEPLOY_OWNER_UID="$(id -u)" bash "$REPO_ROOT/infra/aapanel/install-deployer.sh"

echo "── the deployer's lists: no unit (systemctl is stubbed), the environment spec, the doctor rows this site runs non-OK"
# the expected-nonok list is drafted from A's own doctor the way staging-launch.md S4b does it; this run proves the release
# mechanics, the refusal of a row outside the list is pinned in DeployGateTest
(umask 077
  printf '# e2e: no unit is managed here\n' > "$box/state/expected-units"
  printf 'APP_ENV=staging\nAPP_DEBUG=false\nAPP_URL=https://staging.test\nMAIL_MAILER=log\nONHOST_SECRETS_DRIVER=db\nAI_ANTHROPIC_*=\nONHOST_CONSOLE_RELAY_KEY=\n' > "$box/state/expected-env"
  printf '# nothing listens here: the probe must fail\n127.0.0.1:1\n' > "$box/state/egress-blocked")
(cd "$app" && "$PHP_BIN" artisan onhost:doctor --json > "$box/doctor-before.json") || true
"$PHP_BIN" "$box/lib/deploy-gate.php" nonok --report "$box/doctor-before.json" --production 0 > "$box/expected-nonok.draft" || fail "cannot draft the expected-nonok list"
(umask 077; cp "$box/expected-nonok.draft" "$box/state/expected-nonok")
echo "   $(grep -c . "$box/state/expected-nonok" || true) row(s) expected non-OK"

deploy() { # $1 = sha
  local allow=()
  [ "${E2E_ALLOW_DOCTOR_FAIL:-0}" = 1 ] && allow=(ALLOW_DOCTOR_FAIL="${1:0:12}:local e2e run without a CA bundle")
  (cd "$app" && env PATH="$box/bin:$PATH" ${allow[@]+"${allow[@]}"} SITE=staging.test APP_DIR="$app" PHP="$PHP_BIN" COMPOSER="$COMPOSER_BIN" \
    RUN_USER="$(id -un)" ENV_FILE="$box/etc/app.env" DEPLOY_STATE_DIR="$box/state" DEPLOY_LIB_DIR="$box/lib" PHP_FPM_RELOAD="$box/bin/fpm-reload" \
    DEPLOY_HTTP_BASE="http://127.0.0.1:$PORT" DEPLOY_OWNER_UID="$(id -u)" DEPLOY_WORK_DIR="$box/work/staging.test" \
    DEPLOY_SAFE_PATH="$box/bin:$(dirname "$PHP_BIN"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    DEPLOY_OPERATOR=ci-e2e REF="$1" EXPECTED_SHA="$1" bash "$box/sbin/onhost-deploy")
}
check() { # $1 = sha expected live
  [ "$(git -C "$app" rev-parse HEAD)" = "$1" ] || fail "HEAD is not $1"
  [ "$(cut -d' ' -f1 "$app/VERSION")" = "$1" ] || fail "VERSION is not $1"
  grep -q "\"sha\":\"$1\"" "$box/state/last-good.json" || fail "last-good.json is not $1"
  [ ! -f "$app/storage/framework/down" ] || fail "the site is still in maintenance"
  [ "$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/up")" = 200 ] || fail "public /up is not 200"
  [ -z "$(git -C "$app" status --porcelain --untracked-files=all -- . ':(exclude)contracts/openapi/onhost-v1.yaml' ':(exclude)VERSION')" ] || fail "the tree is not clean"
}

echo "── deploy A (first gated release)";  deploy "$sha_a" || fail "deploy A rc=$?"; check "$sha_a"
echo "── deploy B (migration + OpenAPI edit)"; deploy "$sha_b" || fail "deploy B rc=$?"; check "$sha_b"
"$PHP_BIN" -r '$p = new PDO("sqlite:".$argv[1]); exit((int) $p->query("select count(*) from migrations where migration = \"2099_12_31_000000_deploy_e2e_noop\"")->fetchColumn() === 1 ? 0 : 1);' "$(winpath "$app/database")/e2e.sqlite" || fail "B's migration did not run"
echo "── deploy A again (rollback over a migration: the backup is taken, not skipped)"; deploy "$sha_a" || fail "rollback rc=$?"; check "$sha_a"
[ "$(grep -c ' rc=0 ' "$box/state/deploy.log")" = 3 ] || fail "deploy.log does not hold three successful runs"
[ "$(grep -c ' set=platform-backups/' "$box/state/deploy.log")" = 3 ] || fail "not every run took a verified backup"
# review round 0 (security HIGH): the site's PHP ran through setpriv, as the run user — composer and migrations included
grep -q '^setpriv .* -- env -i .*composer.* install' "$box/stub.log" && grep -q '^setpriv .* -- env -i .*artisan migrate' "$box/stub.log" \
  || fail "the deployer did not run composer and artisan through setpriv"
echo "E2E OK: A → B → A released through the gate ($box)"
