<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Onhost\Domain\Notifications\Models\NotificationTemplate;

/**
 * Versioned, localized transactional templates (blueprint §72). Re-running keeps the
 * version when the body is unchanged and bumps it when the text changed, so old mails
 * remain reproducible. Placeholders: {{name}}.
 */
final class NotificationTemplateSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->templates() as $key => $t) {
            foreach (['cs', 'en'] as $locale) {
                $this->upsert($key, $locale, $t[$locale]['subject'], $t[$locale]['body'], $t['vars'], (bool) ($t['mandatory'] ?? false));
            }
        }
    }

    private function upsert(string $key, string $locale, string $subject, string $body, array $vars, bool $mandatory): void
    {
        $current = NotificationTemplate::query()->where('key', $key)->where('channel', 'mail')->where('locale', $locale)->orderByDesc('version')->first();
        if ($current !== null && $current->subject === $subject && $current->body === $body) {
            $current->forceFill(['variables' => $vars, 'mandatory' => $mandatory, 'state' => 'active'])->save();

            return;
        }
        NotificationTemplate::query()->create(['key' => $key, 'channel' => 'mail', 'locale' => $locale, 'version' => ($current?->version ?? 0) + 1, 'subject' => $subject, 'body' => $body, 'variables' => $vars, 'mandatory' => $mandatory, 'state' => 'active']);
        if ($current !== null) {
            $current->forceFill(['state' => 'superseded'])->save();
        }
    }

    /** @return array<string, array{cs:array{subject:string,body:string}, en:array{subject:string,body:string}, vars:list<string>, mandatory?:bool}> */
    private function templates(): array
    {
        $sig = ['cs' => "\n\nTým ONhost", 'en' => "\n\nThe ONhost team"];

        return [
            'welcome' => ['vars' => ['jmeno', 'organizace', 'url'], 'cs' => ['subject' => 'Vítejte v ONhost', 'body' => "Dobrý den, {{jmeno}},\n\núčet pro {{organizace}} je založený. Do klientské sekce se dostanete zde: {{url}}\n\nCo dál:\n- dobijte kredit nebo si nastavte platební metodu,\n- objednejte první službu,\n- zapněte si dvoufázové ověření.".$sig['cs']], 'en' => ['subject' => 'Welcome to ONhost', 'body' => "Hello {{jmeno}},\n\nthe account for {{organizace}} is ready. Open the customer panel here: {{url}}\n\nNext steps:\n- top up credit or add a payment method,\n- order your first service,\n- enable two-factor authentication.".$sig['en']]],
            'invitation' => ['vars' => ['organizace', 'role', 'url'], 'cs' => ['subject' => 'Pozvánka do organizace {{organizace}}', 'body' => "Byli jste pozváni do organizace {{organizace}} v roli {{role}}.\n\nPozvánku přijmete zde (platí 7 dní): {{url}}".$sig['cs']], 'en' => ['subject' => 'Invitation to {{organizace}}', 'body' => "You have been invited to {{organizace}} as {{role}}.\n\nAccept the invitation here (valid 7 days): {{url}}".$sig['en']]],
            'order-received' => ['vars' => ['cislo', 'castka', 'jmeno', 'url'], 'cs' => ['subject' => 'Objednávka {{cislo}} přijata', 'body' => "Dobrý den, {{jmeno}},\n\npřijali jsme objednávku {{cislo}} v celkové výši {{castka}}. Stav sledujte v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Order {{cislo}} received', 'body' => "Hello {{jmeno}},\n\nwe have received order {{cislo}} for {{castka}}. Track it in the customer panel: {{url}}".$sig['en']]],
            'service-activated' => ['vars' => ['sluzba', 'pristup', 'url'], 'cs' => ['subject' => 'Služba je aktivní', 'body' => "Vaše služba ({{sluzba}}) je zřízená a aktivní.\n\nPřístup: {{pristup}}\n\nDetaily, konzoli a logy najdete v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Your service is active', 'body' => "Your service ({{sluzba}}) has been provisioned and is active.\n\nAccess: {{pristup}}\n\nDetails, console and logs are in the customer panel: {{url}}".$sig['en']]],
            'service-plan-changed' => ['vars' => ['sluzba', 'tarif', 'url'], 'cs' => ['subject' => 'Tarif služby {{sluzba}} změněn na {{tarif}}', 'body' => "Služba {{sluzba}} běží od teď v tarifu {{tarif}}. Nové limity platí do minuty; nová cena se účtuje od příštího období.\n\nSlužba: {{url}}".$sig['cs']], 'en' => ['subject' => 'Plan of {{sluzba}} changed to {{tarif}}', 'body' => "Service {{sluzba}} now runs on the {{tarif}} plan. The new limits apply within a minute; the new price is charged from the next period.\n\nService: {{url}}".$sig['en']]],
            'digest-weekly' => ['vars' => ['organizace', 'shrnuti', 'url'], 'cs' => ['subject' => 'Týdenní přehled účtu {{organizace}}', 'body' => "Přehled za uplynulý týden a výhled na příští dva:\n\n{{shrnuti}}\n\nPanel: {{url}}\n\nPřehled si můžete vypnout v nastavení oznámení.".$sig['cs']], 'en' => ['subject' => 'Weekly summary for {{organizace}}', 'body' => "The past week and the next two:\n\n{{shrnuti}}\n\nPanel: {{url}}\n\nYou can switch the summary off in the notification settings.".$sig['en']]],
            'digest-staff' => ['vars' => ['datum', 'shrnuti', 'url'], 'cs' => ['subject' => 'Provozní přehled {{datum}}', 'body' => "Stav platformy k dnešnímu ránu:\n\n{{shrnuti}}\n\nNástěnka provozu: {{url}}".$sig['cs']], 'en' => ['subject' => 'Operations summary {{datum}}', 'body' => "The platform this morning:\n\n{{shrnuti}}\n\nOperations board: {{url}}".$sig['en']]],
            'renewal-underfunded' => ['vars' => ['castka', 'chybi', 'datum', 'url'], 'cs' => ['subject' => 'Na obnovy do {{datum}} chybí {{chybi}}', 'body' => "Do {{datum}} se obnovují služby za {{castka}}; na kreditu chybí {{chybi}}. Dobijte prosím kredit, aby obnovy proběhly bez přerušení — nebo si v panelu zapněte automatické dobití.\n\nFakturace: {{url}}".$sig['cs']], 'en' => ['subject' => 'Renewals until {{datum}} are short by {{chybi}}', 'body' => "Services worth {{castka}} renew until {{datum}}; the credit is short by {{chybi}}. Please top up so the renewals go through — or switch on automatic top-ups in the panel.\n\nBilling: {{url}}".$sig['en']]],
            'service-usage-high' => ['vars' => ['sluzba', 'metrika', 'procenta', 'nabidka', 'url'], 'cs' => ['subject' => 'Služba {{sluzba}} využívá {{procenta}} % kapacity', 'body' => "Služba {{sluzba}} využívá {{procenta}} % svého limitu ({{metrika}}).\n\n{{nabidka}}\n\nSlužba a tarify: {{url}}".$sig['cs']], 'en' => ['subject' => '{{sluzba}} is using {{procenta}} % of its plan', 'body' => "Service {{sluzba}} uses {{procenta}} % of its limit ({{metrika}}).\n\n{{nabidka}}\n\nService and plans: {{url}}".$sig['en']]],
            'service-period-changed' => ['vars' => ['sluzba', 'obdobi', 'konec', 'url'], 'cs' => ['subject' => 'Období platby služby {{sluzba}} změněno na {{obdobi}}', 'body' => "Služba {{sluzba}} se od teď platí {{obdobi}}. Nové období běží do {{konec}}; nevyužitý zbytek původního období jsme odečetli z ceny.\n\nSlužba: {{url}}".$sig['cs']], 'en' => ['subject' => 'Billing period of {{sluzba}} changed to {{obdobi}}', 'body' => "Service {{sluzba}} is now billed {{obdobi}}. The new period runs until {{konec}}; the unused rest of the previous period was credited against the price.\n\nService: {{url}}".$sig['en']]],
            'service-shared' => ['vars' => ['sluzba', 'organizace', 'opravneni', 'do', 'url'], 'cs' => ['subject' => 'Byla vám svěřena služba {{sluzba}}', 'body' => "{{organizace}} vám dává přístup ke službě {{sluzba}}.\n\nCo smíte: {{opravneni}}\nPlatí do: {{do}}\n\nOtevřete ji zde: {{url}}\n\nUvidíte jen tuto službu — žádné faktury, platby ani ostatní služby organizace. Přístup může majitel kdykoli odebrat.".$sig['cs']], 'en' => ['subject' => 'The service {{sluzba}} was shared with you', 'body' => "{{organizace}} gives you access to the service {{sluzba}}.\n\nWhat you may do: {{opravneni}}\nValid until: {{do}}\n\nOpen it here: {{url}}\n\nYou will see this service only — no invoices, payments or other services of the organization. The owner can take the access back at any time.".$sig['en']]],
            'order-cancelled' => ['vars' => ['cislo', 'castka', 'kam', 'doklad', 'url'], 'cs' => ['subject' => 'Objednávka {{cislo}} byla zrušena', 'body' => "Objednávku {{cislo}} jsme zrušili.\n\nČástku {{castka}} jsme vrátili {{kam}}; opravný doklad {{doklad}} najdete mezi fakturami. Za zrušenou objednávku nic neplatíte.\n\nObjednávky: {{url}}".$sig['cs']], 'en' => ['subject' => 'Order {{cislo}} was cancelled', 'body' => "We cancelled order {{cislo}}.\n\n{{castka}} went back {{kam}}; the credit note {{doklad}} is among your invoices. You pay nothing for the cancelled order.\n\nOrders: {{url}}".$sig['en']]],
            'order-refunded' => ['vars' => ['cislo', 'castka', 'polozky', 'kam', 'doklad', 'url'], 'cs' => ['subject' => 'Objednávka {{cislo}}: {{castka}} se vrací', 'body' => "Část objednávky {{cislo}} se nám nepodařilo zřídit:\n\n{{polozky}}\n\nČástku {{castka}} jsme vrátili {{kam}}; opravný doklad {{doklad}} najdete mezi fakturami. Za nezřízené položky nic neplatíte.\n\nObjednávky: {{url}}".$sig['cs']], 'en' => ['subject' => 'Order {{cislo}}: {{castka}} returned', 'body' => "We could not deliver part of order {{cislo}}:\n\n{{polozky}}\n\n{{castka}} went back {{kam}}; the credit note {{doklad}} is among your invoices. You pay nothing for what was not delivered.\n\nOrders: {{url}}".$sig['en']]],
            'chargeback-approved' => ['vars' => ['sluzba', 'castka', 'procenta', 'url'], 'cs' => ['subject' => 'Vrácení kreditu za {{sluzba}} schváleno', 'body' => "Technická podpora schválila vaši žádost. Až službu {{sluzba}} v panelu zrušíte, připíšeme vám {{castka}} ({{procenta}} % nevyužitého zaplaceného období) jako kredit na účet.\n\nSlužby: {{url}}".$sig['cs']], 'en' => ['subject' => 'Credit refund for {{sluzba}} approved', 'body' => "Support approved your request. Once you cancel {{sluzba}} in the panel we credit {{castka}} ({{procenta}} % of the unused paid period) to your account.\n\nServices: {{url}}".$sig['en']]],
            'chargeback-rejected' => ['vars' => ['sluzba', 'duvod', 'url'], 'cs' => ['subject' => 'Vrácení kreditu za {{sluzba}} jsme nemohli schválit', 'body' => "Vaši žádost o vrácení kreditu za službu {{sluzba}} jsme posoudili a nemůžeme ji schválit. Důvod: {{duvod}}\n\nChcete-li rozhodnutí probrat, napište podpoře: {{url}}".$sig['cs']], 'en' => ['subject' => 'Credit refund for {{sluzba}} could not be approved', 'body' => "We reviewed your refund request for {{sluzba}} and cannot approve it. Reason: {{duvod}}\n\nTo discuss the decision, write to support: {{url}}".$sig['en']]],
            'chargeback-refunded' => ['vars' => ['sluzba', 'castka', 'url'], 'cs' => ['subject' => 'Kredit za zrušenou službu {{sluzba}} připsán', 'body' => "Služba {{sluzba}} byla zrušena a {{castka}} je připsáno jako kredit na váš účet. Kredit použijete na jakoukoli další službu.\n\nFakturace: {{url}}".$sig['cs']], 'en' => ['subject' => 'Credit for the cancelled service {{sluzba}}', 'body' => "{{sluzba}} has been cancelled and {{castka}} is credited to your account, usable for any other service.\n\nBilling: {{url}}".$sig['en']]],
            'marketplace-assigned' => ['vars' => ['sluzba', 'zakaznik', 'termin', 'zadani', 'url'], 'cs' => ['subject' => 'Nová zakázka z marketplace: {{sluzba}}', 'body' => "Zákazník {{zakaznik}} objednal {{sluzba}}. Termín dodání: {{termin}}.\n\nZadání:\n{{zadani}}\n\nZakázku převezměte a po dodání ji označte v partnerském portálu: {{url}}".$sig['cs']], 'en' => ['subject' => 'New marketplace job: {{sluzba}}', 'body' => "{{zakaznik}} ordered {{sluzba}}. Delivery due: {{termin}}.\n\nBrief:\n{{zadani}}\n\nStart the job and mark it delivered in the partner portal: {{url}}".$sig['en']]],
            'marketplace-delivered' => ['vars' => ['sluzba', 'poznamka', 'dni', 'url'], 'cs' => ['subject' => 'Dodáno: {{sluzba}}', 'body' => "Partner dodal {{sluzba}}.\n\n{{poznamka}}\n\nPotvrďte převzetí v panelu, nebo do {{dni}} dní podejte reklamaci; poté se dodání považuje za převzaté: {{url}}".$sig['cs']], 'en' => ['subject' => 'Delivered: {{sluzba}}', 'body' => "The partner delivered {{sluzba}}.\n\n{{poznamka}}\n\nAccept it in the panel or dispute it within {{dni}} days; afterwards the delivery counts as accepted: {{url}}".$sig['en']]],
            'referral-rewarded' => ['vars' => ['body', 'kredit', 'url'], 'cs' => ['subject' => 'Odměna za doporučení: +{{body}} bodů a {{kredit}}', 'body' => "Zákazník, kterého jste doporučili, zaplatil první doklad. Připsali jsme vám {{body}} bodů a {{kredit}} promo kreditu.\n\nVáš odkaz k doporučení najdete v nastavení účtu: {{url}}".$sig['cs']], 'en' => ['subject' => 'Referral reward: +{{body}} points and {{kredit}}', 'body' => "The customer you referred paid their first document. We credited {{body}} points and {{kredit}} of promo credit.\n\nYour invite link is in the account settings: {{url}}".$sig['en']]],
            'loyalty-streak' => ['vars' => ['mesice', 'url'], 'cs' => ['subject' => 'Věrnostní série: {{mesice}} měsíců plateb včas', 'body' => "Děkujeme — {{mesice}} měsíců po sobě jste měli všechny doklady zaplacené včas. Finance posoudí trvalou věrnostní slevu na vaše další objednávky; dáme vám vědět.\n\nPřehled: {{url}}".$sig['cs']], 'en' => ['subject' => 'Loyalty streak: {{mesice}} months paid on time', 'body' => "Thank you — {{mesice}} months in a row every document was paid on time. Finance will review a permanent loyalty discount on your future orders; we will let you know.\n\nOverview: {{url}}".$sig['en']]],
            'loyalty-campaign' => ['vars' => ['kampan', 'mise', 'do', 'url'], 'cs' => ['subject' => 'Nová kampaň: {{kampan}}', 'body' => "Spouštíme kampaň {{kampan}}. Mise: {{mise}}. Platí do {{do}}; za splnění všech misí získáte odznak a body.\n\nPřehled misí: {{url}}".$sig['cs']], 'en' => ['subject' => 'New campaign: {{kampan}}', 'body' => "The campaign {{kampan}} is on. Missions: {{mise}}. Runs until {{do}}; completing every mission earns a badge and points.\n\nYour missions: {{url}}".$sig['en']]],
            'loyalty-level-up' => ['vars' => ['uroven', 'body', 'odmena', 'url'], 'cs' => ['subject' => 'Věrnostní program: úroveň {{uroven}}', 'body' => "Máte {{body}} bodů a dosáhli jste úrovně {{uroven}}. Odměna: {{odmena}} (promo kredit na účtu).\n\nBody získáváte za zaplacené objednávky, včasné platby, zapnuté 2FA, zálohy a monitoring. Přehled: {{url}}".$sig['cs']], 'en' => ['subject' => 'Loyalty programme: level {{uroven}}', 'body' => "You have {{body}} points and reached level {{uroven}}. Reward: {{odmena}} (promo credit on your account).\n\nPoints come from paid orders, on-time payments, 2FA, backups and monitoring. Overview: {{url}}".$sig['en']]],
            'service-migration-scheduled' => ['vars' => ['sluzba', 'zacatek', 'od', 'do', 'duvod', 'url'], 'cs' => ['subject' => 'Stěhování serveru {{sluzba}} je naplánované', 'body' => "Server {{sluzba}} přestěhujeme na jiný uzel ({{duvod}}). Stěhování začne {{zacatek}} a server bude po dobu přenosu dat vypnutý; data, nastavení i plány zůstanou, změní se jen adresa, kterou vám pošleme.\n\nNevyhovuje termín? V panelu ho posunete kamkoli v okně {{od}} – {{do}}: {{url}}".$sig['cs']], 'en' => ['subject' => 'Migration of server {{sluzba}} is scheduled', 'body' => "Server {{sluzba}} moves to another node ({{duvod}}). The migration starts {{zacatek}}; the server is off while the data moves; data, settings and schedules are kept, only the address changes (we will send it).\n\nDoes the time not suit you? Move it anywhere within {{od}} – {{do}} in the panel: {{url}}".$sig['en']]],
            'service-migrated' => ['vars' => ['sluzba', 'adresa', 'url'], 'cs' => ['subject' => 'Server {{sluzba}} byl přestěhován', 'body' => "Server {{sluzba}} teď běží na jiném uzlu. Nová adresa: {{adresa}}.\n\nData, nastavení, plánované úlohy i zálohy zůstaly; jen adresu prosím aktualizujte u hráčů.\n\nSlužba: {{url}}".$sig['cs']], 'en' => ['subject' => 'Server {{sluzba}} has moved', 'body' => "Server {{sluzba}} now runs on another node. New address: {{adresa}}.\n\nData, settings, schedules and backups are kept; only the address changed for your players.\n\nService: {{url}}".$sig['en']]],
            'service-suspended' => ['vars' => ['duvod', 'url'], 'cs' => ['subject' => 'Služba byla pozastavena', 'body' => "Služba byla pozastavena. Důvod: {{duvod}}.\n\nData zůstávají zachována. Jakmile bude důvod odstraněn (např. uhrazen doklad), služba se obnoví: {{url}}".$sig['cs']], 'en' => ['subject' => 'Your service has been suspended', 'body' => "The service has been suspended. Reason: {{duvod}}.\n\nYour data is kept. Once the reason is cleared (for example the invoice is paid) the service resumes: {{url}}".$sig['en']]],
            'ticket-ack' => ['vars' => ['cislo', 'predmet', 'sla', 'url'], 'cs' => ['subject' => 'Přijali jsme váš požadavek {{cislo}}', 'body' => "Váš požadavek „{{predmet}}“ jsme zaevidovali pod číslem {{cislo}}.\n\nPrvní odpověď dostanete nejpozději do {{sla}} minut. Průběh sledujete zde: {{url}}".$sig['cs']], 'en' => ['subject' => 'We received your request {{cislo}}', 'body' => "Your request “{{predmet}}” is registered as {{cislo}}.\n\nYou will get a first reply within {{sla}} minutes. Follow it here: {{url}}".$sig['en']]],
            'ticket-reply' => ['vars' => ['cislo', 'predmet', 'uryvek', 'url'], 'cs' => ['subject' => 'Re: {{predmet}} ({{cislo}})', 'body' => "Podpora odpověděla na váš požadavek {{cislo}}:\n\n{{uryvek}}\n\nCelou konverzaci a odpověď najdete zde: {{url}}".$sig['cs']], 'en' => ['subject' => 'Re: {{predmet}} ({{cislo}})', 'body' => "Support replied to your request {{cislo}}:\n\n{{uryvek}}\n\nThe full conversation is here: {{url}}".$sig['en']]],
            'invoice' => ['mandatory' => true, 'vars' => ['cislo', 'castka', 'splatnost', 'url'], 'cs' => ['subject' => 'Doklad {{cislo}}', 'body' => "Vystavili jsme doklad {{cislo}} na částku {{castka}}.\n\nDoklad ve formátu PDF i ve strukturované podobě (UBL) si stáhnete v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Document {{cislo}}', 'body' => "We issued document {{cislo}} for {{castka}}.\n\nDownload the PDF and the structured (UBL) version in the customer panel: {{url}}".$sig['en']]],
            'invoice-overdue' => ['mandatory' => true, 'vars' => ['cislo', 'castka', 'url'], 'cs' => ['subject' => 'Doklad {{cislo}} je po splatnosti', 'body' => "Doklad {{cislo}} ({{castka}}) je po splatnosti. Uhraďte jej prosím co nejdříve: {{url}}\n\nPokud už platba odešla, tento e-mail ignorujte — spárujeme ji automaticky.".$sig['cs']], 'en' => ['subject' => 'Document {{cislo}} is overdue', 'body' => "Document {{cislo}} ({{castka}}) is overdue. Please pay it as soon as possible: {{url}}\n\nIf the payment is already on its way, ignore this e-mail — it is matched automatically.".$sig['en']]],
            'dunning-notice' => ['vars' => ['dni', 'url'], 'cs' => ['subject' => 'Upomínka: neuhrazený doklad ({{dni}} dní po splatnosti)', 'body' => 'Evidujeme neuhrazený doklad {{dni}} dní po splatnosti. Abychom nemuseli službu omezit, uhraďte jej prosím zde: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Reminder: unpaid document ({{dni}} days overdue)', 'body' => 'We have an unpaid document {{dni}} days overdue. To avoid limiting the service, please pay it here: {{url}}'.$sig['en']]],
            'dunning-suspended' => ['vars' => ['url'], 'cs' => ['subject' => 'Služba pozastavena pro neplacení', 'body' => "Pro neuhrazený doklad jsme službu pozastavili. Data zůstávají zachována.\n\nPo přijetí platby se služba automaticky obnoví: {{url}}".$sig['cs']], 'en' => ['subject' => 'Service suspended for non-payment', 'body' => "Because of an unpaid document the service has been suspended. Your data is kept.\n\nThe service resumes automatically once the payment arrives: {{url}}".$sig['en']]],
            'dunning-termination' => ['mandatory' => true, 'vars' => ['datum', 'url'], 'cs' => ['subject' => 'Poslední upozornění: služba bude zrušena {{datum}}', 'body' => "Doklad stále není uhrazen. Služba bude zrušena {{datum}}; zálohy držíme ještě po dobu retenční lhůty.\n\nUhrazením do tohoto data se zrušení odvolá: {{url}}".$sig['cs']], 'en' => ['subject' => 'Final notice: the service will be terminated on {{datum}}', 'body' => "The document is still unpaid. The service will be terminated on {{datum}}; backups are kept for the retention period.\n\nPaying before that date cancels the termination: {{url}}".$sig['en']]],
            'renewal-failed' => ['vars' => ['castka', 'do', 'url'], 'cs' => ['subject' => 'Prodloužení služby se nezdařilo', 'body' => "Prodloužení služby vyžaduje {{castka}}, na kreditu ale není dostatek prostředků. Služba běží do {{do}}.\n\nDobijte kredit: {{url}}".$sig['cs']], 'en' => ['subject' => 'Service renewal failed', 'body' => "Renewing the service needs {{castka}} but the wallet balance is insufficient. The service runs until {{do}}.\n\nTop up here: {{url}}".$sig['en']]],
            'domain-registered' => ['vars' => ['domena', 'expirace', 'url'], 'cs' => ['subject' => 'Doména {{domena}} je zaregistrována', 'body' => "Doména {{domena}} je registrována a aktivní, platí do {{expirace}}.\n\nDNS a nastavení spravujete zde: {{url}}".$sig['cs']], 'en' => ['subject' => 'Domain {{domena}} is registered', 'body' => "Domain {{domena}} is registered and active until {{expirace}}.\n\nManage DNS and settings here: {{url}}".$sig['en']]],
            'domain-renewal' => ['mandatory' => true, 'vars' => ['domena', 'dni', 'expirace', 'autorenew', 'url'], 'cs' => ['subject' => 'Doména {{domena}} expiruje za {{dni}} dní', 'body' => "Doména {{domena}} expiruje {{expirace}}. Automatické prodloužení je {{autorenew}}.\n\nZkontrolujte kredit nebo prodlužte ručně: {{url}}".$sig['cs']], 'en' => ['subject' => 'Domain {{domena}} expires in {{dni}} days', 'body' => "Domain {{domena}} expires on {{expirace}}. Automatic renewal is {{autorenew}}.\n\nCheck your credit or renew manually: {{url}}".$sig['en']]],
            'domain-renewed' => ['vars' => ['domena', 'expirace', 'url'], 'cs' => ['subject' => 'Doména {{domena}} prodloužena', 'body' => 'Doména {{domena}} byla prodloužena, nově platí do {{expirace}}. Doklad najdete v klientské sekci: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Domain {{domena}} renewed', 'body' => 'Domain {{domena}} has been renewed and is now valid until {{expirace}}. The document is in the customer panel: {{url}}'.$sig['en']]],
            'domain-renewal-failed' => ['mandatory' => true, 'vars' => ['domena', 'duvod', 'url'], 'cs' => ['subject' => 'Prodloužení domény {{domena}} se nezdařilo', 'body' => "Doménu {{domena}} se nepodařilo prodloužit: {{duvod}}.\n\nDobijte kredit nebo prodlužte ručně, jinak doména expiruje: {{url}}".$sig['cs']], 'en' => ['subject' => 'Renewing domain {{domena}} failed', 'body' => "Domain {{domena}} could not be renewed: {{duvod}}.\n\nTop up or renew manually, otherwise the domain expires: {{url}}".$sig['en']]],
            'registrar-credit-low' => ['vars' => ['ucet', 'kredit', 'url'], 'cs' => ['subject' => 'Kredit u registrátora klesl na {{kredit}}', 'body' => "Kredit připojeného účtu {{ucet}} klesl na {{kredit}}. Obnovy domén u registrátora by nemusely projít — dobijte kredit v jeho administraci.\n\nPřehled: {{url}}".$sig['cs']], 'en' => ['subject' => 'Registrar credit dropped to {{kredit}}', 'body' => "The credit of the connected account {{ucet}} dropped to {{kredit}}. Domain renewals at the registrar may fail — top it up in the registrar's administration.\n\nOverview: {{url}}".$sig['en']]],
            'domain-external-expiry' => ['mandatory' => true, 'vars' => ['domena', 'dni', 'expirace', 'registrator', 'url'], 'cs' => ['subject' => 'Doména {{domena}} expiruje za {{dni}} dní', 'body' => "Doména {{domena}} je registrována u {{registrator}} a expiruje {{expirace}}. Prodlužte ji v administraci registrátora, nebo ji převeďte k nám.\n\nPřehled: {{url}}".$sig['cs']], 'en' => ['subject' => 'Domain {{domena}} expires in {{dni}} days', 'body' => "Domain {{domena}} is registered at {{registrator}} and expires on {{expirace}}. Renew it in the registrar's administration or transfer it to us.\n\nOverview: {{url}}".$sig['en']]],
            'domain-expired' => ['mandatory' => true, 'vars' => ['domena', 'url'], 'cs' => ['subject' => 'Doména {{domena}} expirovala', 'body' => 'Doména {{domena}} expirovala. V ochranné lhůtě ji lze ještě obnovit — čím dříve, tím levněji: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Domain {{domena}} has expired', 'body' => 'Domain {{domena}} has expired. It can still be restored during the grace period — the sooner the cheaper: {{url}}'.$sig['en']]],
            'domain-auth-info' => ['mandatory' => true, 'vars' => ['domena', 'url'], 'cs' => ['subject' => 'AUTH-ID pro doménu {{domena}} bylo odesláno', 'body' => "Na základě ověřeného požadavku registrátor odeslal AUTH-ID pro převod domény {{domena}} držiteli.\n\nPokud jste o převod nežádali, ihned kontaktujte podporu: {{url}}".$sig['cs']], 'en' => ['subject' => 'AUTH-ID for {{domena}} has been sent', 'body' => "Following a verified request, the registrar sent the AUTH-ID for transferring {{domena}} to the registrant.\n\nIf you did not request this, contact support immediately: {{url}}".$sig['en']]],
            'security-login' => ['mandatory' => true, 'vars' => ['jmeno', 'ip', 'zarizeni', 'cas', 'url'], 'cs' => ['subject' => 'Nové přihlášení k účtu', 'body' => "Dobrý den, {{jmeno}},\n\nk vašemu účtu proběhlo přihlášení {{cas}} z adresy {{ip}} ({{zarizeni}}).\n\nPokud jste to nebyli vy, změňte heslo a zkontrolujte dvoufázové ověření: {{url}}".$sig['cs']], 'en' => ['subject' => 'New sign-in to your account', 'body' => "Hello {{jmeno}},\n\nyour account was signed in at {{cas}} from {{ip}} ({{zarizeni}}).\n\nIf this was not you, change your password and review two-factor authentication: {{url}}".$sig['en']]],
            'security-mfa' => ['mandatory' => true, 'vars' => ['jmeno', 'zmena', 'url'], 'cs' => ['subject' => 'Změna dvoufázového ověření', 'body' => "Dobrý den, {{jmeno}},\n\nu vašeho účtu proběhla změna dvoufázového ověření: {{zmena}}.\n\nPokud jste změnu neprovedli, kontaktujte podporu: {{url}}".$sig['cs']], 'en' => ['subject' => 'Two-factor authentication changed', 'body' => "Hello {{jmeno}},\n\ntwo-factor authentication on your account changed: {{zmena}}.\n\nIf you did not make this change, contact support: {{url}}".$sig['en']]],
            'oncall-shift' => ['mandatory' => true, 'vars' => ['jmeno', 'od', 'do'], 'cs' => ['subject' => 'Za hodinu začíná vaše on-call směna', 'body' => "Dobrý den, {{jmeno}},\n\nod {{od}} do {{do}} držíte pager ONhost. Alerty a jejich potvrzení najdete v konzoli správy.".$sig['cs']], 'en' => ['subject' => 'Your on-call shift starts in an hour', 'body' => "Hello {{jmeno}},\n\nfrom {{od}} until {{do}} you carry the ONhost pager. Alerts and their acknowledgement are in the staff console.".$sig['en']]], // §5t-4
            'security-password' => ['mandatory' => true, 'vars' => ['jmeno', 'ip', 'url'], 'cs' => ['subject' => 'Heslo bylo změněno', 'body' => "Dobrý den, {{jmeno}},\n\nheslo k vašemu účtu bylo změněno (z adresy {{ip}}). Všechna ostatní přihlášení a API tokeny byly odhlášeny.\n\nPokud jste heslo neměnili, kontaktujte podporu: {{url}}".$sig['cs']], 'en' => ['subject' => 'Your password was changed', 'body' => "Hello {{jmeno}},\n\nthe password of your account was changed (from {{ip}}). All other sessions and API tokens were signed out.\n\nIf you did not change it, contact support: {{url}}".$sig['en']]],
            'security-locked' => ['mandatory' => true, 'vars' => ['jmeno', 'ip', 'url'], 'cs' => ['subject' => 'Účet byl dočasně uzamčen', 'body' => "Dobrý den, {{jmeno}},\n\npo opakovaných neúspěšných pokusech o přihlášení (z {{ip}}) jsme účet na 15 minut uzamkli.\n\nPokud jste to nebyli vy, doporučujeme obnovit heslo: {{url}}".$sig['cs']], 'en' => ['subject' => 'Your account was temporarily locked', 'body' => "Hello {{jmeno}},\n\nafter repeated failed sign-in attempts (from {{ip}}) the account is locked for 15 minutes.\n\nIf this was not you, reset your password: {{url}}".$sig['en']]],
            'api-token' => ['mandatory' => true, 'vars' => ['jmeno', 'nazev', 'rozsah', 'expirace', 'url'], 'cs' => ['subject' => 'Vytvořen nový API token', 'body' => "Dobrý den, {{jmeno}},\n\nbyl vytvořen API token „{{nazev}}“ s rozsahem {{rozsah}}, platný do {{expirace}}.\n\nTokeny spravujete zde: {{url}}".$sig['cs']], 'en' => ['subject' => 'New API token created', 'body' => "Hello {{jmeno}},\n\nan API token “{{nazev}}” with scope {{rozsah}} was created, valid until {{expirace}}.\n\nManage tokens here: {{url}}".$sig['en']]],
            'incident' => ['mandatory' => true, 'vars' => ['incident', 'nazev', 'stav', 'dopad', 'url'], 'cs' => ['subject' => 'Incident {{incident}} — {{nazev}}', 'body' => "Řešíme incident {{incident}}: {{nazev}}.\n\nStav: {{stav}}\nDopad: {{dopad}}\n\nAktuální informace najdete na stavové stránce: {{url}}".$sig['cs']], 'en' => ['subject' => 'Incident {{incident}} — {{nazev}}', 'body' => "We are handling incident {{incident}}: {{nazev}}.\n\nStatus: {{stav}}\nImpact: {{dopad}}\n\nUpdates are on the status page: {{url}}".$sig['en']]],
            'incident-resolved' => ['mandatory' => true, 'vars' => ['incident', 'nazev', 'trvani', 'url'], 'cs' => ['subject' => 'Incident {{incident}} vyřešen', 'body' => "Incident {{incident}} ({{nazev}}) je vyřešen. Trvání: {{trvani}}.\n\nPost-mortem zveřejníme na stavové stránce: {{url}}".$sig['cs']], 'en' => ['subject' => 'Incident {{incident}} resolved', 'body' => "Incident {{incident}} ({{nazev}}) is resolved. Duration: {{trvani}}.\n\nThe post-mortem will be published on the status page: {{url}}".$sig['en']]],
            'maintenance' => ['mandatory' => true, 'vars' => ['nazev', 'od', 'do', 'dopad', 'url'], 'cs' => ['subject' => 'Plánovaná údržba: {{nazev}}', 'body' => "Plánujeme údržbu „{{nazev}}“ v okně {{od}} – {{do}}.\n\nOčekávaný dopad: {{dopad}}\n\nDetaily a případné změny: {{url}}".$sig['cs']], 'en' => ['subject' => 'Planned maintenance: {{nazev}}', 'body' => "We are planning maintenance “{{nazev}}” in the window {{od}} – {{do}}.\n\nExpected impact: {{dopad}}\n\nDetails and changes: {{url}}".$sig['en']]],
            'sla-credit' => ['vars' => ['castka', 'incident', 'procento', 'url'], 'cs' => ['subject' => 'SLA kredit připsán', 'body' => 'Za incident {{incident}} jsme připsali SLA kredit {{castka}} ({{procento}} % z měsíční ceny dotčených služeb). Opravný doklad je v klientské sekci: {{url}}'.$sig['cs']], 'en' => ['subject' => 'SLA credit issued', 'body' => 'For incident {{incident}} we credited {{castka}} ({{procento}} % of the monthly price of the affected services). The credit note is in the customer panel: {{url}}'.$sig['en']]],
            'payout' => ['vars' => ['castka', 'obdobi', 'url'], 'cs' => ['subject' => 'Provize vyplacena', 'body' => 'Provize za období {{obdobi}} ve výši {{castka}} byla vyplacena. Samofakturační doklad najdete v partnerském portálu: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Commission paid out', 'body' => 'The commission for {{obdobi}} of {{castka}} has been paid. The self-billing document is in the partner portal: {{url}}'.$sig['en']]],
            'tender-docs' => ['vars' => ['jmeno', 'dokumenty', 'url'], 'cs' => ['subject' => 'Podklady pro veřejnou zakázku', 'body' => "Dobrý den, {{jmeno}},\n\nposíláme sadu podkladů pro výběrové řízení:\n{{dokumenty}}\n\nDokumenty ke stažení a případné dotazy: {{url}}".$sig['cs']], 'en' => ['subject' => 'Tender document pack', 'body' => "Hello {{jmeno}},\n\nhere is the document pack for your tender:\n{{dokumenty}}\n\nDownloads and questions: {{url}}".$sig['en']]],
            'data-export' => ['mandatory' => true, 'vars' => ['url', 'dni'], 'cs' => ['subject' => 'Export dat je připraven', 'body' => 'Export vašich dat je připraven ke stažení po dobu {{dni}} dní: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Your data export is ready', 'body' => 'Your data export is ready to download for {{dni}} days: {{url}}'.$sig['en']]],
            'site-down' => ['vars' => ['web', 'chyba', 'url'], 'cs' => ['subject' => 'Web {{web}} neodpovídá', 'body' => "Monitoring hlásí výpadek webu {{web}}.\n\nDetail: {{chyba}}\n\nStav, historii dostupnosti a nastavení kontrol najdete v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Site {{web}} is down', 'body' => "Monitoring reports an outage of {{web}}.\n\nDetail: {{chyba}}\n\nStatus, uptime history and check settings are in the client area: {{url}}".$sig['en']]],
            'service-stopped' => ['vars' => ['sluzba', 'url'], 'cs' => ['subject' => 'Server {{sluzba}} neběží', 'body' => "Server {{sluzba}} je vypnutý, aniž jste ho u nás vypínali.\n\nZapnete ho v klientské sekci: {{url}}\n\nPokud jste ho vypnuli sami zevnitř nebo plánovanou úlohou, nic se neděje. Tato upozornění lze u služby vypnout.".$sig['cs']], 'en' => ['subject' => 'Server {{sluzba}} is not running', 'body' => "Server {{sluzba}} is off although you did not switch it off with us.\n\nStart it in the client area: {{url}}\n\nIf you shut it down from the inside or by a scheduled task, all is well. These alerts can be switched off per service.".$sig['en']]],
            'service-running' => ['vars' => ['sluzba', 'trvani', 'url'], 'cs' => ['subject' => 'Server {{sluzba}} opět běží', 'body' => "Server {{sluzba}} znovu běží. Mimo provoz byl {{trvani}}.\n\nStav služby: {{url}}".$sig['cs']], 'en' => ['subject' => 'Server {{sluzba}} is running again', 'body' => "Server {{sluzba}} runs again. It was down for {{trvani}}.\n\nService status: {{url}}".$sig['en']]],
            'site-up' => ['vars' => ['web', 'trvani', 'url'], 'cs' => ['subject' => 'Web {{web}} opět běží', 'body' => "Web {{web}} znovu odpovídá. Výpadek trval {{trvani}}.\n\nHistorii dostupnosti najdete zde: {{url}}".$sig['cs']], 'en' => ['subject' => 'Site {{web}} is back up', 'body' => "{{web}} answers again. The outage lasted {{trvani}}.\n\nUptime history: {{url}}".$sig['en']]],
            'deploy-failed' => ['vars' => ['ref', 'chyba', 'url'], 'cs' => ['subject' => 'Deploy ({{ref}}) selhal', 'body' => "Nasazení z repozitáře ({{ref}}) se nezdařilo:\n\n{{chyba}}\n\nPředchozí verze zůstává v provozu. Log deploye najdete v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Deployment ({{ref}}) failed', 'body' => "The deployment from your repository ({{ref}}) failed:\n\n{{chyba}}\n\nThe previous release stays live. The deployment log is in the client area: {{url}}".$sig['en']]],
            'import-finished' => ['vars' => ['stav', 'souhrn', 'url'], 'cs' => ['subject' => 'Import webu {{stav}}', 'body' => "Import webu {{stav}}: {{souhrn}}\n\nPodrobnosti a log najdete v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Site import {{stav}}', 'body' => "The site import {{stav}}: {{souhrn}}\n\nDetails and the log are in the client area: {{url}}".$sig['en']]],
            'certificate-failed' => ['vars' => ['domena', 'chyba', 'url'], 'cs' => ['subject' => 'Certifikát pro {{domena}} se nepodařilo vystavit', 'body' => "Vystavení certifikátu pro {{domena}} selhalo:\n\n{{chyba}}\n\nZkontrolujte DNS domény a zkuste to znovu v klientské sekci: {{url}}".$sig['cs']], 'en' => ['subject' => 'Certificate for {{domena}} could not be issued', 'body' => "Issuing the certificate for {{domena}} failed:\n\n{{chyba}}\n\nCheck the domain's DNS and try again in the client area: {{url}}".$sig['en']]],
            'wallet-topup' => ['vars' => ['castka', 'zustatek', 'url'], 'cs' => ['subject' => 'Kredit dobit: {{castka}}', 'body' => "Na váš účet jsme připsali kredit {{castka}}. Aktuální zůstatek je {{zustatek}}.\n\nKredit se čerpá jako první při každé objednávce i obnově. Přehled pohybů: {{url}}".$sig['cs']], 'en' => ['subject' => 'Credit topped up: {{castka}}', 'body' => "We credited {{castka}} to your account. Your balance is now {{zustatek}}.\n\nCredit is used first for every order and renewal. Transactions: {{url}}".$sig['en']]],
            'wallet-runway' => ['vars' => ['dni', 'datum', 'chybi', 'zustatek', 'url'], 'cs' => ['subject' => 'Kredit vystačí ještě {{dni}} dní', 'body' => "Podle naplánovaných obnov vašich služeb vystačí kredit do {{datum}} ({{dni}} dní). Zůstatek je {{zustatek}}, na obnovy v dalších 30 dnech chybí {{chybi}}.\n\nDobijte kredit nebo zapněte automatické dobíjení, aby se žádná služba nepozastavila: {{url}}".$sig['cs']], 'en' => ['subject' => 'Your credit lasts {{dni}} more days', 'body' => "Based on the scheduled renewals of your services, your credit lasts until {{datum}} ({{dni}} days). The balance is {{zustatek}}; renewals in the next 30 days need another {{chybi}}.\n\nTop up or enable automatic top-ups so no service gets suspended: {{url}}".$sig['en']]],
            'payment-received' => ['vars' => ['cislo', 'castka', 'url'], 'cs' => ['subject' => 'Platba přijata: {{cislo}}', 'body' => 'Děkujeme, platbu {{castka}} k dokladu {{cislo}} jsme přijali. Objednané služby se zřizují automaticky a daňový doklad najdete v klientské sekci: {{url}}'.$sig['cs']], 'en' => ['subject' => 'Payment received: {{cislo}}', 'body' => 'Thank you — we received {{castka}} for document {{cislo}}. The ordered services are being provisioned automatically and the tax document is in the client area: {{url}}'.$sig['en']]],
            'legal-notice' => ['mandatory' => true, 'vars' => ['nazev', 'text', 'url'], 'cs' => ['subject' => 'Důležité oznámení: {{nazev}}', 'body' => "{{text}}\n\nÚplné znění: {{url}}".$sig['cs']], 'en' => ['subject' => 'Important notice: {{nazev}}', 'body' => "{{text}}\n\nFull text: {{url}}".$sig['en']]],
        ];
    }
}
