/* ONhost panel — billing seams (docs/ui/data-seams.md #13).
 *
 * The prototype's "Fakturace" tab narrates an invoice card, a cost breakdown and a demo history for a fictional
 * customer. On the API-backed panel this module fills those places from window.ONHOST_PANEL.billing (generated by
 * SurfaceDataController from the organization's documents, subscriptions and legal entity) and wires the actions to
 * the control plane: payment from credit (POST /v1/invoices/{id}/pay), bank-transfer instructions and the PDF
 * download (GET /v1/invoices/{id}/pdf). The surface itself stays byte-identical — SurfaceRenderer only points the
 * prototype's literals at the functions below, and every function returns null when there is no panel data so the
 * demo mode keeps the prototype's own card. */
(function () {
  if (window.OnhostPanelBilling) return; // the prototype runtime executes helmet scripts twice
  var API_BASE = (window.ONHOST && window.ONHOST.apiBase) || '/v1';
  var LABELS = {
    cloud: ['Servery a VPS', 'Servers and VPS'], game: ['Herní servery', 'Game servers'], web: ['Webhosting a aplikace', 'Web hosting and apps'],
    mail: ['E-mail', 'E-mail'], addon: ['Doplňky a zálohy', 'Add-ons and backups'], domain: ['Domény a DNS', 'Domains and DNS'], other: ['Ostatní', 'Other']
  };

  function data() { return (window.ONHOST_PANEL && window.ONHOST_PANEL.billing) || null; }
  function isCs(cmp) { return !cmp || !cmp.state || cmp.state.lang !== 'en'; }
  function tr(cmp) { var cs = isCs(cmp); return function (a, b) { return cs ? a : b; }; }
  function money(cmp, n) { return cmp && typeof cmp.money === 'function' ? cmp.money(n || 0) : String(n || 0); }
  function flash(cmp, title, body) { if (cmp && typeof cmp.flash === 'function') cmp.flash(title, body); }
  function credit(cmp) { return cmp && cmp.state && typeof cmp.state.credit === 'number' ? cmp.state.credit : 0; }
  function openPdf(id) { window.open(API_BASE + '/invoices/' + encodeURIComponent(id) + '/pdf', '_blank', 'noopener'); }
  function typeLabel(cmp, type) {
    var _ = tr(cmp);
    return type === 'proforma' ? _('zálohová faktura', 'proforma invoice') : type === 'credit_note' ? _('opravný doklad', 'credit note') : _('faktura', 'invoice');
  }
  function methodLabel(cmp, m) {
    var _ = tr(cmp);
    var map = { wallet: _('kredit', 'credit'), bank: _('bankovní převod', 'bank transfer'), card: _('karta', 'card'), comgate: _('karta (Comgate)', 'card (Comgate)'), cash: _('hotově', 'cash') };
    return map[m] || m || _('převodem nebo z kreditu', 'bank transfer or credit');
  }
  function plural(cmp, n, key) {
    var cs = isCs(cmp);
    if (key === 'domain') return cs ? n + (n === 1 ? ' doména' : n < 5 ? ' domény' : ' domén') : n + (n === 1 ? ' domain' : ' domains');
    return cs ? n + (n === 1 ? ' služba' : n < 5 ? ' služby' : ' služeb') : n + (n === 1 ? ' service' : ' services');
  }

  function bankBody(cmp, amount, reference, due) {
    var _ = tr(cmp), b = (data() && data().bank) || {};
    var parts = [_('Částka ', 'Amount ') + money(cmp, amount)];
    if (b.account) parts.push(_('účet ', 'account ') + b.account);
    if (b.iban) parts.push('IBAN ' + b.iban + (b.bic ? ' · BIC ' + b.bic : ''));
    if (reference) parts.push(_('variabilní symbol ', 'payment reference ') + reference);
    if (due) parts.push(_('splatnost ', 'due ') + due);
    parts.push(_('Platbu spárujeme automaticky podle variabilního symbolu, obvykle do jednoho pracovního dne.', 'We match the payment automatically by the reference, usually within one business day.'));
    return parts.join(' · ');
  }

  function payFromCredit(cmp, doc) {
    var _ = tr(cmp), A = window.OnhostApi;
    if (!A) return;
    A.post('/invoices/' + doc.id + '/pay', { method: 'wallet' }, A.key()).then(function () {
      flash(cmp, _('Uhrazeno z kreditu · ', 'Paid from credit · ') + doc.number, _('Doklad je zaplacený, potvrzení posíláme na fakturační e-mail. Panel se za okamžik obnoví.', 'The document is paid and the confirmation goes to your billing e-mail. The panel refreshes in a moment.'));
      if (window.OnhostStore && window.OnhostStore.refresh) window.OnhostStore.refresh();
      setTimeout(function () { location.reload(); }, 1500);
    }).catch(function (e) {
      flash(cmp, _('Platba z kreditu neproběhla', 'Credit payment failed'), (e && e.message) || _('Zkuste to prosím znovu, nebo zaplaťte převodem.', 'Please try again or pay by bank transfer.'));
    });
  }

  function notEnoughCredit(cmp, outstanding) {
    var _ = tr(cmp);
    flash(cmp, _('Kredit nestačí', 'Not enough credit'), _('Na účtu je ' + money(cmp, credit(cmp)) + ', doklad je na ' + money(cmp, outstanding) + '. Dobijte kredit v horní liště, nebo zaplaťte převodem.', 'You have ' + money(cmp, credit(cmp)) + ' and the document is ' + money(cmp, outstanding) + '. Top up your credit in the top bar or pay by bank transfer.'));
  }

  function amt(m) { return m && typeof m === 'object' ? parseFloat(m.decimal || 0) : (parseFloat(m) || 0); }

  /* Bank transfer for any open document: the control plane issues (or returns) the transfer with its symbol; the pending list shows it until the money arrives. */
  function payByBank(cmp, doc) {
    var _ = tr(cmp), A = window.OnhostApi;
    if (!A) return;
    A.post('/invoices/' + doc.id + '/pay', { method: 'bank' }, A.key()).then(function (r) {
      var d = r.data || r, ins = d.instructions || {};
      flash(cmp, _('Platba převodem · ', 'Bank transfer · ') + (d.number || doc.number), bankBody(cmp, amt(d.amount) || doc.outstanding || doc.total, ins.variable_symbol || doc.payment_reference || null, doc.due || null));
      if (window.OnhostStore && window.OnhostStore.refresh) window.OnhostStore.refresh();
      setTimeout(function () { location.reload(); }, 4000);
    }).catch(function (e) { flash(cmp, _('Platba převodem · ', 'Bank transfer · ') + doc.number, (e && e.message) || bankBody(cmp, doc.outstanding || doc.total, doc.payment_reference || null, doc.due || null)); });
  }

  /* Card for any open document: the gateway page opens, the panel picks the paid document up on return. */
  function payByCard(cmp, doc) {
    var _ = tr(cmp), A = window.OnhostApi;
    if (!A) return;
    A.post('/invoices/' + doc.id + '/pay', { method: 'card', return_urls: { success: location.origin + '/panel/fakturace', cancel: location.origin + '/panel/fakturace' } }, A.key()).then(function (r) {
      var d = r.data || r;
      if (d.redirect_url) { flash(cmp, _('Přesměrování na platební bránu', 'Redirecting to the payment gateway'), money(cmp, amt(d.amount)) + ' · ' + (d.number || '')); location.href = d.redirect_url; return; }
      flash(cmp, _('Platba kartou', 'Card payment'), _('Platební brána zatím není dostupná; zaplaťte převodem nebo z kreditu.', 'The payment gateway is not available yet; pay by transfer or from credit.'));
    }).catch(function (e) {
      var gateway = e && e.body && (e.body.error === 'payment_provider_error' || e.body.error === 'payment_provider_unavailable');
      flash(cmp, _('Platba kartou neproběhla', 'Card payment failed'), gateway ? _('Platební brána teď není dostupná — zaplaťte převodem (pokyny jsou u dokladu) nebo z kreditu.', 'The payment gateway is not available right now — pay by bank transfer (instructions are on the document) or from credit.') : ((e && e.message) || _('Zkuste to znovu, nebo zaplaťte převodem.', 'Try again, or pay by transfer.')));
    });
  }

  /* TASK-0021 (owner decision 20): credit orders of members who may not spend the credit, waiting for the owner or a billing admin.
   * Shown in the pending-payments card before the transfers; the server refuses a decision to anybody else. */
  function decideOrder(cmp, o, decision) {
    var _ = tr(cmp), A = window.OnhostApi, reason = null;
    if (!A) return;
    if (decision === 'reject') {
      reason = window.prompt(_('Proč objednávku ' + o.number + ' zamítáte? Důvod dostane člen, který ji zadal.', 'Why do you reject order ' + o.number + '? The member who placed it gets the reason.'), '');
      if (!reason || !String(reason).trim()) return;
    } else if (!window.confirm(_('Schválit objednávku ' + o.number + ' za ' + money(cmp, o.total) + '? Částka se uhradí z kreditu a služby se začnou zřizovat.', 'Approve order ' + o.number + ' for ' + money(cmp, o.total) + '? It is paid from credit and the services start.'))) return;
    A.post('/orders/' + encodeURIComponent(o.id) + '/approval', { decision: decision, reason: reason ? String(reason).trim() : undefined }, A.key()).then(function () {
      flash(cmp, decision === 'approve' ? _('Objednávka schválena · ', 'Order approved · ') + o.number : _('Objednávka zamítnuta · ', 'Order rejected · ') + o.number, decision === 'approve' ? _('Uhrazeno z kreditu, služby se zřizují.', 'Paid from credit; the services are being set up.') : _('Nic se z kreditu nečerpalo.', 'No credit was used.'));
      setTimeout(function () { location.reload(); }, 1500);
    }).catch(function (e) { flash(cmp, _('Rozhodnutí se neuložilo', 'Decision not saved'), (e && e.message) || _('Zkuste to prosím znovu.', 'Please try again.')); });
  }

  function approvalsLedger(cmp) {
    var b = data();
    if (!b || !b.approvals || !b.approvals.length) return null;
    var _ = tr(cmp), n = b.approvals.length, cs = isCs(cmp), actions = [], days = b.approval_expire_days || 7;
    b.approvals.slice(0, 3).forEach(function (o) {
      actions.push([_('Schválit ', 'Approve ') + o.number, '', false, function () { decideOrder(cmp, o, 'approve'); }]);
      actions.push([_('Zamítnout ', 'Reject ') + o.number, '', false, function () { decideOrder(cmp, o, 'reject'); }]);
    });
    return {
      real: true,
      title: _('Objednávky čekající na schválení', 'Orders waiting for approval'),
      note: _('placené z kreditu · z kreditu smí platit jen vlastník a fakturační správce', 'paid from credit · only the owner and the billing admin may spend the credit'),
      state: n + ' ' + (cs ? (n === 1 ? 'objednávka' : n < 5 ? 'objednávky' : 'objednávek') : (n === 1 ? 'order' : 'orders')), stateKind: 'warn', actions: actions,
      head: [_('Objednávka', 'Order'), _('Zadal(a)', 'Placed by'), _('Částka', 'Amount'), _('Zadáno', 'Placed')],
      rows: b.approvals.map(function (o) { return [o.number, o.requester || '—', money(cmp, o.total), o.placed || '']; }),
      totals: [[_('Celkem čeká', 'Total waiting'), money(cmp, b.approvals.reduce(function (s, o) { return s + (o.total || 0); }, 0)), true]],
      meta: [[_('Bez rozhodnutí', 'Undecided'), _('zrušíme po ' + days + ' dnech', 'cancelled after ' + days + ' days')]],
      metaNote: _('Dokud objednávku neschválíte, nic se z kreditu nečerpá a nic se nezřizuje. Zamítnutí ji zruší bez poplatku.', 'Until you approve an order no credit is used and nothing is set up. Rejecting it cancels it free of charge.')
    };
  }

  /* "Čekající platby převodem": every transfer the customer still owes, with the symbol and the account, in the ledger shape. */
  function pendingLedger(cmp) {
    var approvals = approvalsLedger(cmp);
    if (approvals) return approvals;
    var b = data();
    if (!b || !b.pending || !b.pending.length) return null;
    var _ = tr(cmp), bank = b.bank || {}, n = b.pending.length, cs = isCs(cmp);
    return {
      real: true,
      title: _('Čekající platby převodem', 'Pending bank transfers'),
      note: _('spárujeme automaticky podle variabilního symbolu · po připsání spustíme, co na platbu čeká', 'matched automatically by the payment reference · whatever waits on the payment starts once it arrives'),
      state: n + ' ' + (cs ? (n === 1 ? 'platba' : n < 5 ? 'platby' : 'plateb') : (n === 1 ? 'payment' : 'payments')), stateKind: 'warn', actions: [],
      head: [_('Účel', 'For'), _('Variabilní symbol', 'Payment reference'), _('Částka', 'Amount'), _('Vytvořeno', 'Created')],
      rows: b.pending.map(function (p) { return [p.for || p.purpose, p.variable_symbol || '—', money(cmp, p.amount) + (p.currency && p.currency !== 'CZK' ? ' ' + p.currency : ''), p.created || '']; }),
      totals: [[_('Celkem čeká', 'Total pending'), money(cmp, b.pending.reduce(function (s, p) { return s + (p.amount || 0); }, 0)), true]],
      meta: [[_('Číslo účtu', 'Account number'), bank.account || '—'], ['IBAN', bank.iban || '—'], ['BIC', bank.bic || '—'], [_('Zpráva pro příjemce', 'Message'), _('číslo dokladu nebo objednávky', 'the document or order number')]],
      metaNote: _('Platbu identifikuje variabilní symbol; pošlete přesnou částku. Převod v rámci ČR obvykle dorazí do druhého pracovního dne, kartou je to ihned.', 'The payment reference identifies the payment; send the exact amount. Domestic transfers usually arrive by the next business day; cards are instant.')
    };
  }

  /* The invoice card of the Fakturace tab, in the prototype's ledger shape (title/note/state/actions/head/rows/totals/meta). */
  function ledger(cmp) {
    var b = data();
    if (!b) return null;
    var _ = tr(cmp), d = b.document, org = b.organization || {};
    var head = [_('Položka', 'Item'), _('Počet', 'Qty'), _('Jedn. cena', 'Unit'), _('Celkem', 'Amount')];
    if (!d) {
      return {
        real: true,
        title: _('Zatím žádný doklad', 'No document yet'),
        note: _('první doklad vystavíme s první objednávkou nebo obnovou', 'the first document is issued with your first order or renewal'),
        state: _('nic k úhradě', 'nothing due'), stateKind: 'ok', actions: [], head: head, rows: [],
        totals: [[_('K úhradě', 'Due'), money(cmp, 0), true]],
        meta: [
          [_('Odběratel', 'Customer'), org.name || '—'],
          [org.vat_id ? 'DIČ' : 'IČO', org.vat_id || org.ico || '—'],
          [_('Fakturační e-mail', 'Billing e-mail'), org.billing_email || '—'],
          [_('Způsob platby', 'Payment method'), _('kredit, karta nebo převod', 'credit, card or bank transfer')]
        ],
        metaNote: _('Doklady vystavujeme s každou objednávkou a obnovou: zálohovou fakturu před zahájením služby a daňový doklad po připsání platby, obojí i jako PDF a ISDOC.', 'Documents are issued with every order and renewal: a proforma before the service starts and a tax document once the payment arrives, both also as PDF and ISDOC.')
      };
    }
    var open = d.state === 'due' || d.state === 'overdue';
    var stateLabel = { due: _('k úhradě', 'due'), overdue: _('po splatnosti', 'overdue'), paid: _('zaplaceno', 'paid'), credited: _('dobropisováno', 'credited'), cancelled: _('stornováno', 'voided') }[d.state] || d.state;
    var stateKind = d.state === 'overdue' ? 'acc' : open ? 'warn' : d.state === 'paid' ? 'ok' : 'off';
    var actions = [];
    if (open) {
      var c = credit(cmp), covered = d.outstanding > 0 && c >= d.outstanding;
      actions.push([
        _('Uhradit z kreditu', 'Pay from credit'),
        covered ? _('Kredit ' + money(cmp, c) + ' doklad pokryje; zaplatíme ho okamžitě.', 'Your ' + money(cmp, c) + ' credit covers it; it is paid at once.') : _('Kredit ' + money(cmp, c) + ' nestačí.', 'Your ' + money(cmp, c) + ' credit is not enough.'),
        covered,
        covered ? function () { payFromCredit(cmp, d); } : function () { notEnoughCredit(cmp, d.outstanding); }
      ]);
      actions.push([_('Bankovní převod', 'Bank transfer'), '', !covered, function () { payByBank(cmp, d); }]);
      actions.push([_('Platební karta', 'Payment card'), '', false, function () { payByCard(cmp, d); }]);
    }
    actions.push([_('Stáhnout PDF', 'Download PDF'), '', !open, function () { openPdf(d.id); }]);

    var rows = (d.lines || []).map(function (l) { return [l.name, l.sub, l.qty, money(cmp, l.unit), money(cmp, l.total)]; });
    var totals = [[_('Základ bez DPH', 'Subtotal excl. VAT'), money(cmp, d.subtotal)]];
    if (d.discount > 0) totals.push([_('Sleva', 'Discount'), '− ' + money(cmp, d.discount)]);
    totals.push([_('DPH', 'VAT') + (d.tax_rates && d.tax_rates.length ? ' ' + d.tax_rates.join(' / ') + ' %' : ''), money(cmp, d.tax)]);
    if (open && d.paid_amount > 0) totals.push([_('Již uhrazeno', 'Already paid'), '− ' + money(cmp, d.paid_amount)]);
    totals.push([
      open ? (d.due ? _('K úhradě do ', 'Due by ') + d.due : _('K úhradě', 'Due')) : d.state === 'paid' ? (d.paid ? _('Uhrazeno ', 'Paid ') + d.paid : _('Uhrazeno', 'Paid')) : _('Celkem', 'Total'),
      money(cmp, open ? d.outstanding : d.total), true
    ]);

    var meta = [[_('Číslo dokladu', 'Document number'), d.number], [_('Typ', 'Type'), typeLabel(cmp, d.type)]];
    if (d.payment_reference) meta.push([_('Variabilní symbol', 'Payment reference'), d.payment_reference]);
    if (d.due) meta.push([_('Splatnost', 'Due date'), d.due]);
    meta.push([_('Způsob platby', 'Payment method'), methodLabel(cmp, d.payment_method)]);
    meta.push([_('Odběratel', 'Customer'), (d.buyer && d.buyer.name) || org.name || '—']);
    if (d.buyer && (d.buyer.vat_id || d.buyer.ico)) meta.push([d.buyer.vat_id ? 'DIČ' : 'IČO', d.buyer.vat_id || d.buyer.ico]);
    if (d.previous) meta.push([_('Předchozí doklad', 'Previous document'), d.previous.number + ' · ' + (d.previous.state === 'paid' ? (d.previous.paid ? _('uhrazen ', 'paid ') + d.previous.paid : _('uhrazen', 'paid')) : _('neuhrazen', 'unpaid'))]);

    var kind = typeLabel(cmp, d.type);
    return {
      real: true,
      title: kind.charAt(0).toUpperCase() + kind.slice(1) + ' ' + d.number,
      note: (d.period ? _('období ', 'period ') + d.period + ' · ' : '') + (d.issued ? _('vystaveno ', 'issued ') + d.issued : ''),
      state: stateLabel, stateKind: stateKind, actions: actions, head: head, rows: rows, totals: totals, meta: meta,
      metaNote: d.type === 'proforma'
        ? _('Zálohovou fakturu vystavujeme před zahájením služby. Po připsání platby pošleme daňový doklad — PDF i ISDOC — na fakturační e-mail.', 'A proforma is issued before the service starts. Once the payment arrives we send the tax document — PDF and ISDOC — to your billing e-mail.')
        : _('Daňový doklad je k dispozici jako PDF i ISDOC; obojí najdete také v příloze e-mailu s fakturou.', 'The tax document is available as PDF and ISDOC; both are also attached to the invoice e-mail.')
    };
  }

  /* "Rozpad nákladů" side panel: monthly spend per service group from the organization's active subscriptions. */
  function breakdown(cmp) {
    var b = data();
    if (!b) return null;
    var _ = tr(cmp), rows = b.breakdown || [];
    if (!rows.length) return [{ title: _('Zatím žádné předplatné', 'No subscriptions yet'), meta: _('rozpad nákladů se objeví s první aktivní službou', 'the cost breakdown appears with your first active service'), value: money(cmp, 0), kind: 'off' }];
    return rows.map(function (r) {
      var l = LABELS[r.key] || LABELS.other;
      return { title: _(l[0], l[1]), meta: plural(cmp, r.count, r.key) + _(' · měsíčně', ' · per month'), value: money(cmp, r.amount), kind: 'ok' };
    });
  }

  /* Row button of the invoice history (store-backed rows): "Zaplatit" for open documents, "PDF" for the rest. */
  function rowAction(cmp, i, unpaid) {
    var _ = tr(cmp), id = i.apiId || i.id;
    if (!unpaid) { openPdf(id); return; }
    if (i.total > 0 && credit(cmp) >= i.total) { payFromCredit(cmp, { id: id, number: i.id }); return; }
    var A = window.OnhostApi;
    (A ? A.get('/invoices/' + id) : Promise.reject(new Error('api'))).then(function (r) {
      var v = r.data || r;
      flash(cmp, _('Platba převodem · ', 'Bank transfer · ') + i.id, bankBody(cmp, i.total, v.payment_reference, v.due_at ? new Date(v.due_at).toLocaleDateString(isCs(cmp) ? 'cs-CZ' : 'en-GB') : null));
    }).catch(function () {
      flash(cmp, _('Platba převodem · ', 'Bank transfer · ') + i.id, bankBody(cmp, i.total, null, null));
    });
  }

  /* "Dobít kredit": a payment intent for the wallet (POST /v1/payments/init). Card payments go to the gateway and come
   * back to /panel/fakturace; bank transfers get their instructions in a flash. Credit is booked by the control plane
   * when the payment settles, so nothing is promised here that the ledger has not seen. */
  function topUp(cmp, amount, method) {
    var _ = tr(cmp), A = window.OnhostApi;
    if (!A) return;
    amount = Number(amount);
    if (!(amount > 0)) { flash(cmp, _('Zadejte částku', 'Enter an amount'), _('Vyberte nebo zadejte částku, kterou chcete připsat.', 'Pick or enter the amount to add.')); return; }
    var currency = (window.ONHOST_PANEL && window.ONHOST_PANEL.kpis && window.ONHOST_PANEL.kpis.currency) || 'CZK';
    var body = { amount: amount, currency: currency, method: method === 'bank' ? null : (method || 'card') };
    if (method === 'bank') body.provider = 'bank';
    // stored cards (audit §5f-1): a card top-up may keep the card for automatic top-ups; asked once, only when none is stored yet
    var b0 = data(), at0 = b0 && b0.wallet ? b0.wallet.auto_topup : null, stored = (b0 && b0.wallet && b0.wallet.payment_methods) || [];
    if (method !== 'bank' && at0 && at0.supported && !stored.length) body.save_method = window.confirm(_('Uložit kartu pro automatické dobití kreditu? Kartu nikdy nevidíme — platební brána nám dá jen token; kdykoli ji odeberete ve Fakturaci.', 'Keep the card for automatic top-ups? We never see the card — the gateway gives us a token; remove it any time in Billing.'));
    A.post('/payments/init', body, A.key()).then(function (r) {
      var d = r.data || r;
      if (d.redirect_url) {
        flash(cmp, _('Přesměrování na platební bránu', 'Redirecting to the payment gateway'), money(cmp, amount) + ' · ' + _('po zaplacení se vrátíte zpět do panelu a kredit bude připsaný', 'after paying you return to the panel with the credit added'));
        location.href = d.redirect_url;
        return;
      }
      var ins = d.instructions || {};
      if (d.provider === 'bank' || ins.variable_symbol || ins.reference) {
        flash(cmp, _('Dobití převodem · ', 'Top-up by bank transfer · ') + money(cmp, amount), bankBody(cmp, amount, ins.variable_symbol || ins.reference || null, null));
        return;
      }
      flash(cmp, _('Platba připravena', 'Payment prepared'), _('Kredit připíšeme, jakmile platba dorazí.', 'The credit is added as soon as the payment arrives.'));
    }).catch(function (e) {
      flash(cmp, _('Dobití kreditu se nepodařilo', 'Top-up failed'), (e && e.message) || _('Zkuste to prosím znovu.', 'Please try again.'));
    });
  }

  /* The billing tab's widget strip: the invoice-structure donut becomes the split of the current subscriptions, the
   * "most expensive services" ranking keeps the real servers (scaled to the dearest one), and the two narrated
   * daily-spend / forecast line charts are dropped — there is no metered daily spend to plot. */
  function widgets(cmp, list) {
    var b = data();
    if (!b) return list;
    var _ = tr(cmp);
    return (list || []).filter(function (w) { return w.kind !== 'line'; }).map(function (w) {
      w.real = true; // survives the "narrated blocks" filter of the API-backed panel
      if (w.kind === 'donut') {
        var colors = (w.items || []).map(function (i) { return i[3]; });
        var rows = b.breakdown || [], total = rows.reduce(function (s, r) { return s + r.amount; }, 0);
        w.title = _('Měsíční předplatné', 'Monthly subscriptions');
        w.value = money(cmp, b.monthly); w.center = money(cmp, b.monthly); w.sub = _('bez DPH · měsíčně', 'excl. VAT · per month');
        w.items = rows.map(function (r, i) { var l = LABELS[r.key] || LABELS.other; return [_(l[0], l[1]), money(cmp, r.amount), total ? Math.round(r.amount / total * 100) : 0, colors[i % Math.max(1, colors.length)]]; });
        w.note = _('Kredit se čerpá dřív než platební karta. Nevyčerpaný kredit nepropadá.', 'Credit is drawn before your card. Unused credit never expires.');
      }
      if (w.kind === 'rank') {
        var servers = ((cmp && cmp.state && cmp.state.servers) || []).slice().sort(function (a, c) { return (c.price || 0) - (a.price || 0); }).slice(0, 5);
        var top = servers.length ? Math.max(1, servers[0].price || 0) : 1;
        var palette = (w.items || []).map(function (i) { return i[3]; });
        w.items = servers.map(function (x, i) { return [x.name, money(cmp, x.price || 0), Math.round((x.price || 0) / top * 100), palette[i] || palette[palette.length - 1] || 'currentColor']; });
        w.value = servers.length + ' ' + (isCs(cmp) ? (servers.length === 1 ? 'server' : servers.length < 5 ? 'servery' : 'serverů') : (servers.length === 1 ? 'server' : 'servers'));
        w.note = servers.length ? _('Seřazeno podle měsíční ceny běžících serverů. Změnu konfigurace uděláte za provozu v sekci Servery.', 'Sorted by the monthly price of your running servers. Resize them live in the Servers section.') : _('Zatím žádné servery.', 'No servers yet.');
      }
      return w;
    });
  }

  /* "Čerpání rozpočtu" rows: the invoiced split from the chart legend as [label, '44 %', 44]. */
  function usageRows(cmp) {
    var b = data();
    if (!b || !b.chart) return null;
    return b.chart.legend.map(function (l) { return [l[0], l[1], parseInt(l[1], 10) || 0]; });
  }

  /* "Co se stane, když nezaplatíte": the real dunning ladder from the control plane's configuration. */
  function policyLedger(cmp) {
    var b = data();
    if (!b || !b.dunning) return null;
    var _ = tr(cmp), dn = b.dunning, due = (b.terms && b.terms.due_days) || 14;
    var notices = (dn.overdue_notice_days || []).join(', ');
    // automatic top-up (audit §5e-2): the wallet's policy row and its switch; charging needs a provider that keeps payment methods
    var at = (b.wallet && b.wallet.auto_topup) || null;
    var atRow = at ? [_('Automatické dobití', 'Automatic top-up'), at.enabled ? _('při nedostatku kreditu před obnovou dobijeme ' + money(cmp, at.amount && at.amount.decimal ? Number(at.amount.decimal) : 0) + (at.supported ? '' : ' · zatím jen upozornění, uložená platební metoda není k dispozici'), 'when credit runs short before a renewal we add ' + money(cmp, at.amount && at.amount.decimal ? Number(at.amount.decimal) : 0) + (at.supported ? '' : ' · notice only until a stored payment method is available')) : _('vypnuto · týden před obnovou vás upozorníme, kolik chybí', 'off · a week before a renewal you are told what is missing'), _('7 dní před obnovou', '7 days before a renewal'), '', at.enabled ? _('vypnout v nastavení peněženky', 'switch off in the wallet settings') : _('zapnout v nastavení peněženky', 'switch on in the wallet settings')] : null;
    // stored cards (audit §5f-1): what the automatic top-up charges; removable any time
    var cards = (b.wallet && b.wallet.payment_methods) || [];
    var cardRow = at ? [_('Uložená karta', 'Stored card'), cards.length ? cards.map(function (c) { return (c.brand ? c.brand + ' ' : _('karta ', 'card ')) + '•••• ' + (c.last4 || '') + (c.is_default ? _(' · výchozí', ' · default') : ''); }).join(', ') : _('žádná · při příštím dobití kartou ji můžete uložit pro automatické dobití', 'none · keep the card at the next card top-up for automatic top-ups'), cards.length ? _('kdykoli odebrat', 'remove any time') : '', '', cards.length ? _('odebrat ve fakturaci', 'remove in billing') : _('dobít kartou a uložit', 'top up by card and keep it')] : null;
    var cardActions = cards.length ? cards.map(function (c) { return [_('Odebrat kartu •••• ' + (c.last4 || ''), 'Remove card •••• ' + (c.last4 || '')), '', false, function () {
      var A = window.OnhostApi;
      if (!A || !window.confirm(_('Odebrat uloženou kartu •••• ' + (c.last4 || '') + '? Automatické dobití pak jen upozorní.', 'Remove the stored card •••• ' + (c.last4 || '') + '? Automatic top-ups will only notify afterwards.'))) return;
      A.del('/payment-methods/' + encodeURIComponent(c.id)).then(function () { flash(cmp, _('Karta odebrána', 'Card removed'), ''); if (window.OnhostStore && window.OnhostStore.refresh) window.OnhostStore.refresh(); if (cmp && cmp.forceUpdate) cmp.forceUpdate(); }).catch(function (e) { flash(cmp, _('Kartu se nepodařilo odebrat', 'Card not removed'), (e && e.message) || ''); });
    }]; }) : [];
    var atActions = at ? [[at.enabled ? _('Vypnout automatické dobití', 'Turn automatic top-up off') : _('Zapnout automatické dobití', 'Turn automatic top-up on'), '', false, function () {
      var next = !at.enabled, A = window.OnhostApi;
      if (!A) return;
      if (next && !window.confirm(_('Když kredit nepokryje obnovy příštího týdne, dobijeme ho automaticky z uložené platební metody (do měsíčního limitu). Bez uložené metody vás jen upozorníme. Pokračovat?', 'When credit does not cover next week\'s renewals it is topped up from the stored payment method (up to the monthly limit). Without one you are only told. Continue?'))) return;
      A.put('/wallet/auto-topup', { enabled: next }).then(function () { flash(cmp, _('Nastavení uloženo', 'Setting saved'), next ? _('Automatické dobití je zapnuté.', 'Automatic top-up is on.') : _('Automatické dobití je vypnuté.', 'Automatic top-up is off.')); if (window.OnhostStore && window.OnhostStore.refresh) window.OnhostStore.refresh(); if (cmp && cmp.forceUpdate) cmp.forceUpdate(); }).catch(function (e) { flash(cmp, _('Nastavení se neuložilo', 'Setting not saved'), (e && e.message) || ''); });
    }]] : [];
    return {
      real: true,
      title: _('Co se stane, když nezaplatíte', 'What happens if you do not pay'),
      note: _('lhůty platné pro váš účet · nic z toho nespouštíme bez upozornění', 'the deadlines that apply to your account · nothing runs without a notice'),
      state: _('bez pokut', 'no penalties'), stateKind: 'ok', actions: atActions.concat(cardActions),
      head: [_('Krok', 'Step'), _('Kdy', 'When'), '', _('Co můžete udělat', 'What you can do')],
      rows: (atRow ? [atRow] : []).concat(cardRow ? [cardRow] : []).concat([
        [_('Splatnost dokladu', 'Document due'), _('faktura nebo zálohová faktura k úhradě', 'invoice or proforma to pay'), _(due + ' dní od vystavení', due + ' days from issue'), '', _('kredit, karta, převod', 'credit, card, transfer')],
        [_('Upomínky', 'Reminders'), _('e-mail a upozornění v panelu, žádné poplatky', 'e-mail and a panel notice, no fees'), _(notices + ' dní po splatnosti', notices + ' days after due'), '', _('zaplatit nebo napsat podpoře', 'pay or write to support')],
        [_('Pozastavení služeb', 'Suspension'), _('data zůstávají, po úhradě obnovíme do minut', 'data stays; restored within minutes after payment'), _(dn.suspend_after_days + ' dní po splatnosti', dn.suspend_after_days + ' days after due'), '', _('uhradit doklad', 'settle the document')],
        [_('Ukončení služeb', 'Termination'), _('služby končí, doména zůstává vaše do expirace', 'services end; a domain stays yours until it expires'), _(dn.terminate_after_days + ' dní po splatnosti', dn.terminate_after_days + ' days after due'), '', _('export dat v panelu', 'export your data in the panel')],
        [_('Smazání dat', 'Data deletion'), _('nenávratné, po uplynutí ochranné lhůty', 'irreversible, after the retention period'), _(dn.retention_after_termination_days + ' dní po ukončení', dn.retention_after_termination_days + ' days after termination'), '', _('do té doby lze vše obnovit', 'everything can be restored until then')]
      ]),
      totals: [],
      meta: [[_('Splatnost', 'Due'), due + ' ' + _('dní', 'days')], [_('Upomínky', 'Reminders'), notices + ' ' + _('dní', 'days')], [_('Pozastavení', 'Suspension'), dn.suspend_after_days + ' ' + _('dní', 'days')], [_('Ukončení', 'Termination'), dn.terminate_after_days + ' ' + _('dní', 'days')], [_('Ochranná lhůta dat', 'Data retention'), dn.retention_after_termination_days + ' ' + _('dní', 'days')]],
      metaNote: _('Lhůty počítáme automaticky z data splatnosti; každý krok předchází upozornění na fakturační e-mail a do panelu.', 'Deadlines count from the due date; every step is preceded by a notice to your billing e-mail and the panel.')
    };
  }

  window.OnhostPanelBilling = { ledger: ledger, breakdown: breakdown, rowAction: rowAction, topUp: topUp, payByBank: payByBank, payByCard: payByCard, pendingLedger: pendingLedger, approvalsLedger: approvalsLedger, widgets: widgets, usageRows: usageRows, policyLedger: policyLedger, data: data };
})();
