<?php

declare(strict_types=1);

namespace Onhost\Providers\Penpot;

/**
 * The files one Penpot stack is made of on its node (TASK-0123): `docker-compose.yaml`, its `.env` and the reverse-proxy site.
 *
 * The services, environment variable names and values follow the official self-host compose file
 * (github.com/penpot/penpot docker/images/docker-compose.yaml, help.penpot.app/technical-guide/getting-started/docker): frontend,
 * backend, exporter, PostgreSQL 15 and Valkey. Left out on purpose: the mail catcher (a development aid), the admin console and
 * the MCP server (optional, not sold). Every secret lives in `.env` (mode 0600), never in the compose file, never in a command line.
 *
 * Images are pinned by digest (`config('penpot.images')`, written into `.env`). Every container runs with `no-new-privileges`,
 * a pid limit and `cap_drop: ALL` (security review of PR #119, M2). The Penpot images run as the user `penpot` (`USER penpot:penpot`
 * in docker/images/Dockerfile.{frontend,backend,exporter}) and get no capability back; the official PostgreSQL and Valkey images
 * start as root, chown their data directory and switch to their own user (gosu / setpriv), so they keep exactly the capabilities
 * that takes (CAP_ADD) — docs/runbooks/penpot.md, to be confirmed on the first test node.
 */
final class PenpotCompose
{
    public const SERVICES = ['penpot-frontend', 'penpot-backend', 'penpot-exporter', 'penpot-postgres', 'penpot-valkey'];

    /** `.env` variable of each service's pinned image. */
    public const IMAGE_VARS = ['frontend' => 'PENPOT_FRONTEND_IMAGE', 'backend' => 'PENPOT_BACKEND_IMAGE', 'exporter' => 'PENPOT_EXPORTER_IMAGE', 'postgres' => 'ONHOST_POSTGRES_IMAGE', 'valkey' => 'ONHOST_VALKEY_IMAGE'];

    /** Capabilities a service gets back after `cap_drop: ALL` (only the images that switch users at start). */
    public const CAP_ADD = [
        'penpot-postgres' => ['CHOWN', 'DAC_OVERRIDE', 'FOWNER', 'SETGID', 'SETUID'], // docker-entrypoint.sh: chown/chmod of PGDATA, then gosu postgres
        'penpot-valkey' => ['CHOWN', 'SETGID', 'SETUID'], // docker-entrypoint.sh: chown of /data, then setpriv to the valkey user
    ];

    /** Processes per container (the JVM of the backend and the browser of the exporter need the most). */
    public const PIDS = ['penpot-frontend' => 256, 'penpot-backend' => 1024, 'penpot-exporter' => 1024, 'penpot-postgres' => 256, 'penpot-valkey' => 64];

    /** Share of the stack's memory per container, in percent (Valkey has its own fixed cap). */
    private const MEMORY_SHARE = ['penpot-backend' => 45, 'penpot-exporter' => 25, 'penpot-postgres' => 20, 'penpot-frontend' => 10];

    private const VALKEY_MB = 256;

    /**
     * @param  array{ram_mb:int, cpus:int|float}  $limits
     */
    public static function compose(string $project, array $limits): string
    {
        $ram = max(1024, (int) $limits['ram_mb']) - self::VALKEY_MB;
        $cpus = self::cpus(max(0.5, (float) $limits['cpus']));
        $harden = function (string $service, ?int $memoryMb = null) use ($ram, $cpus): string {
            $out = '    security_opt:'."\n".'      - no-new-privileges:true'."\n".'    cap_drop:'."\n".'      - ALL'."\n";
            if (isset(self::CAP_ADD[$service])) {
                $out .= '    cap_add:'."\n".implode('', array_map(fn (string $cap) => '      - '.$cap."\n", self::CAP_ADD[$service]));
            }
            $memory = $memoryMb ?? intdiv($ram * self::MEMORY_SHARE[$service], 100);

            return $out.'    pids_limit: '.self::PIDS[$service]."\n".'    deploy:'."\n".'      resources:'."\n".'        limits:'."\n"
                .'          memory: '.$memory.'m'."\n".'          cpus: "'.$cpus.'"'."\n";
        };

        return <<<YAML
# Managed by ONhost (TASK-0123). Regenerated by the platform; manual edits are overwritten.
name: {$project}

networks:
  penpot:

volumes:
  penpot_postgres_v15:
  penpot_assets:

services:
  penpot-frontend:
    image: "\${PENPOT_FRONTEND_IMAGE}"
    restart: always
    ports:
      - "127.0.0.1:\${ONHOST_PORT}:8080"
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    environment:
      PENPOT_FLAGS: \${PENPOT_FLAGS}
      PENPOT_PUBLIC_URI: \${PENPOT_PUBLIC_URI}
      PENPOT_HTTP_SERVER_MAX_BODY_SIZE: \${PENPOT_HTTP_SERVER_MAX_BODY_SIZE}
{$harden('penpot-frontend')}
  penpot-backend:
    image: "\${PENPOT_BACKEND_IMAGE}"
    restart: always
    volumes:
      - penpot_assets:/opt/data/assets
    depends_on:
      penpot-postgres:
        condition: service_healthy
      penpot-valkey:
        condition: service_healthy
    networks:
      - penpot
    env_file:
      - .env.smtp
    environment:
      PENPOT_FLAGS: \${PENPOT_FLAGS}
      PENPOT_PUBLIC_URI: \${PENPOT_PUBLIC_URI}
      PENPOT_HTTP_SERVER_MAX_BODY_SIZE: \${PENPOT_HTTP_SERVER_MAX_BODY_SIZE}
      PENPOT_HTTP_SERVER_MAX_MULTIPART_BODY_SIZE: \${PENPOT_HTTP_SERVER_MAX_BODY_SIZE}
      PENPOT_SECRET_KEY: \${PENPOT_SECRET_KEY}
      PENPOT_DATABASE_URI: postgresql://penpot-postgres/penpot
      PENPOT_DATABASE_USERNAME: penpot
      PENPOT_DATABASE_PASSWORD: \${PENPOT_DATABASE_PASSWORD}
      PENPOT_REDIS_URI: redis://penpot-valkey/0
      PENPOT_OBJECTS_STORAGE_BACKEND: fs
      PENPOT_OBJECTS_STORAGE_FS_DIRECTORY: /opt/data/assets
      PENPOT_TELEMETRY_ENABLED: "false"
{$harden('penpot-backend')}
  penpot-exporter:
    image: "\${PENPOT_EXPORTER_IMAGE}"
    restart: always
    depends_on:
      penpot-valkey:
        condition: service_healthy
    networks:
      - penpot
    environment:
      PENPOT_FLAGS: \${PENPOT_FLAGS}
      PENPOT_SECRET_KEY: \${PENPOT_SECRET_KEY}
      PENPOT_PUBLIC_URI: \${PENPOT_PUBLIC_URI}
      PENPOT_INTERNAL_URI: http://penpot-frontend:8080
      PENPOT_REDIS_URI: redis://penpot-valkey/0
{$harden('penpot-exporter')}
  penpot-postgres:
    image: "\${ONHOST_POSTGRES_IMAGE}"
    restart: always
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penpot"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s
    volumes:
      - penpot_postgres_v15:/var/lib/postgresql/data
    networks:
      - penpot
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_DB: penpot
      POSTGRES_USER: penpot
      POSTGRES_PASSWORD: \${PENPOT_DATABASE_PASSWORD}
{$harden('penpot-postgres')}
  penpot-valkey:
    image: "\${ONHOST_VALKEY_IMAGE}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 3s
    networks:
      - penpot
    environment:
      VALKEY_EXTRA_FLAGS: "--maxmemory \${ONHOST_VALKEY_MAXMEMORY} --maxmemory-policy volatile-lfu"
{$harden('penpot-valkey', self::VALKEY_MB)}
YAML;
    }

    /**
     * The `.env` of the stack: what compose interpolates. Secrets are plain values here and nowhere else on the node.
     *
     * @param  array{images:array<string,string>, port:int, public_uri:string, flags:list<string>, secret_key:string, db_password:string, valkey_maxmemory:string, max_body_size:int}  $values
     */
    public static function env(array $values): string
    {
        $lines = ['# Managed by ONhost (TASK-0123). Mode 0600. Regenerated by the platform from its secret vault.'];
        foreach (self::IMAGE_VARS as $name => $var) {
            $lines[] = $var.'='.self::value((string) ($values['images'][$name] ?? ''));
        }
        array_push($lines,
            'ONHOST_PORT='.(int) $values['port'],
            'ONHOST_VALKEY_MAXMEMORY='.self::value($values['valkey_maxmemory']),
            'PENPOT_PUBLIC_URI='.self::value($values['public_uri']),
            'PENPOT_FLAGS='.self::value(implode(' ', $values['flags'])),
            'PENPOT_HTTP_SERVER_MAX_BODY_SIZE='.(int) $values['max_body_size'],
            'PENPOT_SECRET_KEY='.self::value($values['secret_key']),
            'PENPOT_DATABASE_PASSWORD='.self::value($values['db_password']),
        );

        return implode("\n", $lines)."\n";
    }

    /**
     * SMTP of the node for the backend (`.env.smtp`, an `env_file`): empty without one. Variable names from the official compose
     * file; the values are the operator's (`smtp` instance option + `smtp_password` credential).
     *
     * @param  array<string,mixed>  $smtp
     */
    public static function smtpEnv(array $smtp, ?string $password): string
    {
        if (trim((string) ($smtp['host'] ?? '')) === '') {
            return "# no SMTP on this node (docs/runbooks/penpot.md)\n";
        }
        $lines = [
            'PENPOT_SMTP_DEFAULT_FROM='.self::value((string) ($smtp['from'] ?? '')),
            'PENPOT_SMTP_DEFAULT_REPLY_TO='.self::value((string) ($smtp['reply_to'] ?? ($smtp['from'] ?? ''))),
            'PENPOT_SMTP_HOST='.self::value((string) $smtp['host']),
            'PENPOT_SMTP_PORT='.(int) ($smtp['port'] ?? 587),
            'PENPOT_SMTP_USERNAME='.self::value((string) ($smtp['username'] ?? '')),
            'PENPOT_SMTP_PASSWORD='.self::value((string) ($password ?? '')),
            'PENPOT_SMTP_TLS='.(($smtp['tls'] ?? true) ? 'true' : 'false'),
            'PENPOT_SMTP_SSL='.(($smtp['ssl'] ?? false) ? 'true' : 'false'),
        ];

        return implode("\n", $lines)."\n";
    }

    /** The reverse-proxy site of one stack (Caddy: automatic HTTPS once the host name resolves to the node). */
    public static function proxySite(string $serviceId, string $hostname, int $port, int $maxBodyBytes): string
    {
        $mb = max(1, intdiv($maxBodyBytes, 1048576));

        return "# Managed by ONhost (TASK-0123), service {$serviceId}. Regenerated by the platform.\n"
            ."{$hostname} {\n\trequest_body {\n\t\tmax_size {$mb}MB\n\t}\n\treverse_proxy 127.0.0.1:{$port}\n}\n";
    }

    /** One value of a dotenv line: quoted when it holds anything but safe characters. */
    private static function value(string $value): string
    {
        if (preg_match('/^[A-Za-z0-9_.:\/@+=,-]*$/', $value) === 1) {
            return $value;
        }

        return '"'.str_replace(['\\', '"', '$', "\n"], ['\\\\', '\\"', '\\$', ''], $value).'"';
    }

    private static function cpus(float $cpus): string
    {
        return rtrim(rtrim(number_format($cpus, 2, '.', ''), '0'), '.');
    }
}
