<?php

declare(strict_types=1);

use App\Domains\Shared\Support\XlsxWriter;
use Database\Seeders\IntegrationSeeder;
use Database\Seeders\MockServerSeeder;
use Database\Seeders\ProductCatalogSeeder;

/**
 * Native XLSX export (audit D63) — built on PHP's bundled ZipArchive so the
 * project needs no spreadsheet dependency.
 *
 * These tests actually unzip the output and inspect the parts: a file that
 * merely downloads but that Excel refuses to open would be worse than no
 * export at all.
 */
beforeEach(function (): void {
    $this->seed([ProductCatalogSeeder::class, MockServerSeeder::class, IntegrationSeeder::class]);
});

/** Unzip generated bytes into [entryName => contents]. */
function unzipXlsx(string $binary): array
{
    $path = tempnam(sys_get_temp_dir(), 'xlsxtest');
    file_put_contents($path, $binary);

    $zip = new ZipArchive();
    expect($zip->open($path))->toBeTrue();

    $parts = [];
    for ($i = 0; $i < $zip->numFiles; $i++) {
        $name         = (string) $zip->getNameIndex($i);
        $parts[$name] = (string) $zip->getFromIndex($i);
    }

    $zip->close();
    @unlink($path);

    return $parts;
}

// ── The writer ────────────────────────────────────────────────────────────────

it('produces a readable zip with every part Excel requires', function (): void {
    $parts = unzipXlsx(XlsxWriter::build(['A'], [['x']]));

    expect($parts)->toHaveKeys([
        '[Content_Types].xml',
        '_rels/.rels',
        'xl/workbook.xml',
        'xl/_rels/workbook.xml.rels',
        'xl/styles.xml',
        'xl/worksheets/sheet1.xml',
    ]);
});

it('writes well-formed XML in every part', function (): void {
    $parts = unzipXlsx(XlsxWriter::build(['Číslo', 'Částka'], [['CZ-2026-000001', 1234.56]]));

    foreach ($parts as $name => $xml) {
        expect(simplexml_load_string($xml))->not->toBeFalse("Part {$name} is not valid XML");
    }
});

it('writes the header and the data rows', function (): void {
    $parts = unzipXlsx(XlsxWriter::build(['Číslo faktury', 'Celkem'], [['CZ-2026-000001', 500.0]]));
    $sheet = $parts['xl/worksheets/sheet1.xml'];

    expect($sheet)->toContain('Číslo faktury')
        ->and($sheet)->toContain('CZ-2026-000001')
        ->and($sheet)->toContain('<v>500</v>');
});

it('keeps numbers numeric and identifiers textual', function (): void {
    // Invoice numbers and IČO must not be coerced into scientific notation,
    // and amounts must stay summable.
    $sheet = unzipXlsx(XlsxWriter::build(['ID', 'Částka'], [['00123456', 99.5]]))['xl/worksheets/sheet1.xml'];

    expect($sheet)->toContain('<t xml:space="preserve">00123456</t>')
        ->and($sheet)->toContain('<v>99.5</v>');
});

it('escapes characters that would break the XML', function (): void {
    $sheet = unzipXlsx(XlsxWriter::build(['X'], [['Kolář & syn <s.r.o.>']]))['xl/worksheets/sheet1.xml'];

    expect(simplexml_load_string($sheet))->not->toBeFalse()
        ->and($sheet)->toContain('&amp;')
        ->and($sheet)->not->toContain('<s.r.o.>');
});

it('strips control characters that make Excel reject the file', function (): void {
    $sheet = unzipXlsx(XlsxWriter::build(['X'], [["bad\x00\x07value"]]))['xl/worksheets/sheet1.xml'];

    expect(simplexml_load_string($sheet))->not->toBeFalse()
        ->and($sheet)->toContain('badvalue');
});

it('addresses columns beyond Z correctly', function (): void {
    $headers = array_map(static fn (int $i): string => "H{$i}", range(1, 28));
    $sheet   = unzipXlsx(XlsxWriter::build($headers, []))['xl/worksheets/sheet1.xml'];

    // 27th column is AA, 28th is AB.
    expect($sheet)->toContain('r="Z1"')
        ->and($sheet)->toContain('r="AA1"')
        ->and($sheet)->toContain('r="AB1"');
});

it('sanitises a sheet name Excel would reject', function (): void {
    $workbook = unzipXlsx(XlsxWriter::build(['A'], [], 'Faktury/2026:Q1'))['xl/workbook.xml'];

    // Check the name attribute itself — the document is full of legitimate
    // slashes and colons in its namespace URLs.
    preg_match('/<sheet name="([^"]*)"/', $workbook, $matches);
    $sheetName = $matches[1] ?? '';

    expect($sheetName)->toBe('Faktury2026Q1')
        ->and(simplexml_load_string($workbook))->not->toBeFalse();
});

it('handles an empty result set', function (): void {
    $parts = unzipXlsx(XlsxWriter::build(['Číslo'], []));

    expect(simplexml_load_string($parts['xl/worksheets/sheet1.xml']))->not->toBeFalse();
});

// ── The admin export endpoint ─────────────────────────────────────────────────

it('serves the invoice export as a real xlsx file', function (): void {
    placeOrder(customerUser());

    $response = $this->actingAs(adminUser())
        ->get(route('admin.invoices.export', ['format' => 'xlsx']));

    $response->assertOk()
        ->assertHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

    // XLSX is returned as a plain (non-streamed) response.
    $parts = unzipXlsx((string) $response->getContent());

    expect($parts)->toHaveKey('xl/worksheets/sheet1.xml')
        ->and($parts['xl/worksheets/sheet1.xml'])->toContain('Číslo faktury');
});

it('still serves CSV when no format is requested', function (): void {
    placeOrder(customerUser());

    $this->actingAs(adminUser())
        ->get(route('admin.invoices.export'))
        ->assertOk()
        ->assertHeader('Content-Type', 'text/csv; charset=UTF-8');
});

it('forbids a customer from exporting invoices', function (): void {
    $this->actingAs(customerUser())
        ->get(route('admin.invoices.export', ['format' => 'xlsx']))
        ->assertForbidden();
});
