[program:onhost-scheduler]
process_name=%(program_name)s
command=php /var/www/clients/client10/web19/web/artisan schedule:work
autostart=true
autorestart=true
user=web19
redirect_stderr=true
stdout_logfile=/var/www/clients/client10/web19/log/scheduler.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=2
