[program:onhost-horizon]
process_name=%(program_name)s
command=php /var/www/clients/client10/web19/web/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=web19
redirect_stderr=true
stdout_logfile=/var/www/clients/client10/web19/log/horizon.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=3600
