[program:onhost-reverb]
process_name=%(program_name)s
command=php /var/www/clients/client10/web19/web/artisan reverb:start --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=web19
redirect_stderr=true
stdout_logfile=/var/www/clients/client10/web19/log/reverb.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=2
