#!/usr/bin/env bash
# ONhost control plane — the gated release on the aaPanel host (docs/runbooks/release-and-rollback.md, TASK-0032).
#
# Installed root-owned as /usr/local/sbin/onhost-deploy by install-deployer.sh (never run from the site tree: the
# target revision must not bring its own judge). Run as root:
#
#   REF=<tag|sha> EXPECTED_SHA=<40-hex sha> DEPLOY_OPERATOR=<name> /usr/local/sbin/onhost-deploy
#
# Stages: preflight → drain → down → backup + verify → switch + build → ownership → gate → start → up → public check
# → record. Nothing changes before the drain; the site is down (503) only from `down` to `up`. The gate judges the
# target's `onhost:doctor --json` by row name (deploy-gate.php: HARD rows never pass, GATED rows only with a logged,
# SHA-bound ALLOW_DOCTOR_FAIL outside production or an `Accept-Gate:` line in the signed tag) and asks the site
# itself for /up and /v1/status through the maintenance bypass. Before 2026-09-27 the doctor ran after the restarts
# as `onhost:doctor || true` and could stop nothing (onboarding audit C12/C14).
#
# Exit codes: 0 released · 2 preflight refused (nothing changed) · 3 drain, backup or verify failed (nothing switched,
# units started again, site up again when this run took it down) · 4 build failed after the switch · 5 gate failed ·
# 6 the public /up check failed after `up`. After 4 and 5 the site stays in maintenance and the drained units stay
# stopped; the script prints the recovery command (last good release) — there is no automatic rollback.
set -euo pipefail

SITE="${SITE:-staging.onhost.cz}"
APP_DIR="${APP_DIR:-/www/wwwroot/${SITE}}"
PHP="${PHP:-/www/server/php/83/bin/php}"
COMPOSER="${COMPOSER:-/usr/local/bin/composer}"
RUN_USER="${RUN_USER:-www}"
DEPLOY_STATE_DIR="${DEPLOY_STATE_DIR:-/var/lib/onhost-deploy/${SITE}}"
DEPLOY_LIB_DIR="${DEPLOY_LIB_DIR:-/usr/local/lib/onhost-deploy}"
PHP_FPM_RELOAD="${PHP_FPM_RELOAD:-}"            # e.g. '/etc/init.d/php-fpm-83 reload' (opcache would keep serving old code)
DEPLOY_HTTP_IP="${DEPLOY_HTTP_IP:-127.0.0.1}"   # where nginx answers https://$SITE on this host (the vhost lets loopback past basic auth)
DEPLOY_HTTP_BASE="${DEPLOY_HTTP_BASE:-}"        # tests only: a plain base URL (php -S) instead of https://$SITE via --resolve
DRAIN_TIMEOUT="${DRAIN_TIMEOUT:-300}"
DEPLOY_OWNER_UID="${DEPLOY_OWNER_UID:-0}"       # who must own .git and allowed_signers (root; tests run unprivileged)
DEPLOY_HOME="${DEPLOY_HOME:-/root}"
DEPLOY_SAFE_PATH="${DEPLOY_SAFE_PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}"
OPENAPI_PATH="contracts/openapi/onhost-v1.yaml"  # regenerated by every build (onhost:openapi): the one tracked file allowed to differ

STAGE=preflight
SWITCHED=0
PROD=1
SHA=""
TAG=""
FROM=""
SET=""
OVERRIDE=""
OVERRIDE_REASON=""
SKIP_REASON=""
DRAINED_NOW=""
PREV_DRAINED=""
WAS_DOWN=0
MARKER_BY_THIS_RUN=0
WENT_DOWN=0
DRAIN_S=""
DOWN_AT=""
WINDOW_S=""
ACCEPTED=""
RUN_DIR=""
JAR=""
APP_ENV_VALUE=""
DEPLOY_LOG="${DEPLOY_STATE_DIR}/deploy.log"
MARKER="${DEPLOY_STATE_DIR}/down-by-deploy"
DRAINED_FILE="${DEPLOY_STATE_DIR}/drained-units"

say() { printf '\n\033[1;32m▶ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARN %s\033[0m\n' "$*" >&2; }
die() { local rc=$1; shift; printf '\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit "$rc"; }

# git without anything the (www-writable) tree could inject: no system config, a root-owned global config that only
# names this checkout safe, no hooks, no fsmonitor
g() { GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL="${DEPLOY_STATE_DIR}/gitconfig" git -C "$APP_DIR" -c core.hooksPath=/dev/null -c core.fsmonitor=false "$@"; }
# the target's PHP code runs with a clean, fixed environment (as root — aaPanel kills sudo -u www; ownership is repaired)
art() { env -i PATH="$DEPLOY_SAFE_PATH" HOME="$DEPLOY_HOME" "$PHP" "$APP_DIR/artisan" "$@"; }
art_pg() { env -i PATH="$DEPLOY_SAFE_PATH" HOME="$DEPLOY_HOME" PGOPTIONS='-c lock_timeout=10s' "$PHP" "$APP_DIR/artisan" "$@"; }
comp() { env -i PATH="$DEPLOY_SAFE_PATH" HOME="$DEPLOY_HOME" COMPOSER_HOME="${COMPOSER_HOME:-$DEPLOY_HOME/.composer}" COMPOSER_ALLOW_SUPERUSER=1 "$PHP" "$COMPOSER" "$@"; }
gate() { "$PHP" "$DEPLOY_LIB_DIR/deploy-gate.php" "$@"; }
utc_now() { date -u +%Y%m%d-%H%M%S; }
ver_ge() { [ "$(printf '%s\n%s\n' "$2" "$1" | sort -V | head -n1)" = "$2" ]; }
oneline() { printf '%s' "$*" | tr '\n\r"' '   '; }

log_line() {
  local rc=$1
  [ -d "$DEPLOY_STATE_DIR" ] || return 0
  (umask 077; printf '%s site=%s operator=%s logname=%s from=%s to=%s ref=%s stage=%s rc=%s set=%s drain_s=%s window_s=%s skip_backup="%s" override="%s" accepted="%s" run=%s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SITE" "$(oneline "${DEPLOY_OPERATOR:-?}")" "$(logname 2>/dev/null || echo "${SUDO_USER:-?}")" \
    "${FROM:-?}" "${SHA:-?}" "$(oneline "${REF:-?}")" "$STAGE" "$rc" "${SET:--}" "${DRAIN_S:--}" "${WINDOW_S:--}" \
    "$(oneline "$SKIP_REASON")" "$(oneline "$OVERRIDE_REASON")" "$(oneline "$ACCEPTED")" "${RUN_DIR:--}" >> "$DEPLOY_LOG") || true
}

# ── units ───────────────────────────────────────────────────────────────────────────────────────────────────────────
active_units() { systemctl list-units --plain --no-legend --state=active,activating,reloading 'onhost-queue@*' 'onhost-scheduler.service' | awk '{print $1}' | sort -u; }

start_units() { # $@ = unit names
  local u
  for u in "$@"; do systemctl start "$u" || warn "could not start $u (systemctl status $u)"; done
}

restore_drained_list() { # a failed run leaves the list as it found it (units a previous failed run stopped stay stopped)
  if [ -n "$PREV_DRAINED" ]; then printf '%s\n' "$PREV_DRAINED" > "$DRAINED_FILE"; else rm -f "$DRAINED_FILE"; fi
}

# ── ownership: storage and bootstrap/cache belong to the PHP-FPM user; the rest of the tree is not chowned ──────────
repair_ownership() {
  chown -R "$RUN_USER:$RUN_USER" "$APP_DIR/storage" "$APP_DIR/bootstrap/cache"
  chmod -R u+rwX,g+rX,o-rwx "$APP_DIR/storage" "$APP_DIR/bootstrap/cache"
}
ownership_ok() { [ -z "$(find "$APP_DIR/storage" "$APP_DIR/bootstrap/cache" ! -user "$RUN_USER" -print -quit 2>/dev/null)" ]; }

# ── HTTP: https://$SITE on this host (--resolve), optionally with the maintenance bypass header ─────────────────────
http_status() { # $1 = path, $2 = "bypass" to send the cookie
  local args=(-sS -o /dev/null -w '%{http_code}' --max-time 30) url
  if [ "${2:-}" = bypass ]; then args+=(-K "$JAR"); fi
  if [ -n "$DEPLOY_HTTP_BASE" ]; then url="${DEPLOY_HTTP_BASE%/}$1"; else args+=(--resolve "${SITE}:443:${DEPLOY_HTTP_IP}"); url="https://${SITE}$1"; fi
  curl "${args[@]}" "$url" 2>/dev/null || true
}

recovery_hint() {
  say "Recovery (the site stays in maintenance; the drained units stay stopped)"
  gate hint --file "$DEPLOY_STATE_DIR/last-good.json" --production "$PROD" || true
  echo "backup set of this run: ${SET:-none} (checksums: ${RUN_DIR:-?}/backup.out)"
  echo "a database restore needs the owner: docs/runbooks/release-and-rollback.md § Rollback"
}

on_exit() {
  local rc=$?
  set +e
  trap - EXIT
  if [ "$STAGE" != preflight ]; then repair_ownership 2>/dev/null; fi
  [ -n "$JAR" ] && rm -f "$JAR"
  if [ "$rc" -ne 0 ] && [ "$STAGE" != preflight ]; then
    if [ "$SWITCHED" = 0 ]; then
      if [ "$MARKER_BY_THIS_RUN" = 1 ]; then
        art up >/dev/null 2>&1 && rm -f "$MARKER"
      elif [ "$WENT_DOWN" = 1 ]; then
        art down --retry=60 >/dev/null 2>&1   # the site was down before this run: keep it down, drop this run's bypass secret
      fi
      # shellcheck disable=SC2086 # unit names are plain words
      start_units $DRAINED_NOW
      restore_drained_list
    elif [ "$rc" -ne 6 ]; then
      art down --retry=60 >/dev/null 2>&1       # new payload without a secret: the bypass dies with the failed run
      recovery_hint
    else
      recovery_hint
    fi
  fi
  log_line "$rc"
  exit "$rc"
}
trap on_exit EXIT

# ── 0 preflight: every refusal here is exit 2 and nothing has changed ───────────────────────────────────────────────
[ -n "${BRANCH:-}" ] && die 2 "BRANCH is no longer accepted: pass REF=<tag|sha> and EXPECTED_SHA=<sha>"
[ -n "${REF:-}" ] || die 2 "REF is required (a tag, or outside production a SHA or branch)"
[[ "$REF" =~ ^[A-Za-z0-9][A-Za-z0-9._/-]{0,127}$ ]] && [[ "$REF" != *..* ]] && [[ "$REF" != *.lock ]] || die 2 "REF '$REF' is not a plain ref name"
[[ "${EXPECTED_SHA:-}" =~ ^[0-9a-f]{40}$ ]] || die 2 "EXPECTED_SHA must be the full 40-character SHA of the release"
[[ "${DEPLOY_OPERATOR:-}" =~ ^[A-Za-z0-9._@-]{2,64}$ ]] || die 2 "DEPLOY_OPERATOR (who runs this release) is required"
self="$(realpath "$0" 2>/dev/null || echo "$0")"
case "$self" in "$(realpath "$APP_DIR" 2>/dev/null || echo "$APP_DIR")"/*) die 2 "run the installed deployer (/usr/local/sbin/onhost-deploy), not the copy in the site tree";; esac
[ -f "$DEPLOY_LIB_DIR/deploy-gate.php" ] || die 2 "the deployer is not installed ($DEPLOY_LIB_DIR/deploy-gate.php): infra/aapanel/install-deployer.sh"
for tool in git curl flock find sort; do command -v "$tool" >/dev/null 2>&1 || die 2 "missing: $tool"; done
[ -x "$PHP" ] || die 2 "PHP not found at $PHP"
[ -d "$APP_DIR/.git" ] || die 2 "$APP_DIR is not a checkout"
cd "$APP_DIR" || die 2 "cannot enter $APP_DIR"

(umask 077; mkdir -p "$DEPLOY_STATE_DIR/runs") && chmod 700 "$DEPLOY_STATE_DIR" || die 2 "cannot create $DEPLOY_STATE_DIR"
exec 9>"$DEPLOY_STATE_DIR/lock"
flock -n 9 || die 2 "another deploy of $SITE is running"
[ -f "$DEPLOY_STATE_DIR/gitconfig" ] || (umask 077; printf '[safe]\n\tdirectory = %s\n' "$APP_DIR" > "$DEPLOY_STATE_DIR/gitconfig")

git_version="$(git --version | awk '{print $3}')"
ver_ge "$git_version" 2.32 || die 2 "git $git_version is too old (2.32+ for GIT_CONFIG_GLOBAL)"

APP_ENV_VALUE="$(gate parse-env --file "$APP_DIR/.env" --key APP_ENV || true)"
case "$APP_ENV_VALUE" in staging|local|testing) PROD=0 ;; *) PROD=1 ;; esac   # fail closed: anything unclear is production
[ "$PROD" = 1 ] && { ver_ge "$git_version" 2.34 || die 2 "production needs git 2.34+ (SSH-signed tags)"; }
app_url="$(gate parse-env --file "$APP_DIR/.env" --key APP_URL || true)"
app_host="${app_url#*://}"; app_host="${app_host%%/*}"; app_host="${app_host%%:*}"
[ "$app_host" = "$SITE" ] || die 2 "APP_URL host '$app_host' in $APP_DIR/.env is not SITE '$SITE'"

[ -z "$(find "$APP_DIR/.git" \( ! -uid "$DEPLOY_OWNER_UID" -o -perm /022 \) -print -quit)" ] \
  || die 2 ".git must belong to uid $DEPLOY_OWNER_UID and be writable by nobody else (chown -R root:root .git && chmod -R go-w .git)"

FROM="$(g rev-parse HEAD)" || die 2 "cannot read HEAD of $APP_DIR"
DEPLOYER_SHA="$(cat "$DEPLOY_LIB_DIR/source-sha" 2>/dev/null || true)"
[[ "$DEPLOYER_SHA" =~ ^[0-9a-f]{40}$ ]] || die 2 "the deployer has no source-sha: install it with install-deployer.sh"

say "Fetch and resolve $REF"
g fetch -q --prune --prune-tags --force --tags origin || die 2 "git fetch failed"
if [[ "$REF" =~ ^[0-9a-f]{7,40}$ ]] && SHA="$(g rev-parse -q --verify "${REF}^{commit}" 2>/dev/null)"; then
  kind=sha
elif g rev-parse -q --verify "refs/tags/${REF}" >/dev/null; then
  kind=tag; TAG="$REF"; SHA="$(g rev-parse "refs/tags/${REF}^{commit}")"
elif [ "$PROD" = 0 ] && g rev-parse -q --verify "refs/remotes/origin/${REF}" >/dev/null; then
  kind=branch; SHA="$(g rev-parse "refs/remotes/origin/${REF}^{commit}")"
else
  die 2 "REF '$REF' does not resolve (production: a tag only)"
fi
[ "$SHA" = "$EXPECTED_SHA" ] || die 2 "REF '$REF' is $SHA, not EXPECTED_SHA $EXPECTED_SHA"
RUN_DIR="$DEPLOY_STATE_DIR/runs/$(utc_now)-${SHA:0:12}"
(umask 077; mkdir -p "$RUN_DIR")

if [ "$PROD" = 1 ]; then
  [ "$kind" = tag ] || die 2 "production deploys only a signed, annotated tag (REF=v…)"
  [ "$(g cat-file -t "refs/tags/${REF}")" = tag ] || die 2 "tag $REF is lightweight: production needs an annotated, signed tag"
  signers="$DEPLOY_STATE_DIR/allowed_signers"
  [ -f "$signers" ] && [ -z "$(find "$signers" \( ! -uid "$DEPLOY_OWNER_UID" -o -perm /022 \) -print -quit)" ] \
    || die 2 "no trusted $signers (root-owned, the owner's SSH public key): production deploys are refused until it exists"
  g -c gpg.format=ssh -c gpg.ssh.allowedSignersFile="$signers" verify-tag "$REF" >/dev/null 2>&1 || die 2 "tag $REF is not signed by a key in $signers"
  g cat-file tag "refs/tags/${REF}" > "$RUN_DIR/tag.txt"
  [ -n "${ALLOW_DOCTOR_FAIL:-}" ] && die 2 "ALLOW_DOCTOR_FAIL is refused in production: accept a GATED row with an 'Accept-Gate: <area|check> — <reason>' line in the signed tag"
fi

if g merge-base --is-ancestor "$DEPLOYER_SHA" "$SHA" 2>/dev/null \
  && ! g diff --quiet "$DEPLOYER_SHA" "$SHA" -- infra/aapanel/deploy.sh infra/aapanel/deploy-gate.php; then
  die 2 "the target carries a newer deployer than the installed one ($DEPLOYER_SHA): first run
  g show $SHA:infra/aapanel/install-deployer.sh > /root/install-deployer.sh && SHA=$SHA bash /root/install-deployer.sh"
fi
g cat-file -e "${DEPLOYER_SHA}^{commit}" 2>/dev/null || die 2 "the installed deployer's source $DEPLOYER_SHA is not in this repository"

dirty="$(g status --porcelain --untracked-files=all -- . ":(exclude)${OPENAPI_PATH}" ':(exclude)VERSION')"
[ -z "$dirty" ] || die 2 "the checkout is not clean (a deploy would discard or ship this):
$dirty"

HAS_MIGRATIONS=0
[ -n "$(g diff --name-only "$FROM" "$SHA" -- database/migrations)" ] && HAS_MIGRATIONS=1
if [ -n "${SKIP_BACKUP:-}" ] && [ "${SKIP_BACKUP}" != 0 ]; then
  SKIP_REASON="$(gate override --value "$SKIP_BACKUP" --sha "$SHA")" || die 2 "SKIP_BACKUP must be \"${SHA:0:12}:<reason>\""
  [ "$HAS_MIGRATIONS" = 0 ] || die 2 "SKIP_BACKUP is refused: $FROM..$SHA changes database/migrations"
fi
if [ -n "${ALLOW_DOCTOR_FAIL:-}" ]; then
  OVERRIDE_REASON="$(gate override --value "$ALLOW_DOCTOR_FAIL" --sha "$SHA")" || die 2 "ALLOW_DOCTOR_FAIL must be \"${SHA:0:12}:<reason>\""
  OVERRIDE="$ALLOW_DOCTOR_FAIL"
fi
unset ALLOW_DOCTOR_FAIL SKIP_BACKUP

probe="$(http_status /up)"
case "$probe" in
  401|403) die 2 "https://$SITE/up answers $probe on $DEPLOY_HTTP_IP: the vhost must let loopback past basic auth (the staging block of infra/aapanel/nginx-site.conf)" ;;
  000) die 2 "nothing answers https://$SITE on $DEPLOY_HTTP_IP (DEPLOY_HTTP_IP)" ;;
esac
[ -f "$APP_DIR/storage/framework/down" ] && WAS_DOWN=1
PREV_DRAINED="$(cat "$DRAINED_FILE" 2>/dev/null || true)"
RUN_START="$(utc_now)"
say "Release $FROM → $SHA ($kind $REF, $( [ "$PROD" = 1 ] && echo production || echo "$APP_ENV_VALUE"), operator $DEPLOY_OPERATOR)"
[ -n "$OVERRIDE_REASON" ] && warn "ALLOW_DOCTOR_FAIL accepted for GATED rows only: $OVERRIDE_REASON"

# ── 1 drain: nothing of the old code keeps running jobs while the tree changes under it ────────────────────────────
STAGE=drain
say "Drain the queue workers and the scheduler (up to ${DRAIN_TIMEOUT}s)"
DRAINED_NOW="$(active_units | tr '\n' ' ')" || die 3 "cannot list the onhost units (systemctl)"
# shellcheck disable=SC2086 # unit names are plain words
printf '%s\n%s\n' "$PREV_DRAINED" "$(printf '%s\n' $DRAINED_NOW)" | sed '/^$/d' | sort -u > "$DRAINED_FILE"
drain_started=$SECONDS
if [ -n "${DRAINED_NOW// /}" ]; then
  # shellcheck disable=SC2086
  systemctl stop --no-block $DRAINED_NOW
  while :; do
    still=""
    for u in $DRAINED_NOW; do systemctl is-active --quiet "$u" && still="$still $u"; done
    [ -z "$still" ] && break
    [ $((SECONDS - drain_started)) -ge "$DRAIN_TIMEOUT" ] && die 3 "still running after ${DRAIN_TIMEOUT}s:$still (a long job; retry later or raise DRAIN_TIMEOUT)"
    sleep 2
  done
fi
DRAIN_S=$((SECONDS - drain_started))

# ── 2 down: 503 for visitors; the gate passes with a bypass cookie built from the down file's secret ──────────────
STAGE=down
say "Maintenance mode"
art down --retry=60 --with-secret >/dev/null || die 3 "artisan down failed"   # the bypass URL it prints must never reach a terminal log
WENT_DOWN=1
DOWN_AT=$SECONDS
if [ "$WAS_DOWN" = 0 ] && [ ! -f "$MARKER" ]; then : > "$MARKER"; MARKER_BY_THIS_RUN=1; fi
[ -f "$APP_DIR/storage/framework/down" ] || die 3 "artisan down wrote no storage/framework/down (APP_MAINTENANCE_DRIVER must be file)"

# ── 3 backup + verify inside the window: the set this run wrote, read back ─────────────────────────────────────────
STAGE=backup
if [ -n "$SKIP_REASON" ]; then
  warn "backup skipped (no migrations in range): $SKIP_REASON"
else
  say "Platform backup and verification"
  (umask 077; : > "$RUN_DIR/backup.out")
  art onhost:platform:backup --no-ansi >> "$RUN_DIR/backup.out" 2>&1 || { cat "$RUN_DIR/backup.out"; die 3 "the platform backup failed"; }
  SET="$(gate backup-set --output "$RUN_DIR/backup.out" --since "$RUN_START")" || { cat "$RUN_DIR/backup.out"; die 3 "no fresh backup set from this run (is the platform.backup rule switched off?)"; }
  art onhost:platform:backup:verify "$SET" --no-ansi >> "$RUN_DIR/backup.out" 2>&1 || { cat "$RUN_DIR/backup.out"; die 3 "backup set $SET did not verify"; }
  grep -qE "^OK ${SET}( |$)" "$RUN_DIR/backup.out" || die 3 "verify did not confirm $SET"
  echo "   $SET verified (checksums kept in $RUN_DIR/backup.out)"
fi

# ── 4 switch + build ────────────────────────────────────────────────────────────────────────────────────────────────
STAGE=switch
say "Code $SHA"
SWITCHED=1
g checkout -q -f --detach "$SHA" || die 4 "checkout failed"
[ "$(g rev-parse HEAD)" = "$SHA" ] && g diff --quiet HEAD \
  && [ -z "$(g status --porcelain --untracked-files=all -- . ':(exclude)VERSION')" ] || die 4 "the tree is not clean after the checkout"

STAGE=build
rm -f bootstrap/cache/config.php bootstrap/cache/routes-v7.php bootstrap/cache/events.php bootstrap/cache/packages.php bootstrap/cache/services.php
say "Composer"
comp install --no-dev --no-interaction --prefer-dist --no-progress --optimize-autoloader || die 4 "composer install failed"
say "Migrations (additive, backward compatible for one release; lock_timeout 10s, no retry)"
art_pg migrate --force --isolated || die 4 "migrations failed"
art db:seed --class=AuthorizationSeeder --force || die 4 "AuthorizationSeeder failed"   # roles and permissions are code; the authorizer reads the database
art db:seed --class=NotificationTemplateSeeder --force || die 4 "NotificationTemplateSeeder failed"
say "Caches and contract"
art config:cache && art route:cache && art event:cache || die 4 "caching failed"
art onhost:openapi > "$RUN_DIR/openapi.out" 2>&1 || warn "onhost:openapi failed ($RUN_DIR/openapi.out); the published contract may be stale"
(umask 022; printf '%s %s\n' "$SHA" "$REF" > "$APP_DIR/VERSION") || die 4 "cannot write VERSION"
repair_ownership || die 4 "ownership repair failed"
if [ -n "$PHP_FPM_RELOAD" ]; then sh -c "$PHP_FPM_RELOAD" || warn "PHP-FPM reload failed: opcache may serve the old code"; else warn "PHP_FPM_RELOAD is not set: opcache may serve the old code"; fi

# ── 5 gate ──────────────────────────────────────────────────────────────────────────────────────────────────────────
STAGE=gate
say "Gate: ownership, doctor, HTTP"
ownership_ok || die 5 "storage or bootstrap/cache still has files not owned by $RUN_USER"
doctor_rc=0
art onhost:doctor --json > "$RUN_DIR/report.json" 2> "$RUN_DIR/doctor.err" || doctor_rc=$?
verdict_rc=0
gate verdict --report "$RUN_DIR/report.json" --doctor-rc "$doctor_rc" --env "$APP_ENV_VALUE" --production "$PROD" --sha "$SHA" \
  --override "$OVERRIDE" --accept-file "$RUN_DIR/tag.txt" > "$RUN_DIR/verdict.out" || verdict_rc=$?
cat "$RUN_DIR/verdict.out"
ACCEPTED="$(grep '^ACCEPTED ' "$RUN_DIR/verdict.out" | sed 's/^ACCEPTED //' | tr '\n' ';' || true)"
case "$verdict_rc" in
  0) ;;
  10) die 5 "a GATED doctor row is not OK (staging: ALLOW_DOCTOR_FAIL=\"${SHA:0:12}:<reason>\"; production: Accept-Gate in the signed tag)" ;;
  *) die 5 "a HARD doctor row is not OK, or the doctor report cannot be trusted (never overridable)" ;;
esac
JAR="$RUN_DIR/bypass.curlrc"
gate cookie --down-file "$APP_DIR/storage/framework/down" --out "$JAR" --ttl 900 || die 5 "cannot build the maintenance bypass"
for path in /up /v1/status; do
  code="$(http_status "$path" bypass)"
  [ "$code" = 200 ] || die 5 "GET $path answered $code through the maintenance bypass (not overridable)"
  echo "   GET $path → 200"
done
rm -f "$JAR"; JAR=""

# ── 6 live ──────────────────────────────────────────────────────────────────────────────────────────────────────────
STAGE=live
repair_ownership || die 5 "ownership repair failed"
ownership_ok || die 5 "storage or bootstrap/cache has files not owned by $RUN_USER"
if [ -f "$DEPLOY_STATE_DIR/expect-freeze" ] && [ "$PROD" = 0 ]; then
  art onhost:provisioning:freeze "staging: expected freeze" >/dev/null || die 5 "could not re-assert the expected provisioning freeze"
  echo "   provisioning freeze re-asserted (expect-freeze)"
fi
say "Start the drained units"
# shellcheck disable=SC2046
start_units $(cat "$DRAINED_FILE" 2>/dev/null)
rm -f "$DRAINED_FILE"
if [ -f "$MARKER" ]; then
  art up >/dev/null || die 6 "artisan up failed"
  rm -f "$MARKER"
  WINDOW_S=$((SECONDS - DOWN_AT))
  say "Live (maintenance window ${WINDOW_S}s)"
  code="$(http_status /up)"
  [ "$code" = 200 ] || die 6 "public GET /up answers $code after up"
else
  art down --retry=60 >/dev/null   # drop this run's bypass secret
  say "The site was down before this deploy; left down (artisan up when you are ready)"
fi

# ── 7 record ────────────────────────────────────────────────────────────────────────────────────────────────────────
STAGE=done
(umask 077; printf '{"sha":"%s","ref":"%s","tag":"%s","at":"%s","operator":"%s"}\n' "$SHA" "$REF" "$TAG" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(oneline "$DEPLOY_OPERATOR")" > "$DEPLOY_STATE_DIR/last-good.json")
say "Released $SHA. Run onhost:doctor again after 6 minutes or more for the liveness rows (scheduler, worker)."
