<?php

declare(strict_types=1);

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use App\Http\Support\CatalogPresentation;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Cache;
use Onhost\Domain\Billing\Models\Subscription;
use Onhost\Domain\Catalog\CatalogService;
use Onhost\Domain\Catalog\Models\PlanVersion;
use Onhost\Domain\Catalog\Models\Product;
use Onhost\Domain\Catalog\PanelNavigation;
use Onhost\Domain\Catalog\PricingRules;
use Onhost\Domain\Content\ContentService;
use Onhost\Domain\Domains\Models\Domain;
use Onhost\Domain\Incidents\IncidentService;
use Onhost\Domain\Invoicing\Models\Invoice;
use Onhost\Domain\Invoicing\Models\LegalEntity;
use Onhost\Domain\Orders\Models\ConsentDocument;
use Onhost\Domain\Orders\Models\Order;
use Onhost\Domain\Organizations\Models\Organization;
use Onhost\Domain\Organizations\Models\OrganizationMembership;
use Onhost\Domain\Payments\Models\PaymentIntent;
use Onhost\Domain\Payments\Models\PaymentStateMachineStates as PaymentState;
use Onhost\Domain\Payments\PaymentService;
use Onhost\Domain\Provisioning\GameConfigurator;
use Onhost\Domain\Provisioning\GameTemplates;
use Onhost\Domain\Provisioning\Models\Region;
use Onhost\Domain\Provisioning\PlacementService;
use Onhost\Domain\Provisioning\ProviderRegistry;
use Onhost\Domain\Provisioning\ServiceMigrationService;
use Onhost\Domain\Services\AvailabilityWatch;
use Onhost\Domain\Services\ControlPlaneStatus;
use Onhost\Domain\Services\Models\Service;
use Onhost\Domain\Services\Models\ServiceStateMachine;
use Onhost\Domain\Services\ServiceFreshness;
use Onhost\Domain\Services\SuspensionHold;
use Onhost\Domain\Services\UsageWatch;
use Onhost\Domain\Support\Models\Ticket;
use Onhost\Domain\WalletLedger\AutoTopup;
use Onhost\Domain\WalletLedger\WalletService;
use Onhost\Platform\Errors\DomainError;
use Onhost\Platform\Money\Money;

/**
 * Server-generated data scripts for the surfaces (template-inventory §6.4–6.5):
 *  - /surfaces/onhost-data.js  → `window.ONHOST_DATA` with the exact functions/shapes of the prototype file
 *    (`catalog(cs)`, `plans(cs)`, `compare(cs)`, `status(cs)`, `locations(cs)`, `changelog(cs)`), built from the catalog,
 *    the status page and public content;
 *  - /surfaces/onhost-panel.js → `window.ONHOST_PANEL` with the signed-in organization's services and servers
 *    in the shapes `SVC_DATA().services` / `state.servers` expect.
 */
final class SurfaceDataController extends Controller
{
    private const CATEGORY = ['web' => 'web', 'managed' => 'firm', 'apps' => 'dev', 'cloud' => 'dev', 'game' => 'game', 'mail' => 'firm', 'addon' => 'firm', 'ai' => 'dev'];

    public function __construct(private readonly CatalogService $catalog, private readonly ContentService $content, private readonly IncidentService $incidents, private readonly GameConfigurator $gameConfigurator) {}

    public function data(): Response
    {
        $js = Cache::remember('surfaces:onhost-data.js', 60, function () {
            $payload = [];
            foreach (['cs', 'en'] as $locale) {
                $payload[$locale] = [
                    'catalog' => $this->catalogRows($locale), 'plans' => $this->planRows($locale), 'compare' => (array) config("onhost.content.compare.{$locale}", []),
                    'status' => $this->statusRows($locale), 'locations' => $this->content->locations($locale), 'changelog' => $this->content->changelog($locale),
                    'skus' => $this->skuIndex($locale), 'pages' => $this->pageRows($locale), 'webPlans' => $this->webPlanRows($locale), 'gameSlots' => $this->gameSlotRows(), 'gameConfig' => $this->gameConfigurator->offer($locale, 'CZK'),
                    'pricing' => $this->pricingRows(), 'addons' => $this->addonRows($locale), 'tlds' => $this->tldRows($locale),
                ];
            }
            $json = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG);

            return "// Generated by ONhost from the catalog, status page and content — same shapes as the prototype onhost-data.js.\n"
                ."window.ONHOST_DATA = (function () {\n  var D = {$json};\n  function L(cs) { return cs ? D.cs : D.en; }\n"
                ."  return {\n    catalog: function (cs) { return L(cs).catalog; },\n    plans: function (cs) { return L(cs).plans; },\n    compare: function (cs) { return L(cs).compare; },\n"
                ."    status: function (cs) { return L(cs).status; },\n    locations: function (cs) { return L(cs).locations; },\n    changelog: function (cs) { return L(cs).changelog; },\n    skus: function (cs) { return L(cs).skus; },\n    pages: function (cs) { return L(cs).pages; },\n    webPlans: function (cs) { return L(cs).webPlans; },\n    gameSlots: function (cs) { return L(cs).gameSlots; },\n    gameConfig: function (cs) { return L(cs).gameConfig; },\n    pricing: function (cs) { return L(cs).pricing; },\n    addons: function (cs) { return L(cs).addons; },\n    tlds: function (cs) { return L(cs).tlds; },\n    generatedAt: ".json_encode(now()->toIso8601String())."\n  };\n})();\n";
        });

        return response($js, 200, ['Content-Type' => 'text/javascript; charset=utf-8', 'Cache-Control' => 'public, max-age=60']);
    }

    /** Public product page slug (onhost-svc-*.js) → catalogue products whose plans the page sells. */
    private const PAGE_PRODUCTS = [
        'web-hosting' => ['web-hosting'], 'wordpress' => ['wordpress'], 'eshop' => ['eshop'], 'mail' => ['mail'], 'database' => ['database'], 'backup' => ['backup-plus', 'backup-hourly'],
        'vps' => ['vps'], 'dedicated' => ['vds'], 'ssl' => ['ssl'], 'cdn' => ['cdn'], 'devhosting' => ['apps'], 'gamehosting' => ['game'], 'minecraft' => ['game'],
    ];

    /**
     * Plans, prices, specs and the comparison table of every public product page that has catalogue products behind it
     * (`api/onhost-svc-pages.api.js`, seam #23). Every plan carries its SKU so the checkout maps it without guessing.
     *
     * @return array<string, array<string,mixed>>
     */
    private function pageRows(string $locale): array
    {
        $cs = $locale !== 'en';
        $catalog = collect($this->catalog->publicCatalog($locale, 'CZK'))->keyBy('key');
        $out = [];
        foreach (self::PAGE_PRODUCTS as $slug => $keys) {
            $plans = [];
            $compare = [];
            $family = 'web';
            foreach ($keys as $key) {
                $product = $catalog->get($key);
                if ($product === null) {
                    continue;
                }
                $family = (string) $product['family'];
                $yearly = (($product['meta'] ?? [])['billing_unit'] ?? null) === 'year';
                foreach ((array) $product['plans'] as $plan) {
                    $month = isset($plan['price']['month']) ? self::amount($plan['price']['month']) : 0.0;
                    $features = (array) ($plan['features'] ?? []);
                    $specs = array_values(array_map('strval', (array) ($features[$locale] ?? (array_is_list($features) ? $features : []))));
                    $plans[] = [
                        'name' => (string) $plan['name'], 'tag' => $plan['highlighted'] ? ($cs ? 'Nejoblíbenější' : 'Most popular') : ($plan['sla_class'] === 'ha' ? 'SLA 99,99 %' : ''),
                        'price' => $yearly ? (int) round($month * 12) : (float) round($month, 2), 'unitYear' => $yearly ?: null,
                        'specs' => $specs === [] ? CatalogPresentation::bullets((array) $plan['entitlements'], $family, $locale, 6) : $specs,
                        'sku' => ['product_key' => $product['key'], 'plan_key' => $plan['key'], 'price_year' => self::yearlyPrice($plan)],
                    ];
                    $compare[] = ['name' => (string) $plan['name'], 'entitlements' => (array) $plan['entitlements']];
                }
            }
            if ($plans === []) {
                // a page whose products exist but are not on sale (draft, e.g. Apps without an operated executor): the narrated
                // plans lose their prices and their order buttons become a contact request (api/onhost-svc-pages.api.js)
                if (Product::query()->whereIn('key', $keys)->exists()) {
                    $out[$slug] = [
                        'unavailable' => true, 'kicker' => $cs ? 'Zatím nenabízíme · připravujeme' : 'Not on offer yet · in preparation', 'label' => $cs ? 'připravujeme' : 'coming soon',
                        'note' => $cs ? 'Tuto službu zatím neprodáváme. Ozvěte se a dáme vám vědět, jakmile bude v nabídce.' : 'This service is not sold yet. Get in touch and we will tell you when it is available.',
                        'cta' => $cs ? 'Nezávazně poptat' : 'Request it',
                    ];
                }

                continue;
            }
            $out[$slug] = array_filter([
                'plans' => $plans, 'cmp' => ['cols' => array_map(fn ($p) => $p['name'], $compare), 'rows' => CatalogPresentation::compareRows($compare, $family, $locale)],
                'keep_first' => $slug === 'ssl' ? 1 : null, // the free DV certificate stays as authored
            ], fn ($v) => $v !== null);
            // the detailed configuration listing, the per-item add-ons of the page's main product and (web hosting) the configurator
            $out[$slug]['details'] = ['cols' => array_map(fn ($p) => $p['name'], $compare), 'rows' => CatalogPresentation::detailRows($compare, $family, $locale)];
            $addons = $this->addonRows($locale);
            if (isset($addons[$keys[0]])) {
                $out[$slug]['addons'] = $addons[$keys[0]];
            }
            if ($slug === 'web-hosting') {
                $out[$slug]['builder'] = $this->builderRows($locale);
            }
            if (in_array('game', $keys, true)) { // the game pages name the templates the panel really offers (mapped and orderable), Minecraft flavours on the Minecraft page
                $templates = app(GameTemplates::class);
                $labels = [];
                foreach ((array) data_get($catalog->get('game'), 'meta.eggs', []) as $eggKey) {
                    $isMinecraft = str_starts_with((string) $eggKey, 'minecraft-');
                    if (($slug === 'minecraft') === $isMinecraft && $templates->availability((string) $eggKey)['available']) {
                        $labels[] = $slug === 'minecraft' ? trim(str_replace('Minecraft ·', '', (string) config("onhost.game.eggs.{$eggKey}.label", $eggKey))) : (string) config("onhost.game.eggs.{$eggKey}.label", $eggKey);
                    }
                }
                if ($labels !== []) {
                    $out[$slug]['chips'] = $labels;
                    $out[$slug]['kicker'] = implode(' · ', array_slice($labels, 0, 4));
                    $out[$slug]['kpi_games'] = [(string) count($labels), $cs ? ($slug === 'minecraft' ? 'variant Minecraftu' : 'her na klik') : ($slug === 'minecraft' ? 'Minecraft flavours' : 'games, one click')];
                }
            }
        }
        $out['domains'] = $this->domainPageRows($locale);

        return $out;
    }

    /** Domains page: the most wanted TLDs with the catalogue prices; the CTA checks availability instead of adding a name-less domain to the cart. */
    private function domainPageRows(string $locale): array
    {
        $cs = $locale !== 'en';
        $plans = [];
        foreach ((array) config('onhost.content.domain_page_tlds', ['cz', 'com', 'eu']) as $i => $tld) {
            try {
                $policy = $this->catalog->tld($tld);
                $price = $this->catalog->domainPrice($tld, 'CZK');
            } catch (DomainError) {
                continue;
            }
            $register = self::amount($price->register());
            $plans[] = [
                'name' => '.'.$policy->tld, 'tag' => $i === 0 ? ($cs ? 'Nejžádanější' : 'Most wanted') : '', 'price' => 0, 'unitYear' => true,
                'priceLabel' => number_format($register, 0, ',', ' ').' Kč', 'priceNote' => ($cs ? '/ rok · s DPH ' : '/ year · incl. VAT ').number_format($register * 1.21, 0, ',', ' ').' Kč'.($cs ? ' · obnova ' : ' · renewal ').number_format(self::amount($price->renew()), 0, ',', ' ').($cs ? ' Kč / rok' : ' Kč / year'),
                'ctaLabel' => $cs ? 'Ověřit dostupnost' : 'Check availability', 'goto' => 'home',
                'specs' => array_values(array_filter([
                    $cs ? 'Registrace na rok' : 'One-year registration', $cs ? 'DNS hosting v ceně' : 'DNS hosting included', $policy->dnssec_supported ? 'DNSSEC' : null,
                    ($cs ? 'Obnova ' : 'Renewal ').number_format(self::amount($price->renew()), 0, ',', ' ').($cs ? ' Kč / rok' : ' Kč / year'), $cs ? 'Držitelem jste vy' : 'You are the registrant',
                ])),
            ];
        }

        return ['plans' => $plans, 'keep_last' => 1];
    }

    /**
     * Game hosting landing cards (`gameSlots`, the prototype's shape with both locales in one row: `{p, hi, cs: [name, badge,
     * tagline, 4 bullets], en: […]}`): one card per game the panel offers with its "from" price — the minimum configuration
     * of the configurator priced (audit §5v); `egg` lets the card open the configurator with the game selected.
     *
     * @return list<array{p:int,hi:bool,egg:string,cs:array<int,mixed>,en:array<int,mixed>}>
     */
    private function gameSlotRows(): array
    {
        $offer = $this->gameConfigurator->offer('cs', 'CZK');
        if ($offer === null) {
            return [];
        }
        $rows = [];
        foreach ($offer['games'] as $i => $game) {
            $min = $game['min'];
            $card = function (bool $cs) use ($game, $min): array {
                $feats = [
                    ($cs ? 'od ' : 'from ').($min['ram_gb'] ?? 1).' GB RAM',
                    ($cs ? 'od ' : 'from ').($min['vcpu'] ?? 1).' vCPU',
                    ($cs ? 'od ' : 'from ').($min['nvme_gb'] ?? 10).' GB NVMe',
                    $game['slots_from'] !== null ? ($cs ? '≈ '.$game['slots_from'].' slotů v minimu' : '≈ '.$game['slots_from'].' slots at minimum') : ($cs ? 'sloty bez limitu' : 'unlimited slots'),
                ];

                return [$game['label'], $game['inputs'] !== [] ? ($cs ? 'Vyžaduje token' : 'Needs a token') : '', $cs ? $game['note'] : '', $feats];
            };
            $rows[] = ['p' => (int) round((float) $game['from']), 'hi' => false, 'egg' => (string) $game['key'], 'cs' => $card(true), 'en' => $card(false)];
        }

        return $rows;
    }

    /** Web hosting landing cards (`webPlans`): [name, monthly net price, tagline, 5 bullets, badge] from the web hosting product. @return list<array<int,mixed>> */
    private function webPlanRows(string $locale): array
    {
        $cs = $locale !== 'en';
        $productKey = (string) config('onhost.content.plans_product', 'web-hosting');
        $product = collect($this->catalog->publicCatalog($locale, 'CZK'))->firstWhere('key', $productKey);
        $rows = [];
        foreach ((array) ($product['plans'] ?? []) as $plan) {
            $features = (array) ($plan['features'] ?? []);
            $feats = array_values(array_map('strval', (array) ($features[$locale] ?? (array_is_list($features) ? $features : []))));
            $rows[] = [
                (string) $plan['name'], (int) round(isset($plan['price']['month']) ? self::amount($plan['price']['month']) : 0.0), (string) $plan['description'],
                array_slice($feats === [] ? CatalogPresentation::bullets((array) $plan['entitlements'], (string) ($product['family'] ?? 'web'), $locale, 5) : $feats, 0, 5),
                $plan['highlighted'] ? ($cs ? 'Nejčastější volba' : 'Most chosen') : ($plan['sla_class'] !== 'standard' ? ($cs ? 'S SLA' : 'With SLA') : ''),
            ];
        }

        return $rows;
    }

    /** Signed-in organization's services for the panel seam. */
    public function panel(Request $request): Response
    {
        $user = $request->user();
        if ($user === null) {
            abort(401);
        }
        $organizationId = $request->query('organization') ?: OrganizationMembership::query()->where('user_id', $user->id)->current()->orderBy('joined_at')->value('organization_id');
        if ($organizationId === null || ! OrganizationMembership::query()->where('user_id', $user->id)->where('organization_id', $organizationId)->current()->exists()) {
            $locale = $user->locale ?? 'cs';
            $payload = ['services' => [], 'servers' => [], 'organization' => null, 'needs_organization' => true, 'kpis' => ['credit' => 0.0, 'currency' => 'CZK'], // audit §5z: the order centre asks for a customer profile first
                'catalog' => $this->panelCatalog($locale), 'regions' => Region::query()->where('state', 'active')->orderBy('code')->get()->map(fn ($r) => ['code' => $r->code, 'name' => $r->name, 'datacenter' => $r->datacenter])->all(),
                'consents' => $this->consentVersions(), 'tlds' => $this->panelTlds(null), 'game_config' => $this->gameConfigurator->offer($locale, 'CZK'), 'generated_at' => now()->toIso8601String()];
        } else {
            $payload = $this->panelPayload((string) $organizationId, $user->locale ?? 'cs');
        }
        $json = json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_HEX_TAG);

        return response("window.ONHOST_PANEL = {$json};\n", 200, ['Content-Type' => 'text/javascript; charset=utf-8', 'Cache-Control' => 'no-store']);
    }

    // ── onhost-data.js rows ──────────────────────────────────────────────────

    private function catalogRows(string $locale): array
    {
        $rows = [];
        foreach ($this->catalog->publicCatalog($locale, 'CZK') as $product) {
            $prices = array_values(array_filter(array_map(fn ($p) => isset($p['price']['month']) ? self::amount($p['price']['month']) : null, $product['plans'] ?? [])));
            $meta = (array) ($product['meta'] ?? []);
            $badge = $meta['badge'][$locale] ?? $meta['badge'] ?? '';
            if (($product['family'] ?? null) === 'game' && ($offer = $this->gameConfigurator->offer($locale, 'CZK')) !== null && $offer['groups'] !== []) {
                // audit §5w: the home page lists what a gamer can order — one summary row ("Vše") and one row per game ("Gaming")
                $labels = array_column($offer['groups'], 'label');
                $rows[] = ['code' => 'GAME', 'cat' => 'game', 'price' => (int) round(min(array_column($offer['groups'], 'from'))), $locale => [$locale === 'en' ? 'Game servers' : 'Herní servery', implode(', ', array_slice($labels, 0, 4)).(count($labels) > 4 ? ($locale === 'en' ? ' and '.(count($labels) - 4).' more' : ' a dalších '.(count($labels) - 4)) : ''), ''], 'key' => $product['key'], 'game' => true];
                foreach ($offer['groups'] as $group) {
                    $words = preg_split('/[\s-]+/', (string) $group['label']) ?: ['GAME'];
                    $code = strtoupper(count($words) === 1 ? mb_substr($words[0], 0, 3) : implode('', array_map(fn ($w) => mb_substr($w, 0, 1), array_slice($words, 0, 3))));
                    $rows[] = ['code' => $code, 'cat' => 'game', 'price' => (int) round((float) $group['from']), $locale => [(string) $group['label'], (string) $group['note'], ''], 'key' => $product['key'], 'game' => true, 'sub' => true, 'group' => $group['key'], 'egg' => $group['eggs'][0]];
                }

                continue;
            }
            $rows[] = [
                'code' => (string) ($meta['code'] ?? strtoupper(substr(str_replace('-', '', (string) $product['key']), 0, 4))),
                'cat' => self::CATEGORY[$product['family']] ?? 'firm',
                'price' => $prices === [] ? 0 : (int) round(min($prices)),
                $locale => [(string) $product['name'], (string) $product['description'], is_string($badge) ? $badge : ''],
                'key' => $product['key'],
            ];
        }

        return $rows;
    }

    private function planRows(string $locale): array
    {
        $productKey = (string) config('onhost.content.plans_product', 'web-hosting');
        $product = collect($this->catalog->publicCatalog($locale, 'CZK'))->firstWhere('key', $productKey);
        $rows = [];
        foreach ((array) ($product['plans'] ?? []) as $plan) {
            $features = (array) ($plan['features'] ?? []);
            $features = array_values(array_map('strval', (array) ($features[$locale] ?? (array_is_list($features) ? $features : []))));
            if ($features === []) {
                $features = CatalogPresentation::bullets((array) ($plan['entitlements'] ?? []), (string) ($product['family'] ?? 'web'), $locale, 5);
            }
            $rows[] = [
                'key' => $plan['key'], 'price' => (int) round(isset($plan['price']['month']) ? self::amount($plan['price']['month']) : 0.0), 'hi' => (bool) $plan['highlighted'],
                $locale => [(string) $plan['name'], $plan['highlighted'] ? ($locale === 'cs' ? 'Nejčastější volba' : 'Most popular') : ($plan['sla_class'] === 'ha' ? 'SLA 99,99 %' : ''), (string) $plan['description'], $features],
            ];
        }

        return $rows;
    }

    /**
     * Name → catalog identity for the prototype cart, which only carries the displayed name and price
     * (`addToCart(name, price)`): every plan and product name maps to `{product_key, plan_key}` so the checkout
     * seam can turn the cart into real SKUs. Keys are lower-cased display names; `name|price` variants disambiguate.
     */
    private function skuIndex(string $locale): array
    {
        $index = [];
        foreach ($this->catalog->publicCatalog($locale, 'CZK') as $product) {
            $plans = (array) ($product['plans'] ?? []);
            $cheapest = null;
            foreach ($plans as $plan) {
                $price = isset($plan['price']['month']) ? (int) round(self::amount($plan['price']['month'])) : null;
                $entry = ['product_key' => $product['key'], 'plan_key' => $plan['key'], 'price' => $price, 'price_year' => self::yearlyPrice($plan)];
                $index[mb_strtolower((string) $plan['name'])] = $entry;
                if (($product['family'] ?? null) === 'game') { // the game landing's cards add to the cart as "Gamehosting <plan>" / "Game hosting <plan>"
                    foreach (['gamehosting ', 'game hosting '] as $prefix) {
                        $index[$prefix.mb_strtolower((string) $plan['name'])] = $entry;
                        if ($price !== null) {
                            $index[$prefix.mb_strtolower((string) $plan['name']).'|'.$price] = $entry;
                        }
                    }
                }
                $index[mb_strtolower((string) $product['name'].' '.$plan['name'])] = $entry;
                $index[mb_strtolower((string) $product['name'].' · '.$plan['name'])] = $entry; // product pages add `crumb · plan`
                if ($price !== null) {
                    $index[mb_strtolower((string) $product['name'].' · '.$plan['name']).'|'.$price] = $entry;
                }
                if ($price !== null) {
                    $index[mb_strtolower((string) $plan['name']).'|'.$price] = $entry;
                }
                if ($cheapest === null || ($price !== null && $price < ($cheapest['price'] ?? PHP_INT_MAX))) {
                    $cheapest = $entry;
                }
            }
            if ($cheapest !== null) {
                $index[mb_strtolower((string) $product['name'])] = $cheapest;
                $index[mb_strtolower((string) $product['key'])] = $cheapest;
            }
        }

        return $index;
    }

    /** Commercial rules the cart applies (seam #24): commitment discounts (none unless staff approved one), product → family, active domain discounts. */
    private function pricingRows(): array
    {
        $rules = app(PricingRules::class);
        $families = [];
        foreach (Product::query()->where('state', 'active')->get(['key', 'family']) as $product) {
            $families[$product->key] = $product->family;
        }
        $domain = [];
        foreach (array_keys($rules->domainDiscounts()) as $tld) {
            $d = $rules->domainDiscount($tld, 'register');
            if ($d['percent'] > 0) {
                $domain[$tld] = ['register' => $d['percent'], 'label' => $d['label']];
            }
        }

        return ['commit' => $rules->commitDiscounts(), 'months' => PricingRules::COMMIT_MONTHS, 'product_families' => $families, 'domain_discounts' => $domain];
    }

    /** @var array<string, array<string, array<string,mixed>>> */
    private array $addonCache = [];

    /**
     * Per-product add-ons for the cart and the product pages (seam #24): priced options (sliders, switches, selects) and
     * the add-on products staff allow next to the product, each with its plans and monthly prices. Keyed by product key.
     *
     * @return array<string, array{options: list<array<string,mixed>>, products: list<array<string,mixed>>}>
     */
    private function addonRows(string $locale): array
    {
        if (isset($this->addonCache[$locale])) {
            return $this->addonCache[$locale];
        }
        $rules = app(PricingRules::class);
        $catalog = collect($this->catalog->publicCatalog($locale, 'CZK'))->keyBy('key');
        $out = [];
        foreach ($this->catalog->products() as $product) {
            $options = [];
            foreach ($product->family === 'game' ? [] : $product->options->sortBy('sort') as $option) { // game sliders belong to the configurator, not to cart add-ons
                $options[] = [
                    'key' => $option->key, 'kind' => $option->kind, 'label' => (string) ($option->label[$locale] ?? $option->label['cs'] ?? $option->key), 'desc' => (string) (data_get($option->meta, "desc.{$locale}") ?? data_get($option->meta, 'desc.cs') ?? ''), 'unit' => $option->unit,
                    'min' => $option->min !== null ? (float) $option->min : null, 'max' => $option->max !== null ? (float) $option->max : null, 'step' => $option->step !== null ? (float) $option->step : null, 'default' => $option->default_value !== null ? (float) $option->default_value : null,
                    'price' => ((int) ($option->price_per_unit_minor['CZK'] ?? 0)) / 100,
                    'choices' => array_values(array_map(fn ($c) => ['key' => (string) $c['key'], 'label' => is_array($c['label'] ?? null) ? (string) ($c['label'][$locale] ?? $c['label']['cs'] ?? $c['key']) : (string) ($c['label'] ?? $c['key']), 'units' => (float) ($c['units'] ?? 0)], (array) ($option->choices ?? []))),
                ];
            }
            $products = [];
            foreach ($rules->addonProducts($product) as $key) {
                $addon = $catalog->get($key);
                if ($addon === null) {
                    continue;
                }
                $yearly = (($addon['meta'] ?? [])['billing_unit'] ?? null) === 'year';
                $plans = [];
                foreach ((array) $addon['plans'] as $plan) {
                    $month = isset($plan['price']['month']) ? self::amount($plan['price']['month']) : 0.0;
                    if ($month <= 0) {
                        continue;
                    }
                    $plans[] = ['key' => $plan['key'], 'name' => (string) $plan['name'], 'price' => $yearly ? (int) round($month * 12) : (float) round($month, 2), 'unit_year' => $yearly, 'desc' => (string) $plan['description']];
                }
                if ($plans === []) {
                    continue;
                }
                $products[] = ['key' => $key, 'name' => (string) $addon['name'], 'desc' => (string) $addon['description'], 'family' => $addon['family'], 'plans' => $plans];
            }
            if ($options === [] && $products === []) {
                continue;
            }
            $out[$product->key] = ['options' => $options, 'products' => $products];
        }

        return $this->addonCache[$locale] = $out;
    }

    /** Sold TLDs with CZK prices for the public domain search (the most wanted first). @return list<array<string,mixed>> */
    private function tldRows(string $locale): array
    {
        $rules = app(PricingRules::class);
        $first = array_values((array) config('onhost.content.domain_page_tlds', ['cz', 'com', 'eu']));
        $rows = [];
        foreach ($this->catalog->tlds() as $policy) {
            try {
                $price = $this->catalog->domainPrice($policy->tld, 'CZK');
            } catch (DomainError) {
                continue;
            }
            $d = $rules->domainDiscount($policy->tld, 'register');
            $rows[] = ['tld' => $policy->tld, 'register' => self::amount($price->register()), 'renew' => self::amount($price->renew()), 'transfer' => self::amount($price->transfer()), 'periods' => (array) ($policy->periods ?: [1]), 'default_period' => (int) $policy->default_period, 'discount' => $d['percent'], 'discount_label' => $d['label'], 'dnssec' => (bool) $policy->dnssec_supported];
        }
        usort($rows, function ($a, $b) use ($first) {
            $ia = array_search($a['tld'], $first, true);
            $ib = array_search($b['tld'], $first, true);

            return [$ia === false ? PHP_INT_MAX : $ia, $a['tld']] <=> [$ib === false ? PHP_INT_MAX : $ib, $b['tld']];
        });

        return $rows;
    }

    /** The configurator ("Tarif na míru"): base plan of `web-custom` plus its priced parameters. */
    private function builderRows(string $locale): ?array
    {
        $product = collect($this->catalog->publicCatalog($locale, 'CZK'))->firstWhere('key', 'web-custom');
        if ($product === null || empty($product['plans'])) {
            return null;
        }
        $plan = $product['plans'][0];

        return [
            'product_key' => 'web-custom', 'plan_key' => $plan['key'], 'name' => (string) $product['name'], 'lead' => (string) $product['description'],
            'base_price' => isset($plan['price']['month']) ? (float) round(self::amount($plan['price']['month']), 2) : 0.0, 'base' => (array) $plan['entitlements'], 'family' => (string) $product['family'],
            'options' => $this->addonRows($locale)['web-custom']['options'] ?? [], 'sku' => ['product_key' => 'web-custom', 'plan_key' => $plan['key'], 'price_year' => self::yearlyPrice($plan)],
        ];
    }

    /** The yearly list price of a public-catalogue plan in major units (the cart shows it for a 12- or 24-month term), null when the plan is monthly only. */
    private static function yearlyPrice(array $plan): ?float
    {
        return isset($plan['price_year']['year']) ? (float) round(self::amount($plan['price_year']['year']), 2) : null;
    }

    /** Money value object, its JSON form `{minor, currency, decimal}` or a plain number → float amount. */
    private static function amount(mixed $value): float
    {
        if ($value instanceof Money) {
            return (float) $value->toDecimal();
        }
        if (is_array($value)) {
            return (float) ($value['decimal'] ?? (isset($value['minor']) ? $value['minor'] / 100 : 0));
        }

        return (float) $value;
    }

    private function statusRows(string $locale): array
    {
        $rows = [];
        foreach ($this->incidents->publicStatus()['components'] as $component) {
            $u = rtrim(rtrim(number_format((float) $component['u'], 3, '.', ''), '0'), '.');
            $rows[] = ['n' => $component['n'], 'u' => $locale === 'cs' ? str_replace('.', ',', $u).' %' : $u.'%', 'bad' => $component['bad'], 'state' => $component['state'], 'key' => $component['key']];
        }

        return $rows;
    }

    // ── onhost-panel.js payload ──────────────────────────────────────────────

    private function panelPayload(string $organizationId, string $locale): array
    {
        $cs = $locale === 'cs';
        $t = fn (string $a, string $b) => $cs ? $a : $b;
        $services = Service::query()->where('organization_id', $organizationId)->whereNotIn('state', [ServiceStateMachine::TERMINATED])->orderBy('created_at')->get();
        $subs = Subscription::query()->where('organization_id', $organizationId)->get()->keyBy('service_id');
        $planNames = [];
        $groups = array_fill_keys(array_keys(PanelNavigation::CATEGORIES), []);
        $executors = Product::query()->pluck('executor', 'key')->all();
        $servers = [];

        foreach (Domain::query()->where('organization_id', $organizationId)->orderBy('fqdn_ascii')->get() as $d) {
            $days = $d->daysToExpiry();
            $groups['domain'][] = [
                'id' => $d->id, 'type' => 'domain', 'name' => $d->fqdn_unicode ?: $d->fqdn_ascii,
                'spec' => $t('registrace u ONhost', 'registered via ONhost').' · '.($d->dnssec ? $t('DNSSEC zapnuté', 'DNSSEC on') : $t('DNSSEC vypnuté', 'DNSSEC off')).' · '.($d->usesOnhostDns() ? $t('DNS u ONhost', 'ONhost DNS') : $t('externí DNS', 'external DNS')),
                'meta' => $days === null ? $t('bez data expirace', 'no expiry date') : ($cs ? "expiruje za {$days} dní · autorenew ".($d->auto_renew ? 'zapnutý' : 'vypnutý') : "expires in {$days} days · auto-renew ".($d->auto_renew ? 'on' : 'off')),
                'value' => $d->expires_at?->toDateString() ?? '', 'state' => $this->domainState($d->state, $cs), 'kind' => $days !== null && $days < 14 ? 'warn' : (in_array($d->state, ['EXPIRED', 'REDEMPTION'], true) ? 'bad' : 'ok'),
                // real domain state for the domain workbench (api/onhost-panel-workbench.api.js, seam #21); the registrar behind the domain is never exposed
                'apiState' => $d->state, 'fqdn' => $d->fqdn_ascii, 'expires_at' => $d->expires_at?->toIso8601String(), 'days' => $days, 'auto_renew' => (bool) $d->auto_renew, 'renewal_period' => (int) $d->renewal_period,
                'transfer_lock' => (bool) $d->transfer_lock, 'dnssec' => (bool) $d->dnssec, 'dns_provider' => $d->usesOnhostDns() ? 'onhost' : 'external', 'dns_zone_id' => $d->dns_zone_id, 'nameservers' => array_values((array) $d->nameservers),
            ];
        }

        $controlPlane = []; // per provider instance: can the service be managed right now (H324)
        foreach ($services as $s) {
            $spec = (array) ($s->desired_spec ?? []);
            $sub = $subs->get($s->id);
            $monthly = $sub === null ? 0 : ($sub->period === 'year' ? intdiv((int) $sub->amount_minor, 12) : (int) $sub->amount_minor) / 100;
            $ui = ServiceStateMachine::machine()->toArray()[$s->state] ?? null;
            $stateLabel = $ui['label'] ?? $s->state;
            $kind = match ($s->state) {
                ServiceStateMachine::ACTIVE => 'ok', ServiceStateMachine::DEGRADED, ServiceStateMachine::SUSPENDED, ServiceStateMachine::RESIZING => 'warn', ServiceStateMachine::PROVISIONING, ServiceStateMachine::VERIFYING => 'warn', default => 'bad',
            };
            $sizes = isset($spec['vcpu']) ? sprintf('%d vCPU / %s GB / %s GB NVMe', (int) $spec['vcpu'], isset($spec['ram_mb']) ? round(((int) $spec['ram_mb']) / 1024) : '?', $spec['nvme_gb'] ?? '?') : null;
            // the sidebar category comes from the offer definition (domains/Catalog/PanelNavigation.php); add-ons live inside their parent service
            $category = PanelNavigation::categoryFor((string) $s->family, (string) $s->product_key, $executors[$s->product_key] ?? null);
            if ($category === null) {
                continue;
            }
            $type = match ($s->family) {
                'game' => str_contains((string) $s->product_key, 'cs2') ? 'cs2' : 'mc',
                'cloud', 'data' => $category === 'bucket' ? 'bucket' : 'vps',
                'mail' => 'mail',
                default => 'web',
            };
            // the plan and its billing at a glance: "Standard · ročně · obnova 13. 9. 2027" (the workbench shows the full summary)
            $planName = $s->plan_version_id ? ($planNames[$s->plan_version_id] ??= PlanVersion::query()->with('plan')->find($s->plan_version_id)?->plan?->localizedName($locale)) : null;
            $renewsAt = $sub === null || $sub->cancel_at_period_end ? null : ($sub->next_renewal_at ?? $sub->current_period_end);
            $renewalAmount = $sub === null ? '' : Money::minor((int) $sub->amount_minor, (string) $sub->currency)->format($locale).($sub->period === 'year' ? $t(' / rok', ' / yr') : $t(' / měs.', ' / mo'));
            $billing = $sub === null ? '' : ($sub->period === 'year' ? $t('ročně', 'yearly') : $t('měsíčně', 'monthly')).($renewsAt ? ' · '.$t('obnova ', 'renews ').$renewsAt->format($cs ? 'j. n. Y' : 'Y-m-d').' · '.$renewalAmount : ($sub->cancel_at_period_end ? ' · '.$t('končí ', 'ends ').$sub->current_period_end?->format($cs ? 'j. n. Y' : 'Y-m-d') : ' · '.$renewalAmount));
            // the usage watch's verdict (tags.usage): a row near its plan limit says so and turns amber (audit §5e-1)
            $usage = (array) (($s->tags ?? [])['usage'] ?? []);
            $usageTop = is_array($usage['metrics'] ?? null) ? UsageWatch::top($usage['metrics']) : null;
            $usageNote = ($usage['level'] ?? 'ok') !== 'ok' && $usageTop !== null ? ' · '.$t('kapacita ', 'capacity ').$usageTop['pct'].' % ('.UsageWatch::metricLabel($usageTop['key'], $locale).')' : '';
            $kind = $usageNote !== '' && $kind === 'ok' ? 'warn' : $kind;
            // a VPS or a game server that stopped on its own says so on its row (H14)
            $availability = in_array($s->family, AvailabilityWatch::FAMILIES, true) ? AvailabilityWatch::of($s) : null;
            $downNote = $availability !== null && $availability['alerted'] && $availability['down_since'] !== null
                ? ' · '.$t('neběží od ', 'not running since ').Carbon::parse($availability['down_since'])->timezone((string) config('onhost.timezone_display', 'Europe/Prague'))->format($cs ? 'j. n. H:i' : 'Y-m-d H:i') : '';
            $kind = $downNote !== '' && $kind === 'ok' ? 'warn' : $kind;
            // a cancelled service waits deactivated for its restore window; the row says how long (audit §5ab)
            $deletion = (array) (($s->tags ?? [])['deletion'] ?? []);
            $graceLeft = $s->terminate_at === null ? null : (int) now()->diffInDays($s->terminate_at, false);
            $deletionNote = $graceLeft === null ? '' : ' · '.($graceLeft > 0 ? $t('obnovit lze ještě ', 'restorable for ').$graceLeft.$t(' dní', ' days') : $t('čeká na odstranění', 'awaiting removal'));
            $kind = $graceLeft === null ? $kind : 'warn';
            // a reading the reconciler has not refreshed must not look current (H325)
            $freshness = ServiceFreshness::of($s);
            $staleNote = $freshness['stale'] && in_array($s->state, [ServiceStateMachine::ACTIVE, ServiceStateMachine::DEGRADED], true)
                ? ' · '.($freshness['measured_at'] === null ? $t('stav zatím nezměřen', 'state not measured yet') : $t('stav z ', 'state as of ').Carbon::parse($freshness['measured_at'])->timezone((string) config('onhost.timezone_display', 'Europe/Prague'))->format($cs ? 'j. n. H:i' : 'Y-m-d H:i').$t(' (zastaralý)', ' (stale)')) : '';
            $kind = $staleNote !== '' && $kind === 'ok' ? 'warn' : $kind;
            $control = $controlPlane[(string) $s->provider_instance_id] ??= ControlPlaneStatus::of($s);
            $controlNote = $control['available'] ? '' : ' · '.match ($control['state']) {
                'maintenance' => $t('správa pozastavena, údržba panelu', 'management paused, panel maintenance'),
                'unreachable' => $t('panel neodpovídá, změny čekají', 'panel not answering, changes wait'),
                default => $t('správa dočasně nedostupná', 'management temporarily unavailable'),
            };
            $groups[$category][] = [
                'id' => $s->id, 'type' => $type, 'name' => $s->label ?: ($s->hostname ?: $s->name), 'spec' => $sizes ?? ($s->name.($spec['php_version'] ?? null ? ' · PHP '.$spec['php_version'] : '')),
                'meta' => trim(($s->hostname ? $s->hostname.' · ' : '').strtoupper((string) $s->region_code).($s->sla_class !== 'standard' ? ' · SLA '.$s->sla_class : '').($planName ? ' · '.$planName : '').($billing !== '' ? ' · '.$billing : '').$usageNote.$downNote.$deletionNote.$staleNote.$controlNote), 'value' => $s->activated_at?->toDateString() ?? '',
                'state' => $stateLabel, 'kind' => $kind, 'product' => $s->product_key, 'apiState' => $s->state, 'usage' => $usageTop !== null ? ['level' => $usage['level'] ?? 'ok', 'pct' => $usageTop['pct'], 'metric' => $usageTop['key']] : null,
                'plan' => $planName, 'period' => $sub?->period, 'renews_at' => $renewsAt?->toIso8601String(), 'monthly' => $monthly, 'renewal' => $renewalAmount !== '' ? $renewalAmount : null,
                'deletion' => $graceLeft === null ? null : ['grace_until' => $s->terminate_at?->toIso8601String(), 'days_left' => max(0, $graceLeft), 'archive_backup_id' => $deletion['archive_backup_id'] ?? null],
                'freshness' => $freshness, 'control_plane' => $control, 'suspension' => SuspensionHold::of($s), 'availability' => $availability,
            ];
            if (in_array($s->family, ['cloud', 'game'], true)) {
                $health = (array) ($s->health ?? []);
                $access = (array) (($s->tags ?? [])['access'] ?? []);
                $servers[] = [
                    'id' => $s->id, 'name' => $s->label ?: ($s->hostname ?: $s->name), 'spec' => $sizes ?? $s->name, 'site' => strtoupper((string) ($s->region_code ?? '')),
                    'state' => match ($s->state) {
                        ServiceStateMachine::ACTIVE => 'running', ServiceStateMachine::SUSPENDED, ServiceStateMachine::SUSPENDING => 'paused', ServiceStateMachine::PROVISIONING, ServiceStateMachine::VERIFYING => 'creating', ServiceStateMachine::RESIZING => 'scaling', ServiceStateMachine::DEGRADED => 'degraded', default => strtolower($s->state)
                    },
                    'stale' => $freshness['stale'], 'measured_at' => $freshness['measured_at'],
                    'cpu' => (int) ($health['cpu_pct'] ?? 0), 'ram' => (int) ($health['ram_pct'] ?? 0), 'net' => (int) ($health['net_pct'] ?? 0), 'price' => $monthly,
                    'os' => (string) ($spec['image'] ?? $spec['egg'] ?? $s->product_key), 'ip' => (string) ($access['ipv4'] ?? $access['ip'] ?? $access['address'] ?? ''), 'migration' => ServiceMigrationService::status($s), 'created' => $s->activated_at?->format('j. n. Y') ?? $s->created_at->format('j. n. Y'), // game servers: address = ip:port of the primary allocation
                ];
            }
        }

        return [
            'services' => $groups, 'servers' => $servers, 'organization' => $organizationId, 'kpis' => $this->kpis($organizationId, $services, $cs), 'billing' => $this->billing($organizationId, $services, $cs),
            'nav' => app(PanelNavigation::class)->effective($organizationId), 'catalog' => $this->panelCatalog($locale), 'regions' => Region::query()->where('state', 'active')->orderBy('code')->get()->map(fn ($r) => ['code' => $r->code, 'name' => $r->name, 'datacenter' => $r->datacenter])->all(),
            'consents' => $this->consentVersions(), 'tlds' => $this->panelTlds($organizationId), 'game_config' => $this->gameConfigurator->offer($locale, 'CZK'), 'generated_at' => now()->toIso8601String(),
        ];
    }

    /** Registrable TLDs with the organization's prices for the "Nová služba → Doména" wizard step (decimal amounts, periods, terms links). @return list<array<string,mixed>> */
    private function panelTlds(?string $organizationId): array
    {
        $currency = $organizationId === null ? 'CZK' : (string) (Organization::query()->find($organizationId)?->currency ?? 'CZK');
        $catalog = app(CatalogService::class);
        $out = [];
        foreach ($catalog->tlds() as $policy) {
            try {
                $price = $catalog->domainPrice($policy->tld, $currency);
            } catch (DomainError) {
                continue;
            }
            $out[] = [
                'tld' => $policy->tld, 'periods' => array_values((array) ($policy->periods ?: [1])), 'default_period' => (int) $policy->default_period, 'currency' => $currency,
                'register' => $price->register()->toDecimal(), 'renew' => $price->renew()->toDecimal(), 'transfer' => $price->transfer()->toDecimal(),
                'registry_terms_url' => $policy->registry_terms_url, 'registrar_terms_url' => $policy->registrar_terms_url,
            ];
        }

        return $out;
    }

    /** Orderable products and plans for the panel's "Nová služba" wizard (api/onhost-panel-order.api.js): keys the cart accepts, monthly prices as decimals. */
    private function panelCatalog(string $locale): array
    {
        $out = [];
        $registry = app(ProviderRegistry::class);
        $placements = app(PlacementService::class);
        $executors = Product::query()->whereIn('state', ['active'])->pluck('executor', 'key')->all();
        // a category staff switched off in the sidebar settings sells nothing new (existing services stay manageable)
        $categoryOrderable = [];
        foreach (app(PanelNavigation::class)->effective(null)['categories'] as $category) {
            $categoryOrderable[$category['key']] = $category['orderable'];
        }
        foreach ($this->catalog->publicCatalog($locale, 'CZK') as $product) {
            $plans = [];
            foreach ((array) ($product['plans'] ?? []) as $plan) {
                if (! isset($plan['price']['month'])) {
                    continue;
                }
                $plans[] = ['key' => $plan['key'], 'name' => (string) $plan['name'], 'spec' => (string) ($plan['description'] ?? ''), 'monthly' => self::amount($plan['price']['month']), 'yearly' => isset($plan['price_year']['year']) ? self::amount($plan['price_year']['year']) : null, 'highlighted' => (bool) ($plan['highlighted'] ?? false), 'ram_mb' => (int) data_get($plan, 'entitlements.ram_mb', 0),
                    // the in-panel order centre (api/onhost-panel-shop.api.js) shows what a plan contains
                    'features' => (function () use ($plan, $product, $locale) {
                        $f = (array) ($plan['features'] ?? []);
                        $f = array_values(array_map('strval', (array) ($f[$locale] ?? (array_is_list($f) ? $f : []))));

                        return array_slice($f === [] ? CatalogPresentation::bullets((array) ($plan['entitlements'] ?? []), (string) ($product['family'] ?? 'web'), $locale, 6) : $f, 0, 6);
                    })(),
                    'sla' => (string) ($plan['sla_class'] ?? 'standard')]; // §5t-2: the wizard checks the template's RAM floor
            }
            if ($plans === []) {
                continue;
            }
            // an executor without a usable instance or placement cannot be provisioned: the wizard lists the product as "on request"
            $executor = $executors[$product['key']] ?? null;
            $orderable = $executor === null || $executor === '' || $placements->resolve($product['key'], null, null) !== null || $registry->findInstance((string) $executor) !== null;
            $category = PanelNavigation::categoryFor((string) $product['family'], (string) $product['key'], $executor);
            $orderable = $orderable && ($category === null || ($categoryOrderable[$category] ?? true));
            // game servers: the templates the product sells (Product.meta.eggs) with the presets' labels — the wizard's "Systém a obraz" step offers them
            $eggs = [];
            foreach ((array) data_get($product, 'meta.eggs', []) as $eggKey) {
                $preset = (array) config("onhost.game.eggs.{$eggKey}", []);
                $templates = app(GameTemplates::class);
                if (! $templates->availability((string) $eggKey)['available']) {
                    continue; // §5s: a template no panel can create is not offered
                }
                $eggs[] = ['key' => (string) $eggKey, 'label' => (string) ($preset['label'] ?? $eggKey), 'note' => (string) ($preset['note'] ?? ''), 'min_ram_mb' => (int) ($preset['min_ram_mb'] ?? 0), 'versions' => array_values(array_map('strval', (array) ($preset['versions'] ?? []))), 'inputs' => $templates->inputForms((string) $eggKey)]; // §5u-3: fields with hints; §5s: what the order asks for; §5p: the versions a template offers in the wizard
            }
            $out[] = ['key' => $product['key'], 'family' => $product['family'], 'category' => $category, 'name' => (string) $product['name'], 'description' => (string) ($product['description'] ?? ''), 'plans' => $plans, 'orderable' => $orderable, 'eggs' => $eggs,
                'images' => array_values((array) data_get($product, 'meta.images', [])), 'engines' => array_values((array) data_get($product, 'meta.engines', [])), 'addons' => $this->addonRows($locale)[$product['key']] ?? null];
        }

        return $out;
    }

    /** Current versions of the documents an order must consent to (CheckoutService::requiredDocuments). @return array<string,string> */
    private function consentVersions(): array
    {
        $out = [];
        foreach (['terms', 'privacy', 'withdrawal_waiver', 'dpa', 'sla', 'registrar_terms'] as $key) {
            $document = ConsentDocument::current($key);
            if ($document !== null) {
                $out[$key] = (string) $document->version;
            }
        }

        return $out;
    }

    /**
     * Fakturace tab (api/onhost-panel-billing.api.js): the organization's most relevant document — the open one due first,
     * otherwise the latest settled one — with its lines, the bank details for transfers, the customer identity and the
     * monthly cost breakdown of the active subscriptions. Amounts are decimals; the panel formats money in its own currency/locale.
     */
    private function billing(string $organizationId, $services, bool $cs): array
    {
        $organization = Organization::query()->find($organizationId);
        $fmt = fn ($date) => $date === null ? null : Carbon::parse($date)->format($cs ? 'j. n. Y' : 'j M Y');
        $dec = fn (int|float $minor) => round($minor / 100, 2);
        $trim = fn ($n) => rtrim(rtrim(number_format((float) $n, 4, '.', ''), '0'), '.');
        $documents = Invoice::query()->where('organization_id', $organizationId)->whereIn('type', ['invoice', 'proforma'])->whereNotNull('number');
        $document = (clone $documents)->whereIn('state', [Invoice::ISSUED, Invoice::OVERDUE])->orderBy('due_at')->orderByDesc('issued_at')->first()
            ?? (clone $documents)->whereIn('state', [Invoice::PAID, Invoice::CREDITED])->orderByDesc('issued_at')->first();
        $seller = (array) ($document?->seller ?? []);
        if ($seller === []) {
            $entity = LegalEntity::query()->orderBy('key')->first();
            $seller = $entity === null ? [] : ['iban' => $entity->iban, 'bic' => $entity->bic, 'bank_account' => $entity->bank_account];
        }

        $doc = null;
        if ($document !== null) {
            $lines = $document->lines()->get();
            $from = $lines->min('period_from');
            $to = $lines->max('period_to');
            $overdue = $document->state === Invoice::OVERDUE || ($document->state === Invoice::ISSUED && $document->due_at !== null && $document->due_at->isPast());
            $previous = (clone $documents)->where('id', '!=', $document->id)->where('issued_at', '<', $document->issued_at)->orderByDesc('issued_at')->first();
            $buyer = (array) ($document->buyer ?? []);
            $doc = [
                'id' => $document->id, 'number' => $document->number, 'type' => $document->type, 'currency' => $document->currency,
                'state' => match (true) {
                    $document->state === Invoice::PAID => 'paid', $document->state === Invoice::CREDITED => 'credited', $document->state === Invoice::CANCELLED => 'cancelled', $overdue => 'overdue', default => 'due'
                },
                'issued' => $fmt($document->issued_at), 'due' => $fmt($document->due_at), 'paid' => $fmt($document->paid_at), 'period' => $from && $to ? $fmt($from).' – '.$fmt($to) : null,
                'lines' => $lines->map(fn ($l) => [
                    'name' => $l->description,
                    'sub' => implode(' · ', array_filter([$l->period_from && $l->period_to ? $fmt($l->period_from).' – '.$fmt($l->period_to) : null, $l->sku, ($cs ? 'DPH ' : 'VAT ').$trim($l->tax_rate).' %'])),
                    'qty' => $trim($l->qty).' '.$l->unit, 'unit' => $dec((int) $l->unit_net_minor), 'total' => $dec((int) $l->net_minor),
                ])->values()->all(),
                'subtotal' => $dec((int) $document->subtotal_minor), 'discount' => $dec((int) $document->discount_minor), 'tax' => $dec((int) $document->tax_minor), 'total' => $dec((int) $document->total_minor),
                'paid_amount' => $dec((int) $document->paid_minor), 'outstanding' => $dec(max(0, (int) $document->total_minor - (int) $document->paid_minor)),
                'tax_rates' => collect($document->tax_summary ?? [])->pluck('rate')->filter(fn ($r) => $r !== null)->map($trim)->unique()->values()->all(),
                'payment_reference' => $document->payment_reference, 'payment_method' => $document->payment_method,
                'buyer' => ['name' => $buyer['name'] ?? null, 'ico' => $buyer['ico'] ?? null, 'vat_id' => $buyer['vat_id'] ?? ($buyer['dic'] ?? null), 'email' => $buyer['email'] ?? null],
                'previous' => $previous === null ? null : ['number' => $previous->number, 'state' => $previous->state === Invoice::PAID ? 'paid' : 'open', 'paid' => $fmt($previous->paid_at)],
            ];
        }

        // monthly spend per group of the active subscriptions, grouped the way the panel groups services
        $family = $services->pluck('family', 'id');
        $groups = [];
        foreach (Subscription::query()->where('organization_id', $organizationId)->where('state', Subscription::ACTIVE)->get() as $sub) {
            $key = $sub->domain_id !== null ? 'domain' : match ($family->get($sub->service_id)) {
                'cloud' => 'cloud', 'game' => 'game', 'web', 'managed', 'apps' => 'web', 'mail' => 'mail', 'addon' => 'addon', default => 'other'
            };
            $monthly = $sub->period === 'year' ? intdiv((int) $sub->amount_minor, 12) : (int) $sub->amount_minor;
            $groups[$key] = ['key' => $key, 'count' => ($groups[$key]['count'] ?? 0) + 1, 'amount' => ($groups[$key]['amount'] ?? 0) + $monthly];
        }
        $breakdown = array_values(array_map(fn ($g) => ['key' => $g['key'], 'count' => $g['count'], 'amount' => $dec($g['amount'])], $groups));
        usort($breakdown, fn ($a, $b) => $b['amount'] <=> $a['amount']);

        // what was actually invoiced (tax documents only): the six-month average for the "Průměr 6 měsíců" stat and the
        // twelve-month "Náklady podle služeb" chart — columns are percent heights [label, servers, hosting, other]
        $taxDocuments = Invoice::query()->where('organization_id', $organizationId)->where('type', 'invoice')->whereIn('state', [Invoice::ISSUED, Invoice::OVERDUE, Invoice::PAID])
            ->where('issued_at', '>=', now()->subMonths(11)->startOfMonth())->with('lines')->get();
        $invoiced = (int) $taxDocuments->filter(fn ($i) => $i->issued_at >= now()->subMonths(6)->startOfMonth())->sum('total_minor');
        $groupOf = fn ($line): string => match (true) {
            in_array($family->get($line->service_id), ['cloud', 'game'], true) => 'servers',
            in_array($family->get($line->service_id), ['web', 'managed', 'apps', 'mail'], true) || str_starts_with((string) $line->sku, 'domain') => 'hosting',
            default => 'other',
        };
        $months = [];
        for ($i = 11; $i >= 0; $i--) {
            $months[now()->subMonths($i)->format('Y-m')] = ['servers' => 0, 'hosting' => 0, 'other' => 0];
        }
        foreach ($taxDocuments as $invoice) {
            $key = $invoice->issued_at->format('Y-m');
            foreach ($invoice->lines as $line) {
                if (isset($months[$key])) {
                    $months[$key][$groupOf($line)] += (int) $line->net_minor;
                }
            }
        }
        $names = $cs ? ['Led', 'Úno', 'Bře', 'Dub', 'Kvě', 'Čvn', 'Čvc', 'Srp', 'Zář', 'Říj', 'Lis', 'Pro'] : ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        $peak = max(1, max(array_map('array_sum', $months)));
        $columns = [];
        foreach ($months as $key => $split) {
            $columns[] = [$names[(int) substr($key, 5, 2) - 1], round($split['servers'] / $peak * 85, 1), round($split['hosting'] / $peak * 85, 1), round($split['other'] / $peak * 85, 1)];
        }
        $totals = ['servers' => array_sum(array_column($months, 'servers')), 'hosting' => array_sum(array_column($months, 'hosting')), 'other' => array_sum(array_column($months, 'other'))];
        if (array_sum($totals) === 0) { // nothing invoiced yet: the legend shows the split of the current subscriptions
            foreach ($groups as $g) {
                $totals[match ($g['key']) {
                    'cloud', 'game' => 'servers', 'web', 'mail', 'domain' => 'hosting', default => 'other'
                }] += $g['amount'];
            }
        }
        $share = fn (string $k) => array_sum($totals) > 0 ? (string) round($totals[$k] / array_sum($totals) * 100).' %' : '0 %';
        $chart = [
            'months' => $columns,
            'legend' => [[$cs ? 'Servery a hry' : 'Servers and games', $share('servers')], [$cs ? 'Web, e-mail a domény' : 'Web, e-mail and domains', $share('hosting')], [$cs ? 'Doplňky a ostatní' : 'Add-ons and other', $share('other')]],
        ];

        // transfers the customer still owes: every pending bank intent with its symbol, so the instructions never depend on a closed toast
        $pending = PaymentIntent::query()->where('organization_id', $organizationId)->where('provider', 'bank')->whereIn('state', [PaymentState::CREATED, PaymentState::PENDING_CUSTOMER])->orderByDesc('created_at')->limit(20)->get()
            ->map(function (PaymentIntent $i) use ($cs, $fmt) {
                $ins = (array) ($i->raw['instructions'] ?? []);
                $for = match ($i->purpose) {
                    'order' => ($cs ? 'Objednávka ' : 'Order ').(Order::query()->where('id', $i->reference_id)->value('number') ?? ''),
                    'invoice' => ($cs ? 'Faktura ' : 'Invoice ').(Invoice::query()->where('id', $i->reference_id)->value('number') ?? ''),
                    'topup' => $cs ? 'Dobití kreditu' : 'Credit top-up',
                    default => $i->purpose,
                };

                return ['id' => $i->id, 'purpose' => $i->purpose, 'for' => trim($for), 'amount' => round($i->amount_minor / 100, 2), 'currency' => $i->currency, 'variable_symbol' => $ins['variable_symbol'] ?? null, 'message' => $ins['message'] ?? null, 'iban' => $ins['iban'] ?? null, 'account_number' => $ins['account_number'] ?? null, 'qr_spd' => $ins['qr_spd'] ?? null, 'created' => $fmt($i->created_at)];
            })->values()->all();

        return [
            'document' => $doc, 'breakdown' => $breakdown, 'monthly' => $dec((int) array_sum(array_column($groups, 'amount'))), 'average_6m' => $dec(intdiv($invoiced, 6)), 'chart' => $chart, 'pending' => $pending,
            'bank' => ['account' => $seller['bank_account'] ?? null, 'iban' => $seller['iban'] ?? null, 'bic' => $seller['bic'] ?? null],
            'organization' => ['name' => $organization?->name, 'ico' => $organization?->ico, 'vat_id' => $organization?->vat_id ?: $organization?->dic, 'billing_email' => $organization?->billing_email, 'billing_mode' => $organization?->billing_mode, 'customer_class' => $organization?->customer_class],
            'terms' => ['due_days' => (int) config('onhost.billing.invoice_due_days', 14)],
            'dunning' => (array) config('onhost.billing.dunning'),
            'wallet' => ['auto_topup' => $organization !== null ? app(AutoTopup::class)->settings($organization) : null, 'payment_methods' => $organization !== null ? app(PaymentService::class)->methods($organization) : []], // the automatic top-up policy row (audit §5e-2) and the stored cards (audit §5f-1)
            'sla' => $services->pluck('sla_class')->filter()->unique()->values()->all(),
        ];
    }

    /** Account-level numbers the overview shows: wallet credit, 30-day availability of the components the organization uses. */
    private function kpis(string $organizationId, $services, bool $cs): array
    {
        $organization = Organization::query()->find($organizationId);
        $credit = null;
        if ($organization !== null) {
            try {
                $credit = (float) app(WalletService::class)->spendable($organization, $organization->currency ?? 'CZK')->toDecimal();
            } catch (\Throwable) {
                $credit = null;
            }
        }
        $families = $services->pluck('family')->unique()->all();
        $components = collect($this->incidents->publicStatus()['components'])->filter(fn ($c) => $families === [] || in_array($c['group'] ?? null, $families, true) || in_array($c['key'], ['portal', 'dns'], true));
        $uptime = $components->isEmpty() ? null : (float) $components->min('u');
        $formatted = $uptime === null ? null : rtrim(rtrim(number_format($uptime, 3, '.', ''), '0'), '.');

        return [
            'credit' => $credit, 'currency' => $organization?->currency ?? 'CZK',
            'uptime' => $formatted === null ? null : ($cs ? str_replace('.', ',', $formatted).' %' : $formatted.'%'),
            'open_tickets' => Ticket::query()->where('organization_id', $organizationId)->whereNotIn('state', ['RESOLVED', 'CLOSED'])->count(),
            'unpaid' => (float) Invoice::query()->where('organization_id', $organizationId)->where('type', 'invoice')->where('state', Invoice::ISSUED)->sum('total_minor') / 100,
            // public components currently degraded or down: the sidebar's status line points at the status page instead of narrating "nine locations"
            'incidents' => count(array_filter($this->incidents->publicStatus()['components'], fn (array $c) => ($c['state'] ?? 'operational') !== 'operational')),
        ];
    }

    private function domainState(string $state, bool $cs): string
    {
        return match ($state) {
            'ACTIVE' => $cs ? 'v pořádku' : 'fine', 'PENDING_TRANSFER' => 'transfer', 'PENDING_REGISTRATION' => $cs ? 'registrace' : 'registering', 'EXPIRING' => $cs ? 'expiruje' : 'expiring', 'EXPIRED' => $cs ? 'expirovaná' : 'expired', default => strtolower($state),
        };
    }
}
