[CmdletBinding()]
param([switch] $Quick, [switch] $Json)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

$root = Get-OnhostRepoRoot
$php = Get-OnhostPhp
$composerPhar = Get-OnhostComposerPhar
$checks = [System.Collections.Generic.List[object]]::new()
$overall = $true

function Add-SecurityCheck {
    param([string] $Name, [bool] $Ok, [string] $Detail)
    $script:checks.Add([ordered]@{ name = $Name; result = $(if ($Ok) { 'PASS' } else { 'FAIL' }); detail = $Detail })
    if (-not $Ok) { $script:overall = $false }
}

$tracked = @(Invoke-OnhostGit $root ls-files)
$forbidden = @($tracked | Where-Object {
    $_ -eq '.env' -or
    (($_ -like '.env.*') -and $_ -ne '.env.example') -or
    $_ -eq 'auth.json' -or
    (($_ -like 'storage/app/private/*') -and $_ -ne 'storage/app/private/.gitignore') -or
    (($_ -like 'storage/logs/*') -and $_ -ne 'storage/logs/.gitignore') -or
    $_ -match '^database/.*\.sqlite(?:-|$)' -or
    $_ -match '^infra/edge/.*\.generated$'
})
Add-SecurityCheck 'Forbidden tracked files' ($forbidden.Count -eq 0) $(if ($forbidden.Count -eq 0) { 'none' } else { "found $($forbidden.Count); inspect with git ls-files" })

$gitleaks = Get-OnhostCommand 'gitleaks'
if ($gitleaks) {
    Push-Location $root
    try {
        $previousPreference = $ErrorActionPreference
        $ErrorActionPreference = 'Continue'
        if ($Json) { & $gitleaks git --redact=100 --no-banner . 2>&1 | Out-Null }
        else { & $gitleaks git --redact=100 --no-banner . }
        $gitleaksCode = $LASTEXITCODE
        $ErrorActionPreference = $previousPreference
        Add-SecurityCheck 'Gitleaks history scan' ($gitleaksCode -eq 0) "exit $gitleaksCode; values redacted"
    } finally {
        $ErrorActionPreference = $previousPreference
        Pop-Location
    }
} else {
    Add-SecurityCheck 'Gitleaks available' $false 'install with scripts/ai/install-tools.ps1'
}

if (-not $Quick) {
    if ($php -and $composerPhar) {
        Push-Location $root
        try {
            if ($Json) { & $php $composerPhar audit --locked --no-interaction *> $null }
            else { & $php $composerPhar audit --locked --no-interaction }
            $composerCode = $LASTEXITCODE
            Add-SecurityCheck 'Composer audit' ($composerCode -eq 0) "exit $composerCode"
        } finally { Pop-Location }
    } else { Add-SecurityCheck 'Composer audit' $false 'Composer not found' }

    $npm = Get-OnhostCommand 'npm'
    if ($npm) {
        Push-Location $root
        try {
            if ($Json) { & $npm audit --package-lock-only --audit-level=high *> $null }
            else { & $npm audit --package-lock-only --audit-level=high }
            $npmCode = $LASTEXITCODE
            Add-SecurityCheck 'npm audit' ($npmCode -eq 0) "exit $npmCode"
        } finally { Pop-Location }
    } else { Add-SecurityCheck 'npm audit' $false 'npm not found' }
}

$revision = (Invoke-OnhostGit $root rev-parse --short=12 origin/development | Select-Object -First 1)
$rows = ConvertTo-OnhostMarkdownTable $checks
$report = @"
# Security status

> Generated by brain.ps1 security for revision $revision. Secret values are never included.

$rows

**Overall:** $(if ($overall) { 'PASS' } else { 'FAIL' })
"@
if (-not $Quick -or -not (Test-Path -LiteralPath (Join-Path $root 'docs\generated\SECURITY_STATUS.md'))) {
    [void](Write-OnhostText (Join-Path $root 'docs\generated\SECURITY_STATUS.md') $report)
}

if ($Json) {
    [ordered]@{ ok = $overall; revision = $revision; checks = @($checks) } | ConvertTo-Json -Depth 6
} else {
    Write-Host 'ONHOST Brain security' -ForegroundColor Cyan
    foreach ($check in $checks) {
        $mark = if ($check.result -eq 'PASS') { '[ok]' } else { '[!!]' }
        Write-Host ("  {0,-4} {1,-26} {2}" -f $mark, $check.name, $check.detail)
    }
}

if (-not $overall) { exit 1 }
exit 0
