[CmdletBinding()]
param(
    [switch] $Quick,
    [switch] $E2E,
    [switch] $Json
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

$root = Get-OnhostRepoRoot
$php = Get-OnhostPhp
if (-not $php) { Write-Error 'PHP 8.3 was not found.'; exit 1 }

$steps = [System.Collections.Generic.List[object]]::new()
function Invoke-ValidationStep {
    param([string] $Name, [string] $File, [string[]] $Arguments)

    Write-Host "`n== $Name ==" -ForegroundColor Cyan
    $started = Get-Date
    & $File @Arguments | Out-Host
    $code = $LASTEXITCODE
    [void]$steps.Add([ordered]@{
        name = $Name
        result = $(if ($code -eq 0) { 'PASS' } else { 'FAIL' })
        detail = ('exit {0}; {1:n1}s' -f $code, ((Get-Date) - $started).TotalSeconds)
    })
    return ($code -eq 0)
}

Push-Location $root
try {
    $ok = Invoke-ValidationStep 'Pint' $php @('vendor/bin/pint', '--test')
    if (-not $Quick) {
        $ok = (Invoke-ValidationStep 'Larastan' $php @('vendor/bin/phpstan', 'analyse', '--memory-limit=1G')) -and $ok
    }
    $testArgs = @('artisan', 'test', '--compact')
    if ($Quick) { $testArgs += '--testsuite=Unit' }
    $ok = (Invoke-ValidationStep 'Pest' $php $testArgs) -and $ok
    if (-not $Quick) {
        $npm = Get-OnhostCommand 'npm'
        if (-not $npm) { throw 'npm was not found.' }
        $ok = (Invoke-ValidationStep 'Frontend build' $npm @('run', 'build')) -and $ok
    }
    if ($E2E) {
        $npm = Get-OnhostCommand 'npm'
        $ok = (Invoke-ValidationStep 'Playwright' $npm @('run', 'e2e')) -and $ok
    }
} finally {
    Pop-Location
}

$revision = (Invoke-OnhostGit $root rev-parse --short=12 origin/development | Select-Object -First 1)
$rows = ConvertTo-OnhostMarkdownTable $steps
$report = @"
# Test status

> Generated by brain.ps1 test for revision $revision.

$rows

**Overall:** $(if ($ok) { 'PASS' } else { 'FAIL' })
"@
if (-not $Quick -or -not (Test-Path -LiteralPath (Join-Path $root 'docs\generated\TEST_STATUS.md'))) {
    [void](Write-OnhostText (Join-Path $root 'docs\generated\TEST_STATUS.md') $report)
}

if ($Json) {
    [ordered]@{ ok = $ok; revision = $revision; checks = @($steps) } | ConvertTo-Json -Depth 6
}

if (-not $ok) { exit 1 }
exit 0
