[CmdletBinding()]
param([switch] $Json)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

$root = Get-OnhostRepoRoot
$generated = Join-Path $root 'docs\generated'
$branch = (Invoke-OnhostGit $root rev-parse --abbrev-ref HEAD | Select-Object -First 1)
$revision = (Invoke-OnhostGit $root rev-parse --short=12 origin/development | Select-Object -First 1)
$dirty = @(Invoke-OnhostGit $root status --porcelain -- . ':(exclude)docs/generated/**')
$domains = @(Get-ChildItem -LiteralPath (Join-Path $root 'domains') -Directory | Sort-Object Name | Select-Object -ExpandProperty Name)
$composer = Get-Content -LiteralPath (Join-Path $root 'composer.json') -Raw | ConvertFrom-Json
$package = Get-Content -LiteralPath (Join-Path $root 'package.json') -Raw | ConvertFrom-Json

$projectState = @"
# Project state

> Generated by brain.ps1 update. Do not edit by hand.

| Item | Value |
| --- | --- |
| Branch | $branch |
| Base revision | $revision |
| Working changes outside generated context | $($dirty.Count) |
| PHP requirement | $($composer.require.php) |
| Laravel requirement | $($composer.require.'laravel/framework') |
| Node requirement | 20+ |
| Vite requirement | $($package.devDependencies.vite) |
| Domain modules | $($domains.Count) |

## Domain modules

$($domains -join ', ')

## Context entry points

- AGENTS.md
- docs/context/CURRENT_STATE.md
- docs/context/DOMAIN_MAP.md
- docs/adr
- docs/runbooks
"@

$log = @(Invoke-OnhostGit $root log origin/development -10 --date=short '--pretty=format:%h|%ad|%s')
$recentRows = foreach ($entry in $log) {
    $parts = $entry -split '\|', 3
    if ($parts.Count -eq 3) { "| $($parts[0]) | $($parts[1]) | $($parts[2] -replace '\|', '\|') |" }
}
$recent = @"
# Recent changes

> Generated by brain.ps1 update from the shared development history. Do not edit by hand.

| Commit | Date | Subject |
| --- | --- | --- |
$($recentRows -join "`n")
"@

$defaultTest = @"
# Test status

> Generated status. Run brain.ps1 test to replace this placeholder.

No ONHOST Brain validation has been recorded for this revision.
"@

$defaultSecurity = @"
# Security status

> Generated status. Run brain.ps1 security to replace this placeholder.

No ONHOST Brain security validation has been recorded for this revision.
"@

$changed = @()
if (Write-OnhostText (Join-Path $generated 'PROJECT_STATE.md') $projectState) { $changed += 'PROJECT_STATE.md' }
if (Write-OnhostText (Join-Path $generated 'RECENT_CHANGES.md') $recent) { $changed += 'RECENT_CHANGES.md' }
if (-not (Test-Path -LiteralPath (Join-Path $generated 'TEST_STATUS.md'))) {
    [void](Write-OnhostText (Join-Path $generated 'TEST_STATUS.md') $defaultTest)
    $changed += 'TEST_STATUS.md'
}
if (-not (Test-Path -LiteralPath (Join-Path $generated 'SECURITY_STATUS.md'))) {
    [void](Write-OnhostText (Join-Path $generated 'SECURITY_STATUS.md') $defaultSecurity)
    $changed += 'SECURITY_STATUS.md'
}

$result = [ordered]@{
    project = 'ONHOST'
    branch = $branch
    revision = $revision
    changed = @($changed)
    generated = 'docs/generated'
}

if ($Json) {
    $result | ConvertTo-Json -Depth 5
} else {
    if ($changed.Count -eq 0) { Write-Host 'Context is already current.' -ForegroundColor Green }
    else { Write-Host ("Updated: {0}" -f ($changed -join ', ')) -ForegroundColor Green }
}
